### PR TITLE
Fix tab checkbox confusion

### LINKED ISSUE #498: tabs don't act like tabs without JavaScript
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

https://github.com/searxng/searxng/commit/7a9dda

**How did you install SearXNG?**

    make run

**What happened?**

There is a "click on the .."  text direct under the categories

grafik

**How To Reproduce**

~It is very strange:~ The issue appears when I enable plugins / see https://github.com/searxng/searxng/issues/498#issuecomment-968061989 and 6debda2 :

```yaml
enabled_plugins:
  - "Hostname replace"  # see configuration below

# "Hostname replace" plugin configuration example:
hostname_replace:
    'spam\.example\.com':             false  # remove results from spam.example.com
```
---

**Another issue I observe since  7a9dda**

There is a line break in the category column that overlaps in the column size of the table layout ..

grafik

### PR DESCRIPTION
**Pull request by not-my-profile**
## What does this PR do?

See the commit messages.

## Related issues

Fixes #498

### CODE REVIEW

**Comment by return42** [comment]
@not-my-profile FYI I rebased the PR (your branch)

**Comment by return42** [comment]
@mrpaulblack @dalf .. could you have a look at this PR .. IMO checkboxes for categories give bad UX ...

grafik

Beside it is not rendered well in different screen-size, it is hard for me to switch the category from e.g. "general" to "images" .. if I'm not wrong, I need at least three clicks:

- click to enable images categ
- click to disable general categ
- click on the magnifier

In master branch I just need a single click on the `images` tab (categ)

**Comment by not-my-profile** [comment]
> IMO checkboxes for categories give bad UX

No having stuff that doesn't look like checkboxes act like checkboxes gives bad UX. This PR fixes the UX problem.

>Beside it is not rendered well in different screen-size

I cannot reproduce this.

> I need at least three clicks [..] In master branch I just need a single click on the images tab (categ)

My PR doesn't change how many clicks it takes. I also cannot reproduce this.

**Comment by return42** [comment]
> ... maybe your rebase messed up my PR?

I did not change anything functional, I just rebased and made a new `make static.build.commit` commit on top .. usual procedure when there is a conflict in the client (/static) sources .. but I can't exclude side-effects when we merge this PR with the PRs from you of the last (two) days.  Could you please have a look / thanks.

**Comment by not-my-profile** [comment]
Nvm, I also cannot reproduce the problems you observed with your rebased branch. Maybe your browser still has the old CSS cached? Or can you try another browser? And tell me exactly how to reproduce the problems you experience?

**Comment by return42** [comment]
> And tell me exactly how to reproduce the problems you experience?

In your developer studio, activate "touch device" grafik

**Comment by return42** [comment]
> No having stuff that doesn't look like checkboxes act like checkboxes gives bad UX. This PR fixes the UX problem.

And the price are 3 clicks to switch from one to another categ?

**Comment by not-my-profile** [comment]
>And the price are 3 clicks to switch from one to another categ?

No as I explained my PR is not meant to change how many clicks it takes. If it does so that's a bug that I'll fix.

**Comment by dalf** [comment]
> @mrpaulblack @dalf .. could you have a look at this PR .. IMO checkboxes for categories give bad UX ...
>  I need at least three clicks: ...

this is the default behavior since searx exists, especially when javascript is disabled.
that's why there is a [search_on_category_select.js](https://github.com/searxng/searxng/blob/master/searx/static/plugins/js/search_on_category_select.js) plugin.

The plugin send the query as soon as a category is selected or any other fields is changed (language, date range, safe field).

---

Note about the simple theme:
It doesn't include search_on_category_select.js because:
  * it relies on jQuery which is not include in the simple theme (main reason).
  * the HTML elements are different.

<details>
<summary>related source code</summary>

  * https://github.com/searxng/searxng/blob/ced656606fbc7a5d5dda8b1e4efe16a9eb88e57b/searx/templates/simple/base.html#L22-L25
  * https://github.com/searxng/searxng/blob/ced656606fbc7a5d5dda8b1e4efe16a9eb88e57b/searx/static/themes/simple/src/js/head/00_init.js#L18-L22
  * https://github.com/searxng/searxng/blob/ced656606fbc7a5d5dda8b1e4efe16a9eb88e57b/searx/static/themes/simple/src/js/main/search.js#L90-L110
</details>

---

I've never used this feature: when I need multiple categories in result page I usually use:
* either the bangs. For example `!general !images something`. 
* either I look one category and then another one (because it requires to disable the plugin, save the preferences, send the query, checks the results, go back to preferences, change the settings again, and finally save).

IMO, the default behavior should be the "category on select", so the UX would be same when JS is disabled.
And if this feature is really important, then the HTML should be changed when "category on select" is disabled.

**Comment by not-my-profile** [comment]
>because it requires to disable the plugin, save the preferences, send the query, checks the results, go back to preferences, change the settings again, and finally save

The obvious solution to that is to allow the plugin to be quickly toggled from the results page.

**Comment by return42** [comment]
> The obvious solution to that is to allow the plugin to be quickly toggled from the results page.

If we add a toggle to the result page, we should also consider that we possibly need more toggles / I have https://github.com/searxng/searxng/issues/572 in mind.

**Comment by mrpaulblack** [comment]
I dont really understand this PR; It adds the actual checkbox UI for the categories on the result page with JS enabled as well as JS disabled; Also this breaks search on select, which means that the user needs to select the category and than start a search manually.

I would suggest the following (personal opinion):
* when JS enabled -> UI should be same as in current master
* when JS disabled than there are checkboxes in the same colomn as the label and visible on the left on LTR and on the right on RTL

(Also the search on select does not work because it expects the help text? `if (qinput !== null && d.querySelector('.help') != null && searxng.search_on_category_select)`)

**Comment by not-my-profile** [comment]
Ah yeah my bad ... I missed that the simple theme does not use the plugin JS ... I guess I'll have to fix that first (I opened #769 to track that).

**Pull request closed without merging**
