### PR TITLE
simple theme css refactor

### PR DESCRIPTION
**Pull request by mrpaulblack**
## What does this PR do?

Some simple theme improvements:

* make selected tabs in preferences keep the same width, compared to not being selected (they don't move the tab bar around anymore) -> removing bolt font and change in letter spacing.

* remove various `padding`, `margin` and `width` elements from sidebar and results -> on desktop: 10em margin on the left; on tablet -> 0.5em margin; on phone no margin at all; also there is a 2em margin between content and footer as well as content and the header search bar

* introduce grid layout to the result page to make layout changes between PC, Tablet and Smartphone smoother (based on dalf@0f60925) -> image page has a 0.5em margin on all screen sizes

* sticky footer at the bottom of the page (also from dalf@0f60925)

* remove various elements from toolkit to streamline url copy elements and engine errors in new grid layout

* add max width of 85em to stats, pref and about page; make margin around .checkbox-onoff elements bigger

* add a margin to index on landing page to center the search more (on desktop 16em, on tablet 6em and on mobile 0 to not get hidden by keyboard)

* hide the backtotop element on tablet and mobile

## Why is this change important?

Make the simple theme more polished...

## How to test this PR locally?

```make themes.all```

```make run```

## Author's checklist

Desktop

image

Tablet

image

Phone

image

### CODE REVIEW

**Comment by mrpaulblack** [comment]
### TODO

And two generic changes that can be part of another PR:

```
/* max width for the preferences, can be applied to some other pages like stats and about */
#main_preferences {
    margin: 3em auto;
    width: 90rem;
}

/* adjust the checkbox with the above changes, 
    see the engine tab
*/
.checkbox-onoff {
	margin: 8px 1rem;
}
```

* Sticky footer at bottom of page (don't forget margin for pref, stats and about at bottom; at least 10em)
* Use CSS vars as prep for dark theme? you could just make a class for the dark theme that can be applied to the body to switch

**Comment by dalf** [comment]
Additional notes: see https://github.com/dalf/searxng/commit/0f60925c13d34dae5534ae746f1731a0ba9a0e5f from the https://github.com/dalf/searxng/commits/simple_upgrade :
* changes on `body`, `main`, `footer` using flexbox --> footer at the bottom on the page.
* CSS grid for the other changes:
   * not finished (the layout is broken with some screen width).
   * may be it is easier to write response design CSS?

**Comment by mrpaulblack** [comment]
@dalf I did a PR in your fork to fix the grid layout stuff, so it also works on tablet screens and mobile: https://github.com/dalf/searxng/pull/31; Also I really like working with grid layout; I think this is the right direction for the simple theme, because it is easy to understand and it also makes the CSS a lot simpler, since this makes it possible to drop a lot of the `width`, `margin` and `padding` elements...

**Comment by mrpaulblack** [comment]
@dalf I cherry picked the commits from dalf#31 in your fork and added everything to this PR. Please test this before merge, since this changes a lot with the simple theme design... (especially the tablet and phone form factor); Also there is still a static build missing, because I get merge conflicts when trying to do the commit.

**Comment by dalf** [comment]
All seems works nicely, except two glitches, but I would like to do more testing before merge.

> I get merge conflicts when trying to do the commit

Can you describe the issue here or in a new issue?

---

image

The caret / arrow is displayed when you click on the text of a result (or use the `j`, `k` keys). It requires to enable "Vim-like hotkeys" in the preferences (User Interface tab)

The caret could be closer to the results:
```less
article[data-vim-selected]::before {
    left: (@results-offset - 2rem); // 8rem
}
```

----

The back to button is displayed at the wrong place (note: the cosmetic filtering of uBlock Origin hides this button)

image

-->

```less
#backToTop {
    margin: 0;
    bottom: 8rem;  // at the bottom on the page, the button doesn't overlap the footer
    left: 56em; // I'm not sure how to reach this number using the variables.
}
```

**Comment by mrpaulblack** [comment]
> Can you describe the issue here or in a new issue?

Not really an issue. I can do the static build commit, but than the PR has merge conflicts (searx.min.css, searx.min.js ando so on) with the master base branch. I could fix the issue with a merge of the changes from master into this PR branch, but this would mean a huge commit with all the commits since this branch on master. Idk how to fix this, so maybe the best option is to just not do a static build in this branch and do one after this PR is merged?

On another note: I understand that `rem` is relative to the font in the root element and `em` relative to the font in the element the css gets applied to. But how do you decide when to use rem and when to use em in your CSS?

Like in this example:
```less
#backToTop {
    margin: 0;
    bottom: 8rem;  // at the bottom on the page, the button doesn't overlap the footer
    left: 56em; // I'm not sure how to reach this number using the variables.
}
```
You first used rem and then em? Why tho?

**Comment by dalf** [comment]
> You first used rem and then em? Why tho?

It is a mistake, I think it should be rem everywhere, so it can follow the change of the browser font size. (I had rewatch https://www.youtube.com/watch?v=N5wpD9Ov_To ).

---

Some more issues: 

image

* The back to top button is not on the right side of the screen: https://github.com/searxng/searxng/blob/ad881a5515c41cc47672239cc0a83953c30d264c/searx/static/themes/simple/src/less/style.less#L772-L775
* `#pagination` could have a 1rem margin in tablet and smartphone modes : https://github.com/searxng/searxng/blob/ad881a5515c41cc47672239cc0a83953c30d264c/searx/static/themes/simple/src/less/style.less#L567-L573


A suggestion:
image

```css
@media screen and (max-width: 50em) {

  #backToTop {
    right: 1rem;
    bottom: 6.7rem;
    left: auto;
  }

  #pagination {
    margin: 1rem 5rem 1rem 1rem;
    ...
  }
}
```

Another one: hide the back to top button, and keep only a 1rem margin for #pagination.

**Comment by mrpaulblack** [comment]
Ok should all be fixed now; I decided to hide the backtotop on tablet and mobile since it is easier to just scroll.

[EDIT] also maybe you should sqash the commits; since there are some trial and error commits....

**Comment by dalf** [comment]
> Ok should all be fixed now; I decided to hide the backtotop on tablet and mobile since it is easier to just scroll.

👍 

> also maybe you should sqash the commits; since there are some trial and error commits....

Usually we pull rebase on master and then push force on the branch, so we can track merged PR more easily.

**Comment by return42** [comment]
> Usually we pull rebase on master and then push force on the branch, so we can track merged PR more easily.

@MrPaulBlack for my tests I rebased your branch on top of master and added a `make static.build.commit` commit on top  / see  [Development Quickstart](https://searxng.github.io/searxng/dev/quickstart.html).

I force pushed that on your branch, I hope this was OK for you.

> also maybe you should sqash the commits; since there are some trial and error commits....

If you have some hints which commits you want to squash, I can do it for you.

**Comment by mrpaulblack** [comment]
Great! Thank you. If you could sqash the last 4 fix commits into one that would be great; so 09a61a3e78d4c5c7e73bf73564acf676d9000ef4 09a61a3e78d4c5c7e73bf73564acf676d9000ef4 09a61a3e78d4c5c7e73bf73564acf676d9000ef4 and 7b2bf649e52ed5f1e24d3fa8ddc01d25f5098e09. I did a lot of trial an error in this commits and changed basically the same css stuff around in each of them...

**Comment by return42** [comment]
>  If you could sqash the last 4 fix commits into one

done .. could you please have a look if I authored the commit messages correctly in ~f91adca~ / thanks!

EDIT: I mean in 8268873 :)

**Comment by mrpaulblack** [comment]
Looks great, Thank you! I also did another fix to the pagination and backtotop on the image result page. Should be ready for review/merge now...

**Comment by return42** [comment]
> I also did another fix to the pagination and backtotop on the image result page. 

Tested with FFox & Chrome .. LGTM ..  thanks!

**Review by return42 — APPROVED** [review]
@dalf for me this PR is ready to merge, do you see any more issues we need to fix before merging?

**Comment by return42** [comment]
> remove various elements from toolkit to streamline url copy elements and engine errors in new grid layout

Hm, may be someone can help me: for what is this searx/static/themes/simple/src/less/toolkit.less used?

**Comment by mrpaulblack** [comment]
As far as I understand: The toolkit is used for CSS that is applied to "widgets". Meaning: The CSS is for generic elements like headings, the URL box, dialog boxes and stuff like that... So the CSS from toolkit.less is applied to the dialog box with the engine errors and the search URL element in the sidebar for example...

**Comment by return42** [comment]
> The toolkit is used for CSS that is applied to "widgets".

.. make sense  .. I was a little confused by the comment ...

https://github.com/searxng/searxng/blob/b046322c7b9467a7de6e9e289e1c5b0c0baaf4a6/searx/static/themes/simple/src/less/toolkit.less#L1

.. thanks for clarify! May you can also clarify for me for what the simple/src/less/toolkit_loader.less is used? (sorry for my dump questions).

**Comment by dalf** [comment]
> simple/src/less/toolkit_loader.less

It was used to display a spinner while the overpass data were loaded ("Show details" / "Hide details"):
image

Since https://github.com/searxng/searxng/pull/90 the OSM engine loads use only the OSM API (and get the same data), so a AJAX request is not required. I think we can keep it for now in case we need to dynamically load data.

**Comment by dalf** [comment]
@MrPaulBlack  thank you for this PR !
I think we can iterate with different PR to backport the changes you have made in your fork.

@return42  thank you for the clean up.

**Comment by mrpaulblack** [comment]
NP. The backport is no big deal since I am just tracking the build searx.css. I can just use the upstream searx.css and put the changes into the searx.css of my fork with git diff... (Eventually I want to only track my custom color scheme in definitions.less in my fork tho)

**Pull request merged**
