### PR TITLE
[fix] get_bang_url: handle ambiguous !!bangs without error

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

[fix] get_bang_url: handle ambiguous !!bangs without error

## Why is this change important?

An ambiguous bang like `!!d` raises an exception in function get_bang_url().  A
bang is only unique when the bang_definition from get_bang_definition_and_ac() is
a string / for a ambiguous bang the returned bang_definition is a dictionary.

## How to test this PR locally?

    make run

Search for `!!d foo`

## Related issues

Reported-by: user @prg318 at #searxng:matrix.org on 2022/01/11

### CODE REVIEW

**Comment by return42** [comment]
This PR need some more work, the initial issue is fixed but there is another issue:

Bangs with a `*` suffix, e.g. `!!d*`:

```json
{
    "c":"Online Services",
    "d":"www.joindiaspora.com",
    "r":0,
    "s":"Diaspora*",
    "sc":"Social",
    "t":"d*",
    "u":"https://www.joindiaspora.com/people?utf8=\u2713&q={{{s}}}"
}
```

will overwrite bangs with the same prefix, e.g. `!!d`

```json
{
    "c":"Research",
    "d":"www.thefreedictionary.com",
    "r":5478,"s":"The Free Dictionary",
    "sc":"Academic",
    "t":"d",
    "u":"http://www.thefreedictionary.com/{{{s}}}"
}
```

I assume it is caused by the `*` default:

https://github.com/searxng/searxng/blob/977e9a433085124e17f2f7f26afabbeb71db9470/searxng_extra/update/update_external_bangs.py#L141

**Comment by return42** [comment]
@dalf are you active working on https://github.com/searxng/searxng/pull/740#issuecomment-1010411888 .. if not, I can have a look.

**Comment by dalf** [comment]
>  @dalf are you active working on #740 (comment)

not right now

> I can have a look.

👍

**Comment by return42** [comment]
@dalf I fixed issue of the optimized digital trie in 7cdd314 / if you have time for a review.

**Review by dalf — APPROVED** [review]
Good catch.
Thank you!

**Pull request merged**
