### PR TITLE
[theme] /preferences: rename "Method" to "HTTP Method"

### LINKED ISSUE #751: /preferences: rename "Method" to "HTTP Method".
image

Should Method be renamed "HTTP Method" ?

Source code:
* https://github.com/searxng/searxng/blob/74847fe9029187e792d44eba49ef5a2cbc6c514a/searx/templates/oscar/preferences.html#L262
* https://github.com/searxng/searxng/blob/master/searx/templates/simple/preferences.html#L237

### PR DESCRIPTION
**Pull request by return42**
Closes: https://github.com/searxng/searxng/issues/751

### CODE REVIEW

**Comment by not-my-profile** [comment]
How about also fixing the description? "Search language" isn't right.

**Comment by return42** [comment]
> How about also fixing the description? "Search language" isn't right.

Oops .. / thanks for pointing out / fixed in 08b38a8b, copied the description from oscar theme.

**Comment by not-my-profile** [comment]
I think while we have the Oscar theme it should be changed there as well for consistency.

**Comment by return42** [comment]
> I think while we have the Oscar theme it should be changed there as well for consistency.

Sorry I don't know what you mean by .. both themes have the same "HTTP Method" and the same description.

**Comment by not-my-profile** [comment]
Ah, my bad ... I misread the diff.

**Pull request merged**
