### PR TITLE
Search filters changes

### PR DESCRIPTION
**Pull request by MontyQI**
## What does this PR do?

Improves search filters for mobile. 
before

https://user-images.githubusercontent.com/79922836/155386438-4ac85d55-8fc5-405f-afc6-03f22c3845a5.mp4

   
## Why is this change important?
Makes searxng  more accessible for mobile users.

## How to test this PR locally?

`make run`

### CODE REVIEW

**Comment by MontyQI** [comment]
`lang_id, lang_name, country, english_name = map(str.lower, lc)
ValueError: too many values to unpack (expected 4)`
The checks failed because of the flags, but when I tested it, it worked.

Edit: Just need to change line 88 in query.py. I'll do it tomorrow.

**Comment by dalf** [comment]
> Improves search filters for mobile.

👍 thank you !

> adds flags indicating languages,

Unfortunately, [`update_languages.py`](https://github.com/searxng/searxng/blob/master/searxng_extra/update/update_languages.py) overwrites `searx/languages.py` automatically every month.

So, the idea is to:
* update `update_languages.py` to add the flag.
* call it to update `searx/languages.py`.

May be the flag can be added in another pull request (?)

[EDIT] In addition, the language preference actually choose two things: the language and the region.

<details>
<summary>`flag` variable in `update_language.py`</summary>

```python
flags = {
    'EG': '🇸🇦',
    'BY': '🇧🇾',
    'BG': '🇧🇬',
    'CZ': '🇨🇿',
    'DK': '🇩🇰',
    'de': '🇩🇪',
    'GR': '🇬🇷',
    'GB': '🇬🇧', # US / UK ?
    'ES': '🇪🇸', #
    'EE': '🇪🇪',
    'IR': '🇮🇷',
    'FI': '🇫🇮',
    'FR': '🇫🇷',
    'IL': '🇮🇱',
    'IN': '🇮🇳',
    'HR': '🇭🇷',
    'HU': '🇭🇺',
    'ID': '🇮🇩',
    'IS': '🇮🇸',
    'IT': '🇮🇹',
    'JP': '🇯🇵',
    'KR': '🇰🇷',
    'LT': '🇱🇹',
    'LV': '🇱🇻',
    'NL': '🇳🇱',
    'PL': '🇵🇱',
    'pt': '🇵🇹',
    'RO': '🇷🇴',
    'RU': '🇷🇺',
    'SK': '🇸🇰',
    'SI': '🇸🇮',
    'RS': '🇷🇸',
    'SE': '🇸🇪',
    'TH': '🇹🇭',
    'TR': '🇹🇷',
    'UA': '🇺🇦',
    'VN': '🇻🇳',
    'zh-CN': '🇨🇳',   # zh is not enough. zh-CN = simplified Chinese (from mainland China)
    'zh-HK': '🇭🇰',  # traditional Chinese (Hong Kong)
    'zh-TW': '🇹🇼',  # traditional Chinese (Taiwan). Usually occidental search engines display only a choice between simplified & traditional Chinese.
}
```

</details>

> displays English name of language instead of name in language it indicates.

Between native and English name, I would keep the native name:
* the English name suppose the user understand English : it may be not the case.
* the native name suppose the user understand the language, which is expected. 

Other search engines:
* Native names:
  * https://www.google.com/preferences?hl=fr&fg=1#languages
  * https://duckduckgo.com/settings
  * https://www.qwant.com/?drawer=settings
* Native and English names:
  * https://www.bing.com/account/general?ru=https%3a%2f%2fwww.bing.com%2f&FORM=O2HV65&id=language_section#language-section
  * https://search.brave.com/

ping @MarcAbonce @mrpaulblack @return42 

----

About the error: 
https://github.com/searxng/searxng/blob/8d937179ab42296af4235952e44c5961e355e9d4/searx/query.py#L88

This line needs to be updated.

----

For reference, related to : https://github.com/searxng/searxng/pull/247

**Comment by mrpaulblack** [comment]
I really like the CSS changes of this PR :+1: 

Also I am fully behind dalfs comment that we can update the update_languages.py script in another PR and that we should not use the English name for all the other languages. (Also the flags are a great addition)

**Comment by dalf** [comment]
Can you adjust the commit message:

> Flags in language filter, better search filters view on mobile.

After that, the PR can be merged.

Thanks a lot

**Comment by MontyQI** [comment]
I thought this will be in next pr, but ok

**Comment by mrpaulblack** [comment]
Yeah flags in another PR, but remove the flags from the commit message in this PR please...

So change the commit message for your first commit to `better search filters view on mobile` for example :+1:

**Comment by mrpaulblack** [comment]
Thanks :D

**Pull request merged**
