### PR TITLE
Changed preferences icon to settings icon in gruntfile

### PR DESCRIPTION
**Pull request by MontyQI**
## What does this PR do?

Changes preferences icon to settings icon from material design.
## Why is this change important?

It will be easier to associate with settings.
## How to test this PR locally?

`make run`
change theme to simple

### CODE REVIEW

**Comment by MontyQI** [comment]
Sorry for deleting the previous one, I've accidentally done it.

**Review by mrpaulblack — APPROVED** [review]
LGTM; thanks :+1: 

@dalf are you ok with this change? For example google is using a gear icon for its settings...

**Comment by MontyQI** [comment]
This icon is from material design so it's the same as google uses.

**Review by return42 — APPROVED** [review]

**Comment by dalf** [comment]
Thank you !

**Pull request merged**
