### PR TITLE
[brand] SearXNG environment variables & /utils scripts

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

Renames various environment variables from `SEARX_...` to `SEARXNG_..` 

For more details have a look at the commit messages

## How to test this PR locally?

I tested the scripts in LXC and at https://darmarit.org/searx/search

## Related issues

Related: 

- https://github.com/searxng/searxng/pull/358
- https://github.com/searxng/searxng/issues/425

### CODE REVIEW

**Comment by dalf** [comment]
More or less related to #450 : since the master branch is rolling release, not to surprise admins, it can be useful to detect the previous installation (before this PR), and stop with a HTTP link explaining how to do the migration.

But I'm not sure how the migration can be done ? remove everything and then reinstall everything ?

**Comment by return42** [comment]
> since the master branch is rolling release, not to surprise admins, it can be useful to detect the previous installation 
> .. But I'm not sure how the migration can be done ? remove everything and then reinstall everything ?

For _rolling release_ I suggest a script that does some tests and gives some hints .. I prepared such a script in #456.

May be we first merge #456 and after we can discuss what "checks" need to implement for this PR?

**Comment by return42** [comment]
> But I'm not sure how the migration can be done ? remove everything and then reinstall everything ?

FYI:  there is now a `./utils/searx.sh install check`  script.

**Comment by dalf** [comment]
I'm not sure how to test the first 3 commits.

What I have done:

* on a new VM:
  * I have install SearXNG using `sudo -H ./utils/searx.sh install all`
  * switched to this branch
  * `sudo -H ./utils/searx.sh update searx`
  * it seems to work seamlessly

* on another new VM:
  * switched to this branch
  * I have install SearXNG using `sudo -H ./utils/searx.sh install all`

It both cases it seems to work.

```
$ sudo -H ./utils/searx.sh install check
INFO:  using instance at: /usr/local/searx/searx-src
INFO:  switching to /usr/local/searx/searx-src/.config.sh

============================
SearXNG (check installation)
============================
INFO:  SearXNG instance already installed at: /usr/local/searx/searx-src
INFO:  status:  python-installed 
WARN:  instance's git URL: 'https://github.com/searxng/searxng' differs from local clone's remote URL: 
WARN:  instance git branch: master differs from local clone's branch: return42-searxng-brand
```

So everything seems to work.

**Review by dalf — APPROVED** [review]

**Comment by return42** [comment]
> `sudo -H ./utils/searx.sh update searx`

This just updates the sources from remote repository .. in db6a4d13 I implemented a `reinstall all` for the three scripts and added a message to `install check` 

- https://github.com/searxng/searxng/commit/db6a4d13e7ebe08a5df4fe6f99b0ef87aac94cc8#diff-b62e8274fb7a15e2a2775685b1d07dca116b9e736f9ba106ec7ba7edcc9b432eR288
- https://github.com/searxng/searxng/commit/db6a4d13e7ebe08a5df4fe6f99b0ef87aac94cc8#diff-c20cd7d8c5e019232e023108dbbfe9efe70417ddf4afa4ce9462e2ced0e3ec99R302
- https://github.com/searxng/searxng/pull/446/commits/db6a4d13e7ebe08a5df4fe6f99b0ef87aac94cc8#diff-ffd563c55bf191e4f0f3bdc162add389733738c2e88c5a3e9c22d54585f7be69R401

**Pull request merged**
