### PR TITLE
[fix] simple theme: hide the image if img load fails

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

~[fix] simple theme: show `img_load_error.svg` if img load fails~

[fix] simple theme: hide the image if img load fails

Add event listener to query selector::

    '#urls img.image'

see https://github.com/searxng/searxng/pull/610#issuecomment-997640132

### CODE REVIEW

**Comment by dalf** [comment]
Would it better to just hide the image?

**Comment by return42** [comment]
> Would it better to just hide the image?

I don't know what is better? ... since there is an image URL, I think there should be _placeholder_ images, but this is my very personal view.

BTW: the screenshot from above is not representative, normally you will see very rare the placeholder image.  The screenshots shows, that the bing-news engine has some issues .. we fixed in https://github.com/searxng/searxng/pull/609

**Comment by dalf** [comment]
> I don't know what is better? 

From the user point of view, I think it is better to hide the image: `img_load_error.svg` is helplful in the image category because it still allows to select the image. IMO, in the news category, the fact there is a missing image won't help to choose the links.

From a developer point of view, the place holder is signal that may be the engine needs to be updated (at least give a look). The browser console should show the same information too, but it requires some additional steps.

**Comment by return42** [comment]
>  but it requires some additional steps.

what do you expect from this PR .. should I disable the image if it can't be loaded .. does [Cumulative Layout Shift (CLS)](https://web.dev/cls/) need any attention here?

**Comment by return42** [comment]
ping @dalf

**Comment by dalf** [comment]
> what do you expect from this PR

Hide the images that can't be loaded.

> does Cumulative Layout Shift (CLS) need any attention here?

as you said, this doesn't happen often.

**Comment by return42** [comment]
> Hide the images that can't be loaded.

OK .. done!

**Comment by dalf** [comment]
Thank you

**Pull request merged**
