### PR TITLE
 [fix] keyboard navigation / simple theme (UI)  Fix 2751 & 2788

### LINKED ISSUE #2751: Arrow-Keys (and vim hotkeys) do not work in mixed result lists
In a mixed result list / by example:

    !goi !go !scc hello

the results are grouped ..

image

The `current.nextElementSibling` and `current.previousElementSibling` from ..

https://github.com/searxng/searxng/blob/f182abd6f8f1eac20d19c3e4b4c9800115f2a705/searx/static/themes/simple/src/js/main/keyboard.js#L211-L221

can only jump from one `<article>` to the next `<article>` within a group.

### LINKED ISSUE #2788: Problems about Keyboard Navigation
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
since #2724 .

**What happened?**
When using arrowkey-navigation on first/last result, it will jump to bottom/top  (that is, loop select).
I think it's not good for the UX, but seems you write a special code that cause this "bug".
https://github.com/searxng/searxng/blob/ec540a967a66156baa06797183cc64c4a3e345be/searx/static/themes/simple/src/js/main/keyboard.js#L237-L239

i think it shouldn't act like that, because users will be confused by this sudden jump.

**How To Reproduce**

- Search anything
- focus on the first result
- press `Arrow-Left`
and you will see the page has scrolled to bottom (the last result).

**Expected behavior**

do nothing

### PR DESCRIPTION
**Pull request by BernieHuang2008**
## What does this PR do?
fixed both #2751 and #2788 at the same time .

By finding the next result manually insdead of using `.nextElementSibling`.

## Why is this change important?

fixed bugs and improve UX

## How to test this PR locally?

search the keyword below and try to navigate between groups.

## Related issues
Closes #2751 
Closes #2788

### CODE REVIEW

**Comment by return42** [comment]
Wow, very cool .. I squashed your third commit into you first commit and modified the commit message .. hope thats OK for you ..

One point I have, I think the previous-/next-ElementSibling is superfluous here and the if-condition can be remove .. what to you think about this patch of your code? -->

```diff
diff --git a/searx/static/themes/simple/src/js/main/keyboard.js b/searx/static/themes/simple/src/js/main/keyboard.js
index ae324aadd..5c02acbfd 100644
--- a/searx/static/themes/simple/src/js/main/keyboard.js
+++ b/searx/static/themes/simple/src/js/main/keyboard.js
@@ -234,16 +234,10 @@ searxng.ready(function () {
           }
           break;
         case 'down':
-          next = current.nextElementSibling;
-          if (next === null) {
-            next = results[results.indexOf(current) + 1];
-          }
+          next = results[results.indexOf(current) + 1] || current;
           break;
         case 'up':
-          next = current.previousElementSibling;
-          if (next === null) {
-            next = results[results.indexOf(current) - 1];
-          }
+          next = results[results.indexOf(current) - 1] || current;
           break;
         case 'bottom':
           next = results[results.length - 1];
```

**Comment by BernieHuang2008** [comment]
can't agree with you more ~

**Comment by return42** [comment]
> can't agree with you more ~

:) .. I squashed my patch from above into your commit ([see diff](https://github.com/searxng/searxng/compare/ff369b328b67564403bee25649ba1f9e11a5bb73..315afe509b512b1287cf77087e8d115c9751e83c)) and rebuild the static files ..

Before we merge .. can you please check if my modification do work as expected (in all edge cases) / thanks!

**Comment by BernieHuang2008** [comment]
tested, everything right.

**Comment by return42** [comment]
> tested, everything right.

OK / thanks! .. I'm going to merge .. I want to have this merged, before we going to start the preferences --> https://github.com/searxng/searxng/issues/2788#issuecomment-1722206395

**Pull request merged**
