### PR TITLE
searxng.org: update setup.py & settings.yml

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

* reference `docs.searxng.org` instead of `searxng.github.io/searxng`.
* setup.py: update `author` and `author_email`.

## Why is this change important?

branding

### CODE REVIEW

**Review by mrpaulblack — APPROVED** [review]
LGTM

[EDIT] I think it would be good to drop the `.html` end in the paths tbh

**Comment by not-my-profile** [comment]
Related note: As long as there isn't anything on https://searxng.org/ it should probably redirect to https://docs.searxng.org/.

**Comment by mrpaulblack** [comment]
@not-my-profile I can do a redirect from http://searxng.org to https://docs.searxng.org with godaddy, but its going to be from http://searxng.org; If we want from https://searxng.org we would need to do this with github pages to get a cert or if one of us setups certs and the redirect on their VPS...

**Comment by not-my-profile** [comment]
Yeah I think setting that up on a VPS would probably be the best option since then we can do a proper 302 HTTP redirect (which afaik isn't possible with GitHub pages).

**Comment by return42** [comment]
ATM we deploy on gh-pages by this CI:

https://github.com/searxng/searxng/blob/b630c5d7bc0bf5a4281ad402bb32adc7f6ab257f/.github/workflows/integration.yml#L82-L91

how do we deploy on searxng.org?

**Comment by mrpaulblack** [comment]
We need another repo in the org named `searxng.github.io`; We can deploy from there to `searxng.org`

See: https://github.com/encode/encode.github.io/blob/master/_config.yml

[EDIT] And I think we can use CNAME files in the repo/branches to declare docs and landing page on github pages AFAIK

**Comment by dalf** [comment]
> how do we deploy on searxng.org?

We need to create a project named `searxng.github.io`:
* the master branch is the content of the `https://searxng.github.io`.
* `https://searxng.org` is already configured to display the content of `https://searxng.github.io`

See:
* for example: https://github.com/encode/encode.github.io
* documentation: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by return42** [comment]
And how is it updated/deployed today? .. by example, today I have merge https://github.com/searxng/searxng/pull/666 and now it is deployed at https://docs.searxng.org/dev/searxng_extra/standalone_searx.py.html

**Comment by dalf** [comment]
> And how is it updated/deployed today?

There is a DNS record: 
* `docs.searxng.org.       3588    IN      CNAME   searxng.github.io.`
* `searxng.org` is configured as a custom domain for the GH pages of the searxng/searxng project ( https://github.com/searxng/searxng/settings/pages )

> Yeah I think setting that up on a VPS would probably be the best option since then we can do a proper 302 HTTP redirect (which afaik isn't possible with GitHub pages).

searx.space is hosted in a Hetzner VPS. There is a room to store the content of searxng.org. Bonus: we can provide a .onion URL. But, as a first step I thought GitHub was enough.

**Comment by not-my-profile** [comment]
>But, as a first step I thought GitHub was enough.

My point was that if we use `searxng.org` for branding, then it should actually redirect somewhere instead of returning a 404. Ideally the redirect should happen via a 302 status code.

**Comment by mrpaulblack** [comment]
Ok redirects that point from `www.searxng.org` and `searxng.org` to `docs.searxng.org` are in place now; see: https://github.com/searxng/searxng.github.io (its an HTML redirect)...

**Review by return42 — APPROVED** [review]
LGTM .. thanks :+1:

I pushed d7b43064 .. it is just a nit .. if you want, I can merge d7b43064 with 76cbfbbd

**Pull request merged**
