### PR TITLE
[feat] anna's archive engine

### PR DESCRIPTION
**Pull request by paolobasso99**
## What does this PR do?

Add an engine for Anna's archive

## Why is this change important?

Anna's archive is an aggregator of library genesis, sci-hub and z-library backups. It claims to be "The world’s largest open-source open-data library.".

## How to test this PR locally?

Enable the engine and test a query

### CODE REVIEW

**Comment by return42** [comment]
@paolobasso99 thanks a lot for this PR .. and the other you have placed .. sadly non of the PRs has passed the CI ...

image

image

Most often the reported issues can be easily fixed, I recommend to to follow our [Development Quickstart](https://docs.searxng.org/dev/quickstart.html) .. the guide is very compact and can be read in 2min.

Further please do not change code, that is not needed to touch by this PR.   I think it is OK to touch some code around the PR for a clean up .. but not when it is only about stylish questions like changing from a single quote to a double quote.

And at least, squash the commits by topics / related:

- [How to contribute](https://docs.searxng.org/dev/contribution_guide.html#code)
- [Structural split of changes](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

----

Please do not take the criticism personally, we are very happy about your contributions and this project lives from such contributions :+1:

But to make the development process efficient and to ensure code quality we all have to follow minimal rules.  Thanks again for your cooperation and understanding

**Comment by paolobasso99** [comment]
Thanks for the feedback, I'll will make sure to fix the issues.

**Comment by return42** [comment]
@paolobasso99 one thing I forgot to say: If you have problems with [git rebase (squash)](https://driggl.com/blog/a/how-squashing-commits-can-improve-your-git-workflow) I can do it while in review of a PR (then it will be the last step in the review / just before a PR is merged).. just leave a comment that it is OK for you when I rebase your branch of a PR.

**Comment by paolobasso99** [comment]
It is OK for me when you rebase.

**Comment by return42** [comment]
@paolobasso99 I placed three commits on top of your branch / can you please review & test .. thanks!

In the first commit I added a function to fetch the arguments of the search `<form>` from Anan's search page.

In the second commit I added these arguments to the configuration (how it works is described in the doc-string of the python module).

In the third commit I fixed the result list / the implementation now grep results from '.js-scroll-hidden' elements --> its very strange how Ana's WEB site is rendered .. except the first item all other items are in SGML comments and activated by some JS / I described it in a comment.

----

Anna's Archive is in beta state .. I expect many more changes in the near future and we will have to make adjustments every now and then. Nevertheless, it is a very valuable source ... thank you for making it available to us :rocket:

**Comment by paolobasso99** [comment]
Definitely some nice improvements from your commits, thanks!

I pushed 2 commits:
1. The first just fixes some typos in the comments
2. The second fixes a bug, when lang=None the url parameter should be empty not 'None'

**Comment by return42** [comment]
> I pushed 2 commits:

@paolobasso99: thanks a lot .. I squashed the two commits into the commits from mine (because it belongs together thematically).

Further I squashed the commits 99eaf38aa and 0092c36f8 into your first commits (because it belongs together thematically)

If the commit history we have now is OK for you I will merge this PR.

-----

Don't worry about the failed build of the docs .. its github's CI that runs into a timeout .. this happens sometimes / why, I don't know either .. I started the job again, mostly it runs through then :-)

**Comment by paolobasso99** [comment]
History is ok, thanks.

**Pull request merged**
