### PR TITLE
[l10n] adding new language Tatar (tt)

### LINKED ISSUE #4098: Request for adding New (for SearXNG) Language - Tatar (tt).
Hello!

It seems like that "Translators needed" can't be a good Place for requesting Languages, because Requests are w/o any Answer, which makes Me think it will be ignored.
So [after a while](https://github.com/searxng/searxng/issues/540#issuecomment-2264083028) I've decided to make separate Issue Request for My Language:

> Hello!
> I am Amirkhandrend-Nicest-XII in CodeBerg Project that sent Tatar Language Request.
> I was impressed by SearX and liked searching via that Engine, but unfortunately for Me I found that SearX's GitHub Repo was archived so I can't request Tatar for SearX...
> But I found SearXNG! I even ran own (for Myself) version in Docker... and for now I really want to translate SearXNG into Tatar Language!
> 
> I hope that this Request will be accepted.
> 
> Just some clarification for Tatar Language and why this Language:
> Tatar Language is The Biggest Minority (yep, that's probably sounds strange) Language in Russia. [Politics Expunged]. We are trying to translate as much as possible projects and doing it with best Quality (if that is possible; Translation String System can differ from project to project) to digitalize our Language.

For this Time I actually didn't abandon using SearXNG, so I know some Context for some Strings without need of Asking someone who knows.

### PR DESCRIPTION
**Pull request by return42**
Cammands used to add Tatar (tt):

    $ ./manage pyenv.cmd bash
    $ pybabel init -i searx/translations/messages.pot -d searx/translations -l tt
    creating catalog searx/translations/tt/LC_MESSAGES/messages.po based on searx/translations/messages.pot

    $ ./searxng_extra/update/update_locales.py

- Closes: https://github.com/searxng/searxng/issues/4098

### CODE REVIEW

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
How long to wait Tatar for being added in [Codeberg Translate](https://translate.codeberg.org/projects/searxng/searxng/) Project?

Also I've noticed that "Татар (Tatar)" used instead of "Татар**ча** (Tatar)". Yes, I know that in Unicode CLDR Standart this appears too, but I think (and also I've asked this Question to more Knowing Native, and he also stated "Татарча" being more Natural as Language's Self-Name) that My Option sounds more Natural for My Language's Self-Name as Language Name, "Татар" is more like a Standart Adjective like "Tatar Culture".

**Comment by return42** [comment]
I'm sorry but this is babel (CLDR) .. we had a similar discussion a while ago, please read my explanations from back then:

- https://github.com/searxng/searxng/pull/1801#issuecomment-1256880915

**Comment by return42** [comment]
> How long to wait Tatar for being added in [Codeberg Translate](https://translate.codeberg.org/projects/searxng/searxng/) Project?

We have a problem with the syncing / see here https://github.com/searxng/searxng/issues/4098#issuecomment-2541965951

**Comment by return42** [comment]
@Amirhan-Taipovjan-Greatest-I you can start with translation, Tatar (`tt`) is now available in weblate   --> https://translate.codeberg.org/projects/searxng/searxng/tt/

**Pull request merged**
