### PR TITLE
Reduce Docker image size

### PR DESCRIPTION
**Pull request by ngosang**
## What does this PR do?

* Copy only source code and Docker entrypoint
* Avoid updating packages. The base image is updated frecuently

## Why is this change important?

* Docker image size reduced by 3 MB (195 MB -> 192 MB uncompressed)

## How to test this PR locally?

Deploy and check everything is working as before.

### CODE REVIEW

**Comment by ngosang** [comment]
@return42 how long it takes the review process? I'm a bit concerned about the project health.

**Comment by return42** [comment]
> I'm a bit concerned about the project health.

Sorry for the delay .. I'm not the docker expert, so I requested ([here](https://github.com/searxng/searxng/pull/1896#event-7689327681)) a review of this PR from our docker experts @dalf and @mrpaulblack.

**Comment by ngosang** [comment]
@return42 I want to open more PRs:
* Update Alpine 3.17 => Fix this issue https://github.com/searxng/searxng-docker/issues/31
* Update Python 3.11 and include it in CI/CD => Performance gains https://www.phoronix.com/review/python-311-benchmarks/4

I'm an expert in Docker and I will be reachable for any issue caused by my PRs, but I won't open more PRs until I see this merged, or at least some activity.

**Comment by return42** [comment]
@dalf & @mrpaulblack you are the maintainer of the docker part, can you please have a look at this PR .. @ngosang is still waiting since over a month without getting any feedback.

**Comment by dalf** [comment]
Quick answer:
Related to https://gitlab.alpinelinux.org/alpine/aports/-/issues/11906#note_232487
I was hoping the issue to be fixed in Alpine 3.17.
Some benchmarks are needed on SBC like Raspberry Pi.

**Review by unixfox — APPROVED** [review]

**Review by unixfox — CHANGES_REQUESTED** [review]
No obvious issues. Good idea to chown the searx directory.
Can you prove that removing the compiled sources doesn't affect the startup time by too much?

**Comment by ngosang** [comment]
@unixfox You are right. I just did some tests and these are the results. This is the time since I execute "docker run" in my machine until uwsgi initialization ends. My computer is really fast.
* Docker image with compiled sources => 2.61 seconds
* Docker image without compiled sources => 6.31 seconds

I reverted the changes related to compiled files in this PR. The changes in size are just 3 MB but the image will build a bit faster too.

**Review by unixfox — APPROVED** [review]
Thank you for the test @ngosang 
@return42 good to merge

**Pull request merged**
