### PR TITLE
[mod] lint github YAML config files

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

`yamllint` github config files (YAML)

## Why is this change important?

find issues before merge upstream into `master` branch

## How to test this PR locally?

    make test.yamllint

## Related issues

- https://github.com/searxng/searxng/pull/3313

### CODE REVIEW

**Comment by dalf** [comment]
meh, I understand but the workflows are painful to test / develop. I often end up with `git add .; git commit --ammend; git push --force` until it works.
If the process crash because there is missing space, it will additional stress for no additional gain.
YMMV.

**Comment by return42** [comment]
> meh, I understand but the workflows are painful to test / develop. I often end up with `git add .; git commit --ammend; git push --force` until it works. 

Yeah, but you are talking about challenges in the development cycles when setting up a workflow, this PR is made to reduce avoidable errors / improve quality of YAML files.

> If the process crash because there is missing space, it will additional stress 

This yamllint test can be run before you create the commit and is started by the CI when we send a PR.

> for no additional gain. YMMV.

The intention (gain) is to lint yaml files before merge commits into master (YAML files will be linted in the CI of a PR).

By example:

In https://github.com/searxng/searxng/pull/3313 I merged three YAML issues into the master tree --> https://github.com/searxng/searxng/actions/runs/8214791833/workflow#L117

To fix I needed two commits a48da9b2 and 691390b443 .. with the addition from this PR, YAML issues in the config files will be reported in the CI tests of a PR .. I would never had merged this yaml errors.

**Comment by dalf** [comment]
> To fix I needed two commits https://github.com/searxng/searxng/commit/a48da9b28aa9eb592f0479492f7d04b2c68cc33c and https://github.com/searxng/searxng/commit/691390b443c96ce9aa26c2fea487bbcf397147fc .. with the addition from this PR, YAML issues in the config files will be reported in the CI tests of a PR .. I would never had merged this yaml errors.

I see these type of errors in my editor as I type.

> This yamllint test can be run before you create the commit and is started by the CI when we send a PR.

It is going to do additional tests before the commit --> additional stress for nothing as long the editor make sure to show invalid YAML instantaneously.

**Comment by dalf** [comment]
About instant check, what is the purpose of these lines ?

https://github.com/searxng/searxng/blob/691390b443c96ce9aa26c2fea487bbcf397147fc/.dir-locals.el#L83-L90

Does it ask flycheck to run yaml-lint while you are editing?

**Comment by return42** [comment]
> I see these type of errors in my editor as I type.

I see pyright and pylint issues in my editor but that is not a reason to remove these tests from the CI

>  additional stress for nothing as long the editor make sure to show invalid YAML instantaneously.

Sadly yaml-lint does not work yet well in my editor (emacs).

> Does it ask flycheck to run yaml-lint while you are editing?

Yes, the intention is to set up the flycheck variables needed to start a yamllint in the emacs editor from the local python installation we have in `local/py3/`  (its like running the yammlint within a `local/py3/bin/activate` environment).

Sadly this setup does not work yet in my emacs .. :shrug: 

> It is going to do additional tests before the commit --> additional stress 

I don't have much experience with developing workflows, this PR would have helped me.

But if you think it unnecessarily complicates the development processes, then we can close the PR ... I will follow your lead, you have more experience than I do ..

**Comment by return42** [comment]
>> To fix I needed two commits [a48da9b](https://github.com/searxng/searxng/commit/a48da9b28aa9eb592f0479492f7d04b2c68cc33c) and [691390b](https://github.com/searxng/searxng/commit/691390b443c96ce9aa26c2fea487bbcf397147fc) .. with the addition from this PR, YAML issues in the config files will be reported in the CI tests of a PR .. I would never had merged this yaml errors.
> 
> I see these type of errors in my editor as I type.

I want to merge this PR: we have these issues in the YAML files and they are reported in the CI:

image

>> It is going to do additional tests before the commit --> additional stress

As shown in the screenshot above, these errors are already logged in the IDE and should therefore be easy to avoid.

I understand that this is more work, but I also see the mistakes we make when we don't do this work: As with any change to any other part of the source code where we run tests in the CI to prevent the merge before fixing obvious bugs, we should do the same with the YAML files.  The fact that we have had unclean YAML files in our source code for years shows, in my opinion, how necessary these tests are.

**Review by Bnyro — APPROVED** [review]
I agree with the opinion of Markus, these lints help us to keep the code and config file quality consistent, and I don't see what the source of potential issues should be.

The linter doesn't change the yaml files, it just guarantees everything is indented properly to avoid and early-catch potential issues.

**Pull request merged**
