### PR TITLE
Add wttr.in engine

### PR DESCRIPTION
**Pull request by liimee**
## What does this PR do?

Adds the wttr.in engine

## Why is this change important?

We have no weather engines yet on searxng, so I think this would be cool

## How to test this PR locally?

search `!wttr San Francisco`

## Author's checklist

~~This engine has some hardcoded English text, and I'm not sure how to make it translatable, sorry. We may be able to use their [one-line output](https://github.com/chubin/wttr.in#one-line-output) or [image/plain text/html output](https://github.com/chubin/wttr.in#supported-output-formats-and-views)~~ I'll try to use gettext

## Related issues

#1206 may be related

Thanks :)

### CODE REVIEW

**Comment by return42** [comment]
Hi @liimee its a pleasure to see PR's from you :) 

I recognize continues pushes from you .. if you think PR is ready to review, sent me a note / thanks.

**Comment by liimee** [comment]
hi, sorry about that — it is now ready for review

**Comment by liimee** [comment]
@return42 hi, sorry about that — it is now ready for review

**Comment by julianfairfax** [comment]
#1206 is indeed related. This would be nice to see!

**Comment by liimee** [comment]
@return42 hello, just reminding you to review this PR if you are not busy, thanks

**Comment by return42** [comment]
Hi @liimee sorry for the delay .. its on my ToDo list .. I would prefer it if we can merge https://github.com/searxng/searxng/pull/1412 first.

My plan is to ..

- https://github.com/searxng/searxng/issues/1352

for this we need to:

- https://github.com/searxng/searxng/pull/1412

first.  If this is done I can add the long needed list-type and a table-type (needed in this PR) to the infobox.

About PR-1412 @dalf says [After a long thinking, I'm "meh" about this PR](https://github.com/searxng/searxng/pull/1412#issuecomment-1195305052), then we implemented two alternatives to PR-1412 but both did failed .. 

If we don't make progress with the PR-1412 for longer, then I can bring this PR forward ... but that would just mean more work for me ..  thats why I still wait with this PR .. I hope that is also okay for you.

**Review by dalf — APPROVED** [review]

**Pull request merged**
