### PR TITLE
[mod] Shuffle httpx's default ciphers of a SSL context randomly.

### LINKED ISSUE #2246: Bug: duckduckgo engine
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.3.2+abd2d860

**How did you install SearXNG?**

searxng-docker

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 10
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:114`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

### PR DESCRIPTION
**Pull request by return42**
From the analyse of @9Ninety [1] we know that DDG (and may be other engines / I have startpage in mind) does some kind of TLS fingerprint to block bots.

This patch shuffles the default ciphers from httpx to avoid a cipher profile that is known to httpx (and blocked by DDG).

[1] https://github.com/searxng/searxng/issues/2246#issuecomment-1467895556

----

From [What Is TLS Fingerprint and How to Bypass It](https://www.zenrows.com/blog/what-is-tls-fingerprint#how-to-bypass-tls-fingerprinting)

> When implementing TLS fingerprinting, servers can't operate based on a
> locked-in whitelist database of fingerprints.  New fingerprints appear
> when web clients or TLS libraries release new versions. So, they have to
> live off a blocklist database instead.
> ...
> It's safe to leave the first three as is but shuffle the remaining ciphers
> and you can bypass the TLS fingerprint check.

Closes: https://github.com/searxng/searxng/issues/2246

### CODE REVIEW

**Comment by return42** [comment]
FYI: I applied this patch on my instance https://darmarit.org/searx/ .. looks good so far.

Comments & testers are welcome :+1:

**Comment by chenghui-lee** [comment]
Can confirm this is working

**Comment by nicfab** [comment]
Unfortunately, it doesn't work for me (I changed only the content of `client.py` as I read it here).  I continue receiving the DDG error.

**Comment by return42** [comment]
> I changed only the content of `client.py` as I read it here

@nicfab did you double check that the call of `shuffle_ciphers(..)` is in your patch?

grafik

**Comment by nicfab** [comment]
> @nicfab did you double check that the call of `shuffle_ciphers(..)` is in your patch?

Yes, of course. 
I modified the file as I read it [here](https://github.com/searxng/searxng/pull/2266/files).

**Comment by return42** [comment]
And in your [`searx/engines/duckduckgo.py`](https://github.com/searxng/searxng/blob/master/searx/engines/duckduckgo.py) there is no leftover from a previous attempt?

I have your comment in mind --> https://github.com/searxng/searxng/issues/2246#issuecomment-1466410521

**Comment by nicfab** [comment]
> And in your [`searx/engines/duckduckgo.py`](https://github.com/searxng/searxng/blob/master/searx/engines/duckduckgo.py) there is no leftover from a previous attempt?
> 
> I have your comment in mind --> [#2246 (comment)](https://github.com/searxng/searxng/issues/2246#issuecomment-1466410521)

You are right.
I didn't change the file `searxng/searxng/blob/master/searx/engines/duckduckgo.py`.
I will modify them and come back here soon.

**Comment by nicfab** [comment]
> And in your [`searx/engines/duckduckgo.py`](https://github.com/searxng/searxng/blob/master/searx/engines/duckduckgo.py) there is no leftover from a previous attempt?
> 
> I have your comment in mind --> [#2246 (comment)](https://github.com/searxng/searxng/issues/2246#issuecomment-1466410521)

I changed both `client.py` and `duckduckgo.py`, but unfortunately, the DDG error remains.
To be sure I did the changes correctly, I pasted below the content of the modified files:
**client.py**
```
# SPDX-License-Identifier: AGPL-3.0-or-later
# lint: pylint
# pylint: disable=missing-module-docstring, global-statement

import asyncio
import logging
import random
from ssl import SSLContext
import threading
from typing import Any, Dict

import httpx
from httpx_socks import AsyncProxyTransport
from python_socks import parse_proxy_url, ProxyConnectionError, ProxyTimeoutError, ProxyError

from searx import logger

# Optional uvloop (support Python 3.6)
try:
    import uvloop
except ImportError:
    pass
else:
    uvloop.install()


logger = logger.getChild('searx.network.client')
LOOP = None
SSLCONTEXTS: Dict[Any, SSLContext] = {}

def shuffle_ciphers(ssl_context):
     """Shuffle httpx's default ciphers of a SSL context randomly.

     From `What Is TLS Fingerprint and How to Bypass It`_

     > When implementing TLS fingerprinting, servers can't operate based on a
     > locked-in whitelist database of fingerprints.  New fingerprints appear
     > when web clients or TLS libraries release new versions. So, they have to
     > live off a blocklist database instead.
     > ...
     > It's safe to leave the first three as is but shuffle the remaining ciphers
     > and you can bypass the TLS fingerprint check.

     .. _What Is TLS Fingerprint and How to Bypass It:
        https://www.zenrows.com/blog/what-is-tls-fingerprint#how-to-bypass-tls-fingerprinting

     """
     c_list = httpx._config.DEFAULT_CIPHERS.split(':')  # pylint: disable=protected-access
     sc_list, c_list = c_list[:3], c_list[3:]
     random.shuffle(c_list)
     ssl_context.set_ciphers(":".join(sc_list + c_list))

def get_sslcontexts(proxy_url=None, cert=None, verify=True, trust_env=True, http2=False):
    key = (proxy_url, cert, verify, trust_env, http2)
    if key not in SSLCONTEXTS:
        SSLCONTEXTS[key] = httpx.create_ssl_context(cert, verify, trust_env, http2)
    shuffle_ciphers(SSLCONTEXTS[key])
    return SSLCONTEXTS[key]


class AsyncHTTPTransportNoHttp(httpx.AsyncHTTPTransport):
    """Block HTTP request"""

    async def handle_async_request(self, request):
        raise httpx.UnsupportedProtocol('HTTP protocol is disabled')


class AsyncProxyTransportFixed(AsyncProxyTransport):
    """Fix httpx_socks.AsyncProxyTransport

    Map python_socks exceptions to httpx.ProxyError exceptions
    """

    async def handle_async_request(self, request):
        try:
            return await super().handle_async_request(request)
        except ProxyConnectionError as e:
            raise httpx.ProxyError("ProxyConnectionError: " + e.strerror, request=request) from e
        except ProxyTimeoutError as e:
            raise httpx.ProxyError("ProxyTimeoutError: " + e.args[0], request=request) from e
        except ProxyError as e:
            raise httpx.ProxyError("ProxyError: " + e.args[0], request=request) from e


def get_transport_for_socks_proxy(verify, http2, local_address, proxy_url, limit, retries):
    # support socks5h (requests compatibility):
    # https://requests.readthedocs.io/en/master/user/advanced/#socks
    # socks5://   hostname is resolved on client side
    # socks5h://  hostname is resolved on proxy side
    rdns = False
    socks5h = 'socks5h://'
    if proxy_url.startswith(socks5h):
        proxy_url = 'socks5://' + proxy_url[len(socks5h) :]
        rdns = True

    proxy_type, proxy_host, proxy_port, proxy_username, proxy_password = parse_proxy_url(proxy_url)
    verify = get_sslcontexts(proxy_url, None, True, False, http2) if verify is True else verify
    return AsyncProxyTransportFixed(
        proxy_type=proxy_type,
        proxy_host=proxy_host,
        proxy_port=proxy_port,
        username=proxy_username,
        password=proxy_password,
        rdns=rdns,
        loop=get_loop(),
        verify=verify,
        http2=http2,
        local_address=local_address,
        limits=limit,
        retries=retries,
        **TRANSPORT_KWARGS,
    )


def get_transport(verify, http2, local_address, proxy_url, limit, retries):
    verify = get_sslcontexts(None, None, True, False, http2) if verify is True else verify
    return httpx.AsyncHTTPTransport(
        # pylint: disable=protected-access
        verify=verify,
        http2=http2,
        limits=limit,
        proxy=httpx._config.Proxy(proxy_url) if proxy_url else None,
        local_address=local_address,
        retries=retries,
        **TRANSPORT_KWARGS,
    )


def new_client(
    # pylint: disable=too-many-arguments
    enable_http,
    verify,
    enable_http2,
    max_connections,
    max_keepalive_connections,
    keepalive_expiry,
    proxies,
    local_address,
    retries,
    max_redirects,
    hook_log_response,
):
    limit = httpx.Limits(
        max_connections=max_connections,
        max_keepalive_connections=max_keepalive_connections,
        keepalive_expiry=keepalive_expiry,
    )
    # See https://www.python-httpx.org/advanced/#routing
    mounts = {}
    for pattern, proxy_url in proxies.items():
        if not enable_http and pattern.startswith('http://'):
            continue
        if proxy_url.startswith('socks4://') or proxy_url.startswith('socks5://') or proxy_url.startswith('socks5h://'):
            mounts[pattern] = get_transport_for_socks_proxy(
                verify, enable_http2, local_address, proxy_url, limit, retries
            )
        else:
            mounts[pattern] = get_transport(verify, enable_http2, local_address, proxy_url, limit, retries)

    if not enable_http:
        mounts['http://'] = AsyncHTTPTransportNoHttp()

    transport = get_transport(verify, enable_http2, local_address, None, limit, retries)

    event_hooks = None
    if hook_log_response:
        event_hooks = {'response': [hook_log_response]}

    return httpx.AsyncClient(
        transport=transport,
        mounts=mounts,
        max_redirects=max_redirects,
        event_hooks=event_hooks,
    )


def get_loop():
    return LOOP


def init():
    # log
    for logger_name in ('hpack.hpack', 'hpack.table', 'httpx._client'):
        logging.getLogger(logger_name).setLevel(logging.WARNING)

    # loop
    def loop_thread():
        global LOOP
        LOOP = asyncio.new_event_loop()
        LOOP.run_forever()

    thread = threading.Thread(
        target=loop_thread,
        name='asyncio_loop',
        daemon=True,
    )
    thread.start()


init()
```
**duckduckgo.py**
```
# SPDX-License-Identifier: AGPL-3.0-or-later
# lint: pylint
"""DuckDuckGo Lite
"""

from json import loads

from lxml.html import fromstring

from searx.utils import (
    dict_subset,
    eval_xpath,
    eval_xpath_getindex,
    extract_text,
    match_language,
)
from searx.network import get

# about
about = {
    "website": 'https://lite.duckduckgo.com/lite',
    "wikidata_id": 'Q12805',
    "official_api_documentation": 'https://duckduckgo.com/api',
    "use_official_api": False,
    "require_api_key": False,
    "results": 'HTML',
}

# engine dependent config
categories = ['general', 'web']
paging = True
supported_languages_url = 'https://duckduckgo.com/util/u588.js'
time_range_support = True
send_accept_language_header = True

language_aliases = {
    'ar-SA': 'ar-XA',
    'es-419': 'es-XL',
    'ja': 'jp-JP',
    'ko': 'kr-KR',
    'sl-SI': 'sl-SL',
    'zh-TW': 'tzh-TW',
    'zh-HK': 'tzh-HK',
}

time_range_dict = {'day': 'd', 'week': 'w', 'month': 'm', 'year': 'y'}

# search-url
url = 'https://lite.duckduckgo.com/lite'
url_ping = 'https://duckduckgo.com/t/sl_l'

# match query's language to a region code that duckduckgo will accept
def get_region_code(lang, lang_list=None):
    if lang == 'all':
        return None

    lang_code = match_language(lang, lang_list or [], language_aliases, 'wt-WT')
    lang_parts = lang_code.split('-')

    # country code goes first
    return lang_parts[1].lower() + '-' + lang_parts[0].lower()


def request(query, params):

    params['url'] = url
    params['method'] = 'POST'

    params['data']['q'] = query

    # The API is not documented, so we do some reverse engineering and emulate
    # what https://lite.duckduckgo.com/lite/ does when you press "next Page"
    # link again and again ..

    params['headers']['Content-Type'] = 'application/x-www-form-urlencoded'
    params['headers']['User-Agent'] = 'curl/7.81.0'

    # initial page does not have an offset
    if params['pageno'] == 2:
        # second page does have an offset of 30
        offset = (params['pageno'] - 1) * 30
        params['data']['s'] = offset
        params['data']['dc'] = offset + 1

    elif params['pageno'] > 2:
        # third and following pages do have an offset of 30 + n*50
        offset = 30 + (params['pageno'] - 2) * 50
        params['data']['s'] = offset
        params['data']['dc'] = offset + 1

    # initial page does not have additional data in the input form
    if params['pageno'] > 1:
        # request the second page (and more pages) needs 'o' and 'api' arguments
        params['data']['o'] = 'json'
        params['data']['api'] = 'd.js'

    # initial page does not have additional data in the input form
    if params['pageno'] > 2:
        # request the third page (and more pages) some more arguments
        params['data']['nextParams'] = ''
        params['data']['v'] = ''
        params['data']['vqd'] = ''

    region_code = get_region_code(params['language'], supported_languages)
    if region_code:
        params['data']['kl'] = region_code
        params['cookies']['kl'] = region_code

    params['data']['df'] = ''
    if params['time_range'] in time_range_dict:
        params['data']['df'] = time_range_dict[params['time_range']]
        params['cookies']['df'] = time_range_dict[params['time_range']]

    logger.debug("param data: %s", params['data'])
    logger.debug("param cookies: %s", params['cookies'])
    return params


# get response from search-request
def response(resp):

    headers_ping = dict_subset(resp.request.headers, ['User-Agent', 'Accept-Encoding', 'Accept', 'Cookie'])
    get(url_ping, headers=headers_ping)

    if resp.status_code == 303:
        return []

    results = []
    doc = fromstring(resp.text)

    result_table = eval_xpath(doc, '//html/body/form/div[@class="filters"]/table')
    if not len(result_table) >= 3:
        # no more results
        return []
    result_table = result_table[2]

    tr_rows = eval_xpath(result_table, './/tr')

    # In the last <tr> is the form of the 'previous/next page' links
    tr_rows = tr_rows[:-1]

    len_tr_rows = len(tr_rows)
    offset = 0

    while len_tr_rows >= offset + 4:

        # assemble table rows we need to scrap
        tr_title = tr_rows[offset]
        tr_content = tr_rows[offset + 1]
        offset += 4

        # ignore sponsored Adds <tr class="result-sponsored">
        if tr_content.get('class') == 'result-sponsored':
            continue

        a_tag = eval_xpath_getindex(tr_title, './/td//a[@class="result-link"]', 0, None)
        if a_tag is None:
            continue

        td_content = eval_xpath_getindex(tr_content, './/td[@class="result-snippet"]', 0, None)
        if td_content is None:
            continue

        results.append(
            {
                'title': a_tag.text_content(),
                'content': extract_text(td_content),
                'url': a_tag.get('href'),
            }
        )

    return results


# get supported languages from their site
def _fetch_supported_languages(resp):

    # response is a js file with regions as an embedded object
    response_page = resp.text
    response_page = response_page[response_page.find('regions:{') + 8 :]
    response_page = response_page[: response_page.find('}') + 1]

    regions_json = loads(response_page)
    supported_languages = map((lambda x: x[3:] + '-' + x[:2].upper()), regions_json.keys())

    return list(supported_languages)
```
Obviously, in `settings.yml` I set:
```
engines:
  - name: duckduckgo
    disabled: false

```

**Comment by return42** [comment]
> I changed both `client.py` and `duckduckgo.py` ...

may you misunderstood me, you have to rollback `duckduckgo.py` to current master --> https://github.com/searxng/searxng/blob/master/searx/engines/duckduckgo.py

By example I see this line in your `duckduckgo.py` from above:

        params['headers']['User-Agent'] = 'curl/7.81.0'

This line is not in current master and is one reason for the issue you observe.

**Comment by chenghui-lee** [comment]
Tested locally by applying the changes in this PR.
Looks fine.
image

Debug message:
image

**Comment by nicfab** [comment]
> may you misunderstood me, you have to rollback `duckduckgo.py` to current master --> https://github.com/searxng/searxng/blob/master/searx/engines/duckduckgo.py
> 
> By example I see this line in your `duckduckgo.py` from above:
> 
> ```
>     params['headers']['User-Agent'] = 'curl/7.81.0'
> ```
> 
> This line is not in current master and is one reason for the issue you observe.

I replaced `duckduckgo.py` with the master and it doesn't work for me.
I still receive the DDG error.
If I run `cat /var/log/syslog | grep searx` I see:

```
Mar 20 07:52:59 ip-172-31-21-198 systemd[1]: /lib/systemd/system/searxng-redis.service:19: Unknown key name 'ExecPaths' in section 'Service', ignoring.
Mar 20 07:53:00 ip-172-31-21-198 systemd[1]: /lib/systemd/system/searxng-redis.service:19: Unknown key name 'ExecPaths' in section 'Service', ignoring.
```
BtW, if I run `sudo -H ./utils/searxng.sh instance check` I see:

```
INFO:  wrapper:  utils/searxng.sh instance _call searxng.check

SearXNG checks
--------------
INFO:  [OK] (old) account 'searx' does not exists
INFO:  [OK] (old) account 'filtron' does not exists
INFO:  [OK] (old) account 'morty' does not exists
Traceback (most recent call last):
  File "/usr/local/searxng/searxng-src/utils/searxng_check.py", line 17, in <module>
    import searx
ModuleNotFoundError: No module named 'searx'
```
What is the latest error `ModuleNotFoundError: No module named 'searx'` and how can I solve it?

**Comment by nicfab** [comment]
> > I changed both `client.py` and `duckduckgo.py` ...
> 
> may you misunderstood me, you have to rollback `duckduckgo.py` to current master --> https://github.com/searxng/searxng/blob/master/searx/engines/duckduckgo.py
> 
> By example I see this line in your `duckduckgo.py` from above:
> 
> ```
>     params['headers']['User-Agent'] = 'curl/7.81.0'
> ```
> 
> This line is not in current master and is one reason for the issue you observe.

I checked the DDG error and the result is the following:

```
Exception | searx.exceptions.SearxEngineAccessDeniedException | Percentage | 100
-- | -- | -- | --
HTTP error 403
searx/search/processors/online.py:114
_send_http_request
response = req(params['url'], **request_args)
```
I don't if it is relevant here.

**Comment by 9Ninety** [comment]
Confirm it works on all of my instance.

@return42 By the way, your master branch break my instance "by default" 😮, it doesn't work with `default_lang: "all"` and throw following error:
```
Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/webapp.py", line 682, in search
searxng  |     search_query, raw_text_query, _, _ = get_search_query_from_webapp(request.preferences, request.form)
searxng  |   File "/usr/local/searxng/searx/webadapter.py", line 232, in get_search_query_from_webapp
searxng  |     query_lang = parse_lang(preferences, form, raw_text_query)
searxng  |   File "/usr/local/searxng/searx/webadapter.py", line 67, in parse_lang
searxng  |     raise SearxParameterException('language', query_lang)
searxng  | searx.exceptions.SearxParameterException: Invalid value "None" for parameter language
```

@nicfab Would you mind share your network setup? It looks like there are some timeout exception along with access denied in your [previous comment](https://github.com/searxng/searxng/issues/2246#issuecomment-1464847511), did you make it connect to search engine through Tor or commercial VPN? Where did you host your instance, home or VPS?

**Comment by nicfab** [comment]
> Confirm it works on all of my instance.
> 
> @return42 By the way, your master branch break my instance "by default" 😮, it doesn't work with `default_lang: "all"` and throw following error:
> 
> ```
> Traceback (most recent call last):
> searxng  |   File "/usr/local/searxng/searx/webapp.py", line 682, in search
> searxng  |     search_query, raw_text_query, _, _ = get_search_query_from_webapp(request.preferences, request.form)
> searxng  |   File "/usr/local/searxng/searx/webadapter.py", line 232, in get_search_query_from_webapp
> searxng  |     query_lang = parse_lang(preferences, form, raw_text_query)
> searxng  |   File "/usr/local/searxng/searx/webadapter.py", line 67, in parse_lang
> searxng  |     raise SearxParameterException('language', query_lang)
> searxng  | searx.exceptions.SearxParameterException: Invalid value "None" for parameter language
> ```
> 
> @nicfab Would you mind share your network setup? It looks like there are some timeout exception along with access denied in your [previous comment](https://github.com/searxng/searxng/issues/2246#issuecomment-1464847511), did you make it connect to search engine through Tor or commercial VPN? Where did you host your instance, home or VPS?

Thank you @9Ninety 
My SearXNG instance is on an AWS and is also reachable on TOR.
I installed SearXNG via scripts (no docker), and the reverse proxy is managed by NGINX.
What kind of information do you need and how can I retrieve them?

**Comment by 9Ninety** [comment]
@nicfab I mean have you setup proxy in searxng settings file to make it connect to DDG through Tor or VPN? 

I'm thinking about is this caused by the IP(range) you are using to connect to DDG has been flagged as high risk or proxy.

I couldn't reproduce it on my AWS instance, can you share what operating system you used on the instance and what availability region was used?

**Comment by nicfab** [comment]
> @nicfab I mean have you setup proxy in searxng settings file to make it connect to DDG through Tor or VPN?

No, as you can see from the `settings.yml` of which I paste part of its content (I obscured my email address and the secret code):

```
# SearXNG settings

use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG NicFab"
  contact_url: "mailto:<email>"
  privacypolicy_url: https://docs.searxng.org/own-instance.html#how-does-searxng-protect-privacy
  enable_metrics: true

search:
  safe_search: 2
  autocomplete: 'duckduckgo'
  formats:
    - html
    - json
    - rss
    - csv

server:
  base_url: http://searxng.nicfab.eu
  secret_key: "<secretkey>"
  limiter: true
  image_proxy: true

redis:
  url: unix:///usr/local/searxng-redis/run/redis.sock?db=0

ui:
  static_use_hash: true
  default_locale: ""
# preferences:
#   lock:
#     - autocomplete
#     - method

enabled_plugins:
  - 'Hash plugin'
  - 'Search on category select'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'
  - 'Tor check plugin'

  # - 'Hostname replace'  # see hostname_replace configuration below
  # - 'Infinite scroll'
  # - 'Open Access DOI rewrite'
  # - 'Vim-like hotkeys'

# plugins:
#   - only_show_green_results

# hostname_replace:
#
#   # twitter --> nitter
#   '(www\.)?twitter\.com$': 'nitter.net'

engines:
...

  - name: duckduckgo
    disabled: true

```
> 
> I'm thinking about is this caused by the IP(range) you are using to connect to DDG has been flagged as high risk or proxy.
> 
> I couldn't reproduce it on my AWS instance, can you share what operating system you used on the instance and what availability region was used?

Ubuntu 20.04.6 - AWS region: Europe (Milan) - eu-south1-1

**Comment by return42** [comment]
> @return42 By the way, your master branch break my instance "by default" open_mouth, it doesn't work with default_lang: "all" and throw following error:

Thanks for pointing out / fixed.

> Can confirm this is working
> Tested locally by applying the changes in this PR. Looks fine.
> Confirm it works on all of my instance.

I'm going to merge this PR.

@nicfab that the resists on your instance might be related to some other reasons, we can later discuss in another issue.

First I want that all SearXNG maintainers get this patch into their instances, then we can see on which instances the might issue resists.

**Comment by nicfab** [comment]
> > @return42 By the way, your master branch break my instance "by default" open_mouth, it doesn't work with default_lang: "all" and throw following error:
> 
> Thanks for pointing out / fixed.
> 
> > Can confirm this is working
> > Tested locally by applying the changes in this PR. Looks fine.
> > Confirm it works on all of my instance.
> 
> I'm going to merge this PR.
> 
> @nicfab that the resists on your instance might be related to some other reasons, we can later discuss in another issue.
> 
> First I want that all SearXNG maintainers get this patch into their instances, then we can see on which instances the might issue resists.

Thank you very much @return42 
I updated it just now, and I confirm that it works fine.
No DDG errors.

**Comment by unixfox** [comment]
This could also help in fixing this issue: https://github.com/searxng/searxng/issues/1966
I've already found out that when this error occurs, SearXNG is blocked but not curl: https://github.com/searxng/searxng/issues/1966#issuecomment-1441300370

---

Also what's the TLS version that httpx uses? IIRC you can't easily fingerprint a client in TLS 1.3 because the ciphers suites is very small, see page 20 of this document: https://owasp.org/www-chapter-london/assets/slides/OWASPLondon20180125_TLSv1.3_Andy_Brodie.pdf

Here is an example where it seems like it's possible to force TLS 1.3: https://github.com/encode/httpx/issues/469#issuecomment-540650240. The only issue is that not all the webservers in the world support TLS 1.3 so this may break some engines.

**Comment by return42** [comment]
> Here is an example where it seems like it's possible to force TLS 1.3: 

This comment also says ..

> Currently we don't allow passing an SSLConfig object to `verify=` (which maybe we should because this is painful)

AFAIK you can only pass a boolean to the argument `verify` .. here is what we do:

https://github.com/searxng/searxng/blob/9dc36965bbb118db64c0bf2d3f54389d4d484670/searx/network/client.py#L55-L58

.. by default we pass `verify=True` what builds a TLS 1.3 context.

> IIRC you can't easily fingerprint a client in TLS 1.3 because the ciphers suites is very small

I assume you can add additional strings like `!aNULL`, `!eNULL` .. and if I am not wrong:

- this is what httpx does by default 
- and the hash of the [JA3](https://github.com/salesforce/ja3) method includes all this additional strings in the cypher suite string.

TBH, I don't really know in deep / I did a lot of assumptions :-)

**Comment by dalf** [comment]
<details>

<summary>out of topic about the `verify` field</summary>

> you can only pass a boolean to the argument verify

Actually, it can be a path to a certificate. So the `verify` fields in `settings.yml` can be a path to certificate too.
See https://github.com/searxng/searxng/pull/1529

</details>

**Comment by unixfox** [comment]
> TBH, I don't really know in deep / I did a lot of assumptions :-)

Don't worry it's a lost cause, httpx already use TLS 1.3 by default.

**Comment by unixfox** [comment]
Shuffle may not be the ideal way, I think it would be better to be as close as possible to a JA3 of firefox: https://nitter.net/BillDemirkapi/status/1663580689969577990

For example, this library allows doing that and may support httpx: https://github.com/yifeikong/curl_cffi. Downside is that you need to use a specific curl_impersonate library like explained in https://github.com/yifeikong/curl_cffi#current-status but that wouldn't be an issue for docker based installations as everything could be packaged in it.

I can see that some proxies for changing ja3 exist: https://github.com/Kolosok86/proxy

**Pull request merged**
