### PR TITLE
[docs] switch sphinx theme from pallets to furo

### LINKED ISSUE #635: Better Doc Navigation / Maybe new SearXNG doc theme and URL?
**Is your feature request related to a problem? Please describe.**

Right now the navigation in our doc does not show all available pages, but rather only the next page after a current page and the previous one as well as where the page is located in the directory tree. This makes it hard IMO to find a resource, since a user always needs to go back to https://searxng.github.io/searxng/ to find the right resource.

**Describe the solution you'd like**

Have a navigation like https://doc.traefik.io/traefik/ (on the left) or rather have the overview of https://searxng.github.io/searxng/ as navigation on the left.

**Describe alternatives you've considered**

Maybe add a navigation manually if it cannot be generated by the theme?

**Additional context**

Ping @return42 @not-my-profile

### PR DESCRIPTION
**Pull request by return42**
update 2026: there is a follow up PR:

- https://github.com/searxng/searxng/pull/3408

-----

## What does this PR do?

[docs] switch sphinx theme from pallets to furo

## Why is this change important?

- https://github.com/searxng/searxng/issues/635

## How to test this PR locally?

    make docs.clean docs.live

A preview is available here: https://return42.github.io/searxng/index.html

## Author's checklist

Need some polish / DRAFT

## Related issues

Closes #635

### CODE REVIEW

**Comment by return42** [comment]
**update** : fixed in 870bf312

Sphinx `sphinx_tabs.tabs` does not support dark/light mode.

grafik

**Comment by return42** [comment]
Directive `.. contents::` are not needed in this theme / we need to _disable_ this directive:

grafik

**Comment by not-my-profile** [comment]
I have noticed four things with Furo that bother me:

* the horizontal scrolling on  https://return42.github.io/searxng/admin/engines/configured_engines.html
  At least on a 1080p desktop display the whole tables should be viewable without horizontal scrolling.

* when the sidebar is long clicking on something in the sidebar looses the scrolling position in the sidebar
  For example on [this page](https://return42.github.io/searxng/admin/engines/search-indexer-engines.html), scroll down in the sidebar and click on "Xpath engine" ... you now lost your scrolling position.
  I find this so disorienting that IMO it does not actually improve the navigation (which the issue is about).

* The tab focus order is suboptimal for keyboard accessibility: with the old theme hitting tab selected the first link in the page content, now you have to tab over everything in the sidebar. Accessibility is quite important to me so this does bother me. (For testing this you can add the CSS `*:focus { background: red; }`.)

* Inconsistent font sizes: The tip text, the main text and the sidebar text all have different font sizes. What's up with that? To me it looks really bad.
image

**Comment by return42** [comment]
> I have noticed three things with Furo that bother me:

This PR is just a starting point, I think the Furo theme needs some polish .. like we have polished the pallet theme in the past.

I will have a look, how we can improve the issues you named / suggestions & remarks are welcome / thanks!

**Comment by return42** [comment]
After playing a while with the Furo theme and trying to customize I came to the conclusion that this theme waste my time.

The text layout is quite horrible, @not-my-profile named some issues. When I compare the text layout with what we have produced by TeX in the 90's last century I get eye cancer these days.  Anyway I tried to customize the Furo theme but this is where the next issues started.  The theme is not inheritable (like we [inherit the poco theme](https://github.com/searxng/searxng/blob/master/docs/_themes/searxng/theme.conf)) and [Overriding or replacing a theme’s stylesheet](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html#overriding-or-replacing-a-theme-s-stylesheet) (referenced by Furo) does not work.

This theme supports a navigation bar and a dark/light mode switch, which is in the theme's favor, but the price is to go one step forward and three steps back.

We should look for better alternatives I think / I close this DRAFT.

**Comment by dalf** [comment]
The next one on https://sphinx-themes.org/#themes is book.

**Comment by not-my-profile** [comment]
Book seems very broken, [go here](https://sphinx-themes.org/sample-sites/sphinx-book-theme/kitchen-sink/paragraph-markup/) and scroll up and down and observe how the table of contents annoyingly pops in and back out.

**Comment by return42** [comment]
> Book seems very broken,

Small issue can be fixed on the customizing, I am open for new suggestions. The [book theme](https://sphinx-themes.org/sample-sites/sphinx-book-theme/kitchen-sink/) does not have dark/light mode.

I had a look at different themes (https://sphinx-themes.org) but I can't see a good replacement for what we have.  

In https://github.com/searxng/searxng/pull/648 I added a TOC, now I only miss a dark/light mode.

**Pull request closed without merging**
