### PR TITLE
[logo] SearXNG logo & trademark (WIP)

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

SearXNG logo & trademark (WIP)

## Why is this change important?

SearXNG need its own logo.

## How to test this PR locally?

A first draft, not yet ready to test!

Have a look at:  https://github.com/return42/searxng/tree/searxng-logo/src/brand

I am not very creative  .. comments are welcome ... personally I prefer ...

grafik

----

Related-to: https://github.com/searxng/searxng/issues/370

### CODE REVIEW

**Comment by dalf** [comment]
image

Some comments:
* I like the idea of moving from "searx" with the typography.
* But, from my eyes, the vertical `ear` feels like a `I`, so I can read `SIXNG`:
* Also `ear` is a word with different meaning ( https://en.wikipedia.org/wiki/Ear_(disambiguation) ,  https://en.wikipedia.org/wiki/Ear_(botany)  )

I have difficulties to say if it's a right or not.

**Comment by return42** [comment]
> Also `ear` is a word with different meaning

Haven't thought about "I" and "ear" :) .. I will design something new .. coming soon.

**Comment by SecularSteve** [comment]
I've got one of my own:

searXNG

ZIP comes with SVG and PNG, free of charge...

[searXNG.zip](https://github.com/searxng/searxng/files/7289205/searXNG.zip)

CC BY-SA 4.0, Inkscape

**Comment by sw5ciprl** [comment]
Frame 132

Took a poke at the design. Thoughts?

**Comment by dalf** [comment]
disclaimer: totally subjective view point.

@SecularSteve Thank you. It use the typography to emphasize "NG", but I feel it is too much.

@Bounty780 I like this version. One note: I've usually seen  "ng" in lower case, but SearXNG has started to write "NG" in upper case.

---

I don't know if this is doable: perhpas in "NG", the G can be magnifying glass.

---

Should we make a vote on which logo to use? using GH reaction emoticons? A dedicated web page?

**Comment by return42** [comment]
> Should we make a vote on which logo to use? using GH reaction emoticons? A dedicated web page?

No. Finding the "right" is IMO not a democratic decision .. give us more time and we will find a logo that fits our needs. I have some alternatives in mind but did not have the time right now to bring it down.

**Comment by mrpaulblack** [comment]
I think we can close this for now, since we have a temp logo and watermark and just keep the issue open... (@return42 feel free to reopen)

**Pull request closed without merging**
