### PR TITLE
[doc] searxng brand

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

image

## Why is this change important?

Update copyright notice

### CODE REVIEW

**Comment by return42** [comment]
How did you made the ["searXNG" logo](https://github.com/searxng/searxng/blob/a447b256156f621cf4d525f71f71fc001c17f98f/docs/static/img/searxng.png)?

- shouldn't it be "SearXNG"?
- The SearXNG logo should be stored in its origin format (e.g. SVG)
- I think the typography is improvable, the proportions of the letters are not right and there are hard breaks like this one
grafik

If you want, I can patch on top of your branch what I think improves the typography. Unfortunately this might take some time since I do not have much time at the moment.

**Comment by dalf** [comment]
> How did you made the "searXNG" logo?

Inkscape + a lot of search on Internet, since I don't know how to use it :-)

I can restore the logo, so
* we can merge this PR (if there are no other issues about it)
* take the time to create a logo

**Comment by return42** [comment]
> I can restore the logo, so ... we can merge this PR (if there are no other issues about it)

Yes, lets do it that way.

**Comment by dalf** [comment]
Done

**Comment by dalf** [comment]
... and of course when I rewrote https://github.com/searxng/searxng/blob/13a4d20e8dc3fbad8f4094b318a96153d563823e/docs/conf.py#L135
I forgot to replace `Searx`  by `SearXNG`...

**Pull request merged**
