### PR TITLE
Add helm chart for SearXNG

### LINKED ISSUE #1256: Kubernetes Helm Chart for SearxNG
**Is your feature request related to a problem? Please describe.**

I'm using the Kubernetes Helm Chart from here: https://github.com/k8s-at-home/charts/tree/master/charts/stable/searx
searxNG was not usable with this chart by only changing the image to searxng/searxng.

**Describe the solution you'd like**

A Kubernetes Helm Chart for SearxNG woud be great :-)

**Describe alternatives you've considered**

Use a Kubernetes Deployment

**Additional context**

@unixfox according to the chat in #searxng:matrix.org I should ping you :-)

### PR DESCRIPTION
**Pull request by unixfox**
## What does this PR do?

This adds a helm chart for easily installing SearXNG on Kubernetes.

## Why is this change important?

Make things easy for Kubernetes users.

## How to test this PR locally?

1. Install a Kubernetes cluster. You can use k3s: https://k3s.io/
2. Install Helm: https://helm.sh/docs/intro/install/
3. Install the helm chart by following https://github.com/searxng/searxng/blob/c52fb8a65787e50d0ca7bf0d739d6fd93a5eca12/kubernetes/chart/README.md#installing-the-chart
4. The helm chart should be deployed, you can test it by following the NOTES at the end of the output of the command.

## Author's checklist

The chart is located in kubernetes/chart because it's commonly placed like this in most of the projects that have an helm chart. 

I didn't write any documentation for docs.searxng.org because I'm a bit lazy (and I don't really like reST), but feel free to add a page that points towards the README file of the helm chart.

## Related issues

Closes #1256

### CODE REVIEW

**Comment by mrpaulblack** [comment]
Would you think it makes sense to add this to searxng/searxng-docker (we could even rename it to something more generic for example) or to create a seperate repo for this?

This way it would be easier to discover by new users of the project, it would also mean that people dont need to git clone the entire SearXNG core repo and it would also separate SearXNG core development from the helm charts in a way...

**Comment by unixfox** [comment]
Separating repository would be a great idea because I would be able to do some GitHub actions thing in order to push the helm chart to a repository served on HTTP(S).

But the downside is that people will have to dig a bit more in order to find the chart, but this could be solved by advertising it directly in the README of the searxng main repository. Something that I don't understand why we are not already advertising the Docker image too :).

**Comment by mrpaulblack** [comment]
yeah agreed a install section in the readme could be a great thing to advertise docker, helm and the script installation; If you create the helm repo we can also pin it like the docker repo in the org :+1:

**Comment by dalf** [comment]
> Separating repository would be a great idea because I would be able to do some GitHub actions thing in order to push the helm chart to a repository served on HTTP(S).

When to run it? After each commit on the master branch of searxng/searxng ?

**Comment by unixfox** [comment]
> > Separating repository would be a great idea because I would be able to do some GitHub actions thing in order to push the helm chart to a repository served on HTTP(S).
> 
> When to run it? After each commit on the master branch of searxng/searxng ?
> 

The github actions workflow is just to update the chart files to our helm repository when I push some changes to it.

This has nothing to do with the main searxng/searxng repo

**Comment by dalf** [comment]
So I agree, we can have another repository for the helm chart, and then add link to it in README and the documentation.

**Comment by unixfox** [comment]
Migrated to https://github.com/searxng/searxng-helm-chart/tree/main/searxng

**Pull request closed without merging**
