### PR TITLE
Draft: remove utils/morty.sh and utils/filtron.sh

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

Remove `utils/morty.sh` and `utils/filtron.sh`

TODO:
* [ ] update the documentation
* [ ] test the scripts

## Why is this change important?

SearXNG can now works without morty and filtron.

## How to test this PR locally?

N/A

### CODE REVIEW

**Comment by return42** [comment]
FYI I work on a complete new script ``utils/searxng.sh`` / in my [searxng-install](https://github.com/return42/searxng/commits/searxng-install) branch.

My Intention was a little bit different / I will implement the new script and when it is ready I will remove all the old scripts (searx.sh, filtron.sh, morty.sh) and the generic build of the documentation.

**Comment by dalf** [comment]
So I can close this PR.

Is there a quick way to update the documentation first ? So the users don't install Morty & Filtron any, so we don't have support these two repository. 

However, I don't see a lot requests about this subject so may be this can way too.

**Comment by 3nprob** [comment]
@dalf: While morty is not a strict dependency, what is the motivation for not removing the existing support for it? It has a lot of use-cases that are not in scope for image_proxy

**Comment by mrpaulblack** [comment]
For example it does not (in its current state) run on other architectures. Also I believe its always better to keep the stack as simple as possible, so using the image_proxy makes the stack simpler... If you mean that there is the proxy button with morty there is a tracking issue here: https://github.com/searxng/searxng/issues/857


(Also nobody really worked on morty for quite some time; we already updated our docker stack to drop morty so it only makes sense to also drop it from the scripts and tbh we are a small team and providing one installation method instead of multiple onse makes support also a lot easier...)

**Comment by return42** [comment]
> However, I don't see a lot requests about this subject so may be this can way too.

For the moment I will wait to remove the docs .. I haven't thought all the scenarios to its end yet, but I assume I will offer a way to upgrade old filtron & morty installations (or at least  some warnings when an old filtron and/or morty installation is detected in a SearXNG instance).

**Pull request closed without merging**
