### PR TITLE
[feat] zlibrary engine use zlibrary-global.se

### PR DESCRIPTION
**Pull request by paolobasso99**
## What does this PR do?

This PR:
1. re-enables z-library as the new domain zlibrary-global.se is now available from the open web. The announcement of the domain: https://www.reddit.com/r/zlibrary/comments/13whe08/mod_note_zlibraryglobalse_domain_is_officially/ (It is an official domain, it requires to log in to the "personal" subdomain only to download files, but the search works.)
2. changes the result template of zlibrary to paper.html, filling the appropriate fields
3. implements language filtering for zlibrary
4. implement zlibrary custom filters (engine traits)
5. refactor and document the zlibrary engine

## Why is this change important?

z-library is very useful and it is back.

## How to test this PR locally?

Search with !zlib

## Related issues

https://github.com/searxng/searxng/issues/2345#issuecomment-1517319202

### CODE REVIEW

**Comment by paolobasso99** [comment]
Converting to draft, I will try implementing engine traits.

**Comment by paolobasso99** [comment]
Done, I have updated the initial PR comment accordingly.

**Comment by return42** [comment]
@paolobasso99 I rebased your branch on SearXNG's master branch and squashed the commits .. ut I haven't finished my review .. I will continue the next days ...

**Comment by return42** [comment]
@paolobasso99 great work :+1: .. sorry for the git-push mess from mine .. I was in a hurry the last days, but now I finished my review.

To summarize what I have done:

- I rebased your branch on SearXNG's master branch and squashed your commits into one (see comment above)
- I placed a WIP commit on top of your branch

In the WIP commit:

1. Move the .rst to the new location ... in #2537 I reordered the docs / engines documented now [here](https://docs.searxng.org/dev/engines/index.html)

2. response: added i18n to terms "Language", "Book rating" and "File quality" (in the UI of z-library its named "File quality" not "Book quality")
3. response: tried do condense the code for better readability .. "readability" is in the eye of the beholder, the new code is strongly influenced by my subjective views.

Can you please have a look at the WIP commit / is 3. OK for you? If you think different, we can revert it.

Otherwise I would squash my WIP commit into you commit and merge this PR into master branch.

----

Further: what do you think about the following points:

- I have noticed timeouts, e.g. when I search for terms like YBCO `!zlib ybco :en`.  But I don't know if it would be good to increase the timeout from 7 to e.g. 10.
- The z-library is currently in the category 'files', I don't know if it would make sense to add it to another category like 'general' (the drawback is the long timeout).

I have left it as it is for now, but I would be interested in your opinion.

**Comment by paolobasso99** [comment]
Changes are ok for me, thanks.
It makes sense to increase the timeout but, honestly, I don't know exactly what are the implications of doing so.
About adding the engine to other categories, in my personal use, I prefer to have it only on files but that is just me.

**Comment by return42** [comment]
> It makes sense to increase the timeout but, honestly, I don't know exactly what are the implications of doing so.

Let's look at the process flow

1. User sends search term to SearXNG
2. SearXNG sends this request **in parallel** to a "group of engines" and **waits** for the responses
3. SearXNG aggregates the results from engines and sends a result list back to the user

In 2. we have the bottleneck, SearXNG has to wait until the last engine has answered ... but what if there is one among the engines that never response or it takes extremely long until it finally response?

To limit the impact of this bottleneck on the process flow, each engie has a timeout.  If it does not respond within this period, its response is ignored and the process flow can continue once the maximum timeout has expired.

The "group of engines" (by example) is built up by the active engines in category "general". If the user wants to be more selective, he can select engines or groups of engines directly via the search syntax [(single bang)](https://docs.searxng.org/user/configured_engines.html) in addition to the categories that are selectable as tabs in the UI.

In the SearXNG default setup we have an priority on a fast response in the category "general".  Engines in this category that are active by default have a maximum timeout of 3sec. This ensures that the user receives a result list after approx. 3sec at the latest (as long he is in the "general" category).

There are several other engines in this category that the user can activate, but these have longer timeouts and the user must be prepared that his search queries will usually take longer than in the default configuration.

-----

In the light of the explanation above, it may also become clearer why I consider the activation of all engines (including the saving of this setting) to be wrong and why I rejected https://github.com/searxng/searxng/issues/2536#issuecomment-1616143729

**Comment by paolobasso99** [comment]
Understood, in this case, I would leave z-lib in the files category only.

**Pull request merged**
