### PR TITLE
[mod] add support for the ipfs-search engine

### PR DESCRIPTION
**Pull request by return42**
- enable paging for ipfs search
- added support for images, music and video to the ipfs search engine

## What does this PR do?

The patches of this PR has been cherry picked and squashed from @elpoelma / see PR https://github.com/searx/searx/pull/3218

There is some more work needed / if someone is interested in this engine ask for or send me your patches.

### CODE REVIEW

**Comment by dokterbob** [comment]
@return42 \o/

What is needed to get this merged?

**Comment by return42** [comment]
Right now, I have not investigated any work in this PR .. I do not have any practical experience with this engine nor in using IPFS, may be several things can be improved:

- language support?
- time range support?
- Selecting mime type by the category name `mime_type = mime_types_map.get(params['category'], '*')` is not good --> when we place the engine by example in a category named `foo` the mime_type selection does no longer work.

@dokterbob do you have practical experience in using [IPFS](https://docs.ipfs.tech/)?

**Comment by elpoelma** [comment]
@dokterbob  @return42 I will look into updating my original PR on searx if I find the time tomorrow. @return42 Thanks for the feedback!

**Comment by elpoelma** [comment]
I added support for time ranges in the original PR on searx. Language support was not yet added as IPFS search does not support this yet IIRC.

**Comment by elpoelma** [comment]
@return42 On the mime type issue: IPFS search only supports general, images, music and videos, other categories should normally not show up.

**Comment by return42** [comment]
> I added support for time ranges in the original PR on searx. 

Thanks a lot, I will have a look and cherry pick .

> Language support was not yet added as IPFS search does not support this yet IIRC.

:+1:

> On the mime type issue: IPFS search only supports general, images, music and videos, other categories should normally not show up.

OK, I understand .. anyway I will have a look if we can move the `mime_times_map` to the settings.yml configuration.

I do not have much time these days .. I'm sorry if you have to be patient a little longer.

**Comment by return42** [comment]
FWIW I reopened & rebased this PR as DRAFT .. 

- https://api.ipfs-search.com/v1/

```
SSLError [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131), verify=True
```

**Comment by return42** [comment]
Due to lack of interest, I am now closing this DRAFT.

**Pull request closed without merging**
