### PR TITLE
[feat] yep: support for images and news (and safesearch)

### PR DESCRIPTION
**Pull request by Bnyro**
## What does this PR do?
* implement a python module for "yep" with support for images and news

## Why is this change important?
* yep provides decent results and has its own index (iirc)

## How to test this PR locally?
* !yep hello world
* !yepi hello world
* !yepn hello world

### CODE REVIEW

**Review by unixfox — COMMENTED** [review]
Only one page of results?

**Comment by Bnyro** [comment]
Yes, images and news only have one page. e.g. https://yep.com/images?q=foo

**Review by return42 — CHANGES_REQUESTED** [review]
Sorry / posted in the wrong PR:

~~When tested I got an exception .. can you please have a look / thanks!~~

**Review by return42 — APPROVED** [review]
Works like a charm / thanks :+1:

**Review by unixfox — APPROVED** [review]

**Pull request merged**
