### PR TITLE
[fix] simple theme: fix modal dialog

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

Currently, the help of keyboard shortcuts is displayed incorrectly:
image

This PR fixes this issue using `display:block`.

In addition, the dialog appears with a slight animation

## Why is this change important?

Fix UI

## How to test this PR locally?

* `make themes`
* `make run`
* enable vim shortcuts in the preferences
* press key `h`

### CODE REVIEW

**Comment by return42** [comment]
ready to review?

**Comment by dalf** [comment]
Yes (the static build commit is missing)

**Comment by return42** [comment]
LGTM .. one nit I have .. if mobile user accidentality types `h` the modal pops up, but there  is no chance to close the modal dialog .. due to centric alignment, the _close window `X`_ is not shown in the view port.

grafik

**Comment by mrpaulblack** [comment]
I added a small commit to move the keyframe animations into a new file: animations.less I think it would be good to move all animations and all transitions into this file to keep them all together; Fell free to force push over my commit it is just an example...

**Comment by return42** [comment]
>  one nit I have .. if mobile user accidentality types h the modal pops up, but there is no chance to close the modal dialog

Ooops, I was wrong .. 

grafik

FYI: I rebased and added the `[build] /static` on top ..

Thanks for this PR!

**Comment by dalf** [comment]
> I added a small commit to move the keyframe animations into a new file: animations.less I think it would be good to move all animations and all transitions into this file to keep them all together; Fell free to force push over my commit it is just an example...

Note: there is another animation here:
https://github.com/searxng/searxng/blob/0e27578e3528f6dc95a0ae8801e1972b3fdc1766/searx/static/themes/simple/src/less/search.less#L247-L250

**Pull request merged**
