### PR TITLE
Replace chompjs with pure Python code

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

The new implementation is good enough for the current usage (brave)

## Why is this change important?

Remove a dependency with C code.

## How to test this PR locally?

Check the brave image engine.

### CODE REVIEW

**Review by Bnyro — APPROVED** [review]
Works great, nice job!

This is much better than using the C dependency within ChompJS.

**Comment by allendema** [comment]
I found the js_to_json function from yt-dlp which worked fine.

https://github.com/yt-dlp/yt-dlp/blob/5d0395498d7065aa5e55bac85fa9354b4b0d48eb/yt_dlp/utils/_utils.py#L2663

And tests for it: [test_utils.py#L1099](https://github.com/yt-dlp/yt-dlp/blob/5d0395498d7065aa5e55bac85fa9354b4b0d48eb/test/test_utils.py#L1099)

**Comment by dalf** [comment]
@allendema nice, do you think we should replace the current implementation?

or at least it provides an alternative in case the current one is not enough.

**Comment by allendema** [comment]
No, the current implementation can stay.
If new engine has any edgecases, the above function could be added. But right now there is no need for it.

**Pull request merged**
