### PR TITLE
Oscar theme: fix search input field on Safari

### LINKED ISSUE #323: Search input field sometimes not being clickable in Safari (iOS & macOS) when using oscar.
The search bar sometimes gets blocked after hitting enter or pressing the search button. This happens in Safari 14.1.2 (16611.3.10.1.6) when using the oscar theme with pointhi, logicodev or logicodev-dark with all recent versions of searx or searxng.

Example video showing the bug: https://youtu.be/psY2jXM-vUE

I already tried to fix this (https://github.com/tiekoetter/searxng/commit/c45611e5c6583ca01864c7c2ed8ae51bf7c3e6f3) but I am not a developer so there is probably a better solution.

Example video showing the expected behavior using my fix: https://youtu.be/FqNf_DmK68E

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

Oscar theme: make sure search input field z-index is always 2 even when focused.

Code from https://github.com/tiekoetter/searxng/commit/c45611e5c6583ca01864c7c2ed8ae51bf7c3e6f3

## Why is this change important?

On Safari the input field disappears. 

## How to test this PR locally?

with Firefox, Chrome & Safari, check the search input field is displayed:
* when focused
* when the autocompletation are displayed
* when not focused

## Related issues

Close #323

### CODE REVIEW

**Comment by return42** [comment]
@tiekoetter I do not have a Safari at hand, could you please test this PR / thanks!

**Comment by tiekoetter** [comment]
@return42 The fix works with all oscar styles.

Logicodev:
Bildschirmfoto 2021-09-19 um 15 10 35

Logicodev-dark:
Bildschirmfoto 2021-09-19 um 15 11 04

Pointhi:
Bildschirmfoto 2021-09-19 um 15 11 32

**Comment by return42** [comment]
Not related to this patch, but while we are looking at the input bar: Depending on the zoom factor in Firefox I see an issue on the bottom border of the input field and the buttons on the right side / a one pixel hiccup which might related to some relative sizes.

grafik

**Comment by dalf** [comment]
With the initial change of this PR, I forgot that the Firefox & Chrome layouts are changed.

Without being able to run Safari locally, I've changed this PR to use a CSS hack, see: 
* https://github.com/searxng/searxng/pull/330/commits/2cc6301c98caf561dda77c7929c3f5f455a69312
* more precisely https://github.com/searxng/searxng/blob/2cc6301c98caf561dda77c7929c3f5f455a69312/searx/static/themes/oscar/src/less/safari.css

(*) I've tested this checked with: Firefox, Chrome & Safari 12 (using a free account on lambdatest.com).
There are issues with Safari 12 actually, but I guess you are using the last version.

Any better implementation is welcomed.

**Comment by theeddie** [comment]
im still having the issue, ill get into a little

**Pull request merged**
