### PR TITLE
[engine] petal search

### LINKED ISSUE #1247: [engine] add petal search
**Working URL to the engine**
https://petalsearch.com/

**Why do you want to add this engine?**
Its apparently the default search engine in the huawai browser?

**Features of this engine**
Its fast, the design is pretty similar to google, optimized for mobile devices and it has a lot of "normal" results and not so many instant answers. The all and news category are the most important IMO.

**How can SearXNG fetch the information from this engine?**
I did not see an API from a quick check. Tho they return the results in a GET request, so they can be parsed from the HTML.

**Applicable category of this engine**
General and news as separate engines.

**Additional context**
Requested in Matrix by `omlet`.

### PR DESCRIPTION
**Pull request by tiekoetter**
Add Petal Search to SearXNG via XPath

## How to test this PR locally?

1. `make run`
2. Search for `!pts test`

## Related issues

Close #1247

### CODE REVIEW

**Review by mrpaulblack — CHANGES_REQUESTED** [review]
can you please add:

```yaml
wikidata_id: Q104399280
```

underneath about.website?

(and also if you have time add petal news?; it should work with just adding `channel=news` to the get request AFAIK)

**Review by mrpaulblack — APPROVED** [review]
LGTM, Thanks :+1:

**Comment by TheFrenchGhosty** [comment]
@tiekoetter Any reason why you also didn't add Images/Videos/Science? It seems like a useful engine to me.

**Comment by mrpaulblack** [comment]
This PR was created out of a request on Matrix; The user requested the news and general engine :+1:

**Comment by TheFrenchGhosty** [comment]
@mrpaulblack Well, I guess I'm requesting the other 3 then :D

**Comment by mrpaulblack** [comment]
@TheFrenchGhosty can you please create a PR for that or open an issue in the tracker since it will probably not get done immediately... Thanks :D

**Comment by tiekoetter** [comment]
@TheFrenchGhosty I will start working on it when I get home.

**Pull request merged**
