### PR TITLE
Improve settings_general.html

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?
Fix typo in settings_general.html: availabled -> available.
Made statement about metrics in `/preferences` more descriptive.

## Why is this change important?
Improves user/admin experience

### CODE REVIEW

**Comment by return42** [comment]
Hi @ToxyFlog1627 you fixed the typo in the compiled HTML .. we need to fix it in the source --> I replaced this PR by https://github.com/searxng/searxng/pull/2629

Anyway, thanks a lot for pointing out :+1:

**Comment by ghost** [comment]
I figured after seeing how you merged.

**Comment by ghost** [comment]
Why you didn't include second commit?
Personally, I couldn't really get where metrics were in preferences until doing side-by-side comparison, that's why I wrote it.

**Comment by return42** [comment]
> Why you didn't include second commit?

It was not shown in the diff ["Files changed"](https://github.com/searxng/searxng/pull/2628/files) .. since you create this PR from the wrong branch .. for more typos you find, please send a new PR from a branch that forked from the master branch (not from gh-pages).

**Comment by ghost** [comment]
Sure, sorry for the inconvenience

**Pull request closed without merging**
