### PR TITLE
[version] update searxng version of branch master to 1.1.0-pre

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

update searxng version of branch master to 1.1.0-pre

## Why is this change important?

The version number of the branch master must to be detached from the version of the last release.

### CODE REVIEW

**Comment by dalf** [comment]
Should we keep `major.minor.patch` ?
When do we remove `-pre` ?

What about `year.month.day` ? 

I would like to add the last git commit with something like this:
```python
import pathlib

def get_git_revision(base_path):
    git_dir = pathlib.Path(base_path) / '.git'
    with (git_dir / 'HEAD').open('r') as head:
        ref = head.readline().split(' ')[-1].strip()

    with (git_dir / ref).open('r') as git_hash:
        return git_hash.readline().strip()

print(get_git_revision('.'))
```

[EDIT] more complete versions:
* https://gist.github.com/pkienzle/5e13ec07077d32985fa48ebe43486832
* https://github.com/spapas/python-git-info
* https://github.com/pypa/setuptools_scm

**Comment by return42** [comment]
> When do we remove -pre ?

With the next release (major or minor).  After the (tagged) release commit, we have to increment minor-number again and add a  `-pre` ... or should we better use [`-dev`](https://www.python.org/dev/peps/pep-0440/#developmental-releases)?

> Should we keep major.minor.patch ?
> What about year.month.day ?

I do not have a preference to change the given  numbering, but in my projects I also use a _year month day_ numbering.  If you see some benefit in switching the numbering, lets do it.

Take into account, there is no way back since (e.g) `2021.x.y` in sense of semantic versioning comes  _after_ `1.x.y`. 

> I would like to add the last git commit with something like this:

I think this is not a very good idea .. this binds installation of a searxng version to an SCM system (git).  I think we should not establish such dependencies.

**Comment by dalf** [comment]
What trigger a new version / what is the target of a new version ?

> I think this is not a very good idea .. this binds installation of a searxng version to an SCM system (git). I think we should not establish such dependencies.

When the user press the button "Submit a new issue on Github" in `/stats`, the git commit is useful to know which version of the engine is used (we can even make a link to the source on github). The version won't give enough information since it can cover different version of the code.

**Comment by return42** [comment]
> When the user press the button "Submit a new issue on Github" in

I hope we will not receive to many duplicate issues .:) ... lets see.

> What trigger a new version / what is the target of a new version ?

Good question ..here are my 2cent 

... searx deploys packages on PyPi for this a version numbering is needed.  I think it is not a good idea to deploy searxng at PyPi.  I would like to ask "do we need versioning?" .. I don't think so, each commit is a new version I think.  By example: if a central engine like google is broken and a fix is available this fix needs to deploy on each instance as soon as possible.  Version numbers do not count here, I think.

I think I need to get away from the idea that searxng is a versioned program. 

With this in mind I see that your approach (using commit hash) seems to be the better one after all.

If we do so, if each commit is a version we can only deploy from the repository.  

... which means we bind deployment onto git (and a git hoster)
... this is a heavyweight consequence, I think

Side note: that was also a reason why I asked to place the issue form in `searx/templates/__common__` so we can easily  replace it by a template for a different issue system (from a different git hoster).

If I sum up my thoughts I would say that we can go this way but then, we should clearly exclude other pathes of  deployment (e.g. PyPi).

**Pull request closed without merging**
