### PR TITLE
[mod] simple-theme: remove vendor CSS

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

[mod] simple-theme: remove vendor CSS

**flexbox**: Browser support for flexbox is excellent, and the majority of browsers do not need a prefix at this point. Safari was the last of the major browsers to   remove prefixes, with the release of Safari 9 in 2015. [1]

**user-select**: Vendor prefix of user-select is not needed, see 'Browser compatibility' [2].

[1] https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox#status_in_browsers
[2] https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#browser_compatibility

### CODE REVIEW

**Comment by mrpaulblack** [comment]
tbh they should not be mixins if its only one generic line of css code IMO. Can you remove the mixins and replace every mixin call in the less files with just the specific line of css? For example replace `.flexbox;` with `display: flex;` and so on...

Apart from that removing the vendor prefixes LGTM :+1:

**Comment by return42** [comment]
@mrpaulblack sorry for long delay ..

> tbh they should not be mixins if its only one generic line of css code I

that true .. I removed the mixins / good to know: most of them hadn't been used :)

Hint: additional I pushed `[mod] simple theme: remove vendor prefix of width: max-content` on this branch.

**Comment by return42** [comment]
FYI: https://github.com/searxng/searxng/pull/584#commits-pushed-459f33a nothing changed / just rebased to solve conflicts

**Comment by dalf** [comment]
Thank you!

**Pull request merged**
