### PR TITLE
implement rate limiter whitelisting

### LINKED ISSUE #2127: disable rate limiter for whitelisted IPs/subnet
**Is your feature request related to a problem? Please describe.**
I would like to be able to use my instance without rate limiting when I am accessing it from within a specified subnet. 

I use docker and my instance has a public facing network and a local private one where I would like to use its API pro grammatically without rate limiting.

**Describe the solution you'd like**
Add an option in `settings.py` that would bypass the rate limiter.

**Describe alternatives you've considered**
Running a separate instance without rate limiter.
I find this solution very wasteful of resources. 

**Additional context**

### PR DESCRIPTION
**Pull request by blob42**
## What does this PR do?

Add the possibility to whitelist IPs or subnets from the rate limiter. 

Adds the options under the server section in `settings.yml`:
`server.limiter_whitelist_ip`
`server.limiter_whitelist_subnet`

## Why is this change important?

This is a proposal for #2127. I am trying to add Searx as a search engine source for [langchain](https://github.com/hwchase17/langchain/pull/854). Using the json endpoint quickly hits the rate limiter. People usually enable the rate limiter, adding this feature allows the instance to be used publicly as well as a for development purposes. 

## How to test this PR locally?

I added proper unit tests and tried running the instance with valid and invalid parameters.

## Author's checklist

TODO:
- [x] add tests
    - validate the ip address/subnet format 
- [x] update documentation

## Related issues

Fixes #2127

### CODE REVIEW

**Comment by blob42** [comment]
I just realized it's unsafe to use `request.x_forwarded_for` without whitelisting a proxy as well. I might need to add an option to add a proxy as trusted.

**Comment by blob42** [comment]
Hi, I am willing to complete this PR to make it acceteable to merge. Some feedback would be great before I move on with the tests and the doc.

I am currently building this feature to complete a PR on [LangChain](https://github.com/hwchase17/langchain/pull/854) , a large language model framework for building AIs. The framework allows AI to connect and search the internet. Right now they only implemented Google or paid APIs as options. I am adding SearX as well. I believe this will be bring more attention to searx. 

I would also like to improve this feature by adding an API key that allows to bypass the limiter

**Comment by blob42** [comment]
I added some unit tests and updated the documentation. I tried following the contributors guidelines for the commits and testing.  @return42  Let me know if further edits are needed.

**Comment by dalf** [comment]
Thank you for this PR.

Can you have a look to the following patch:
* it calls `ip_address` and `ip_network` only once for the settings.
* `init_whitelist` to make tests easier
* `get_remote_addr` get the IP address for the function `is_accepted_request` ( for reference: https://esd.io/blog/flask-apps-heroku-real-ip-spoofing.html )

```patch
diff --git a/manage b/manage
index a779d1ff2..f94b6cc54 100755
--- a/manage
+++ b/manage
@@ -694,6 +694,7 @@ test.pylint() {
         build_msg TEST "[pylint] searx tests"
         python ${PYLINT_OPTIONS} ${PYLINT_VERBOSE} \
             --disable="${PYLINT_SEARXNG_DISABLE_OPTION}" \
+            --additional-builtins="${PYLINT_ADDITIONAL_BUILTINS_FOR_ENGINES}" \
 	    --ignore=searx/engines \
 	    searx tests
     )
diff --git a/searx/plugins/limiter.py b/searx/plugins/limiter.py
index f45b4fb45..d5aa18894 100644
--- a/searx/plugins/limiter.py
+++ b/searx/plugins/limiter.py
@@ -5,9 +5,9 @@
 
 To monitor rate limits and protect privacy the IP addresses are getting stored
 with a hash so the limiter plugin knows who to block.  A redis database is
-needed to store the hash values. 
+needed to store the hash values.
 
-It is also possible to bypass the limiter for a specific IP address or subnet 
+It is also possible to bypass the limiter for a specific IP address or subnet
 using the `whitelist_ip` and `whitelist_subnet` settings.
 
 Enable the plugin in ``settings.yml``:
@@ -23,6 +23,7 @@ Enable the plugin in ``settings.yml``:
 
 import ipaddress
 import re
+from typing import cast
 from flask import request
 
 from searx import get_setting, redisdb
@@ -45,35 +46,37 @@ re_bot = re.compile(
 )
 
 
-WHITELISTED_IPS = get_setting('server.limiter_whitelist_ip', default=[])
-WHITELISTED_SUBNET = get_setting('server.limiter_whitelist_subnet', default=[])
+WHITELISTED_IPS = []
+WHITELISTED_SUBNET = []
 
 
-def is_whitelist_ip(ip: str) -> bool:
+def is_whitelist_ip(ip_str: str) -> bool:
     """Check if the given IP address belongs to the whitelisted list of IP addresses or subnets."""
     # if ip is empty use the source ip
-    if ip == "" or ip is None:
-        ip = request.remote_addr or ""
-    logger.debug("checking whitelist rules for: %s", ip)
-    whitelisted = False
     try:
-        whitelisted = ip in WHITELISTED_IPS or any(
-            ipaddress.ip_address(ip) in ipaddress.ip_network(subnet) for subnet in WHITELISTED_SUBNET
-        )
+        ip_a = ipaddress.ip_address(ip_str)
     except ValueError as e:
         logger.error("Error while checking ratelimiter whitelist: %s", e)
+        return False
+    return ip_a in WHITELISTED_IPS or any(ip_a in subnet for subnet in WHITELISTED_SUBNET)
+
 
-    return whitelisted
+def get_remote_addr() -> str:
+    x_forwarded_for = request.headers.getlist('X-Forwarded-For')
+    if len(x_forwarded_for) > 0:
+        return x_forwarded_for[-1]
+    return request.remote_addr or ''
 
 
 def is_accepted_request() -> bool:
     # pylint: disable=too-many-return-statements
     redis_client = redisdb.client()
     user_agent = request.headers.get('User-Agent', '')
-    x_forwarded_for = request.headers.get('X-Forwarded-For', '')
+    remote_addr = get_remote_addr()
 
     # if the request source ip belongs to the whitelisted list of ip addresses or subnets
-    if is_whitelist_ip(x_forwarded_for):
+    if is_whitelist_ip(remote_addr):
+        logger.debug("whitelist IP")
         return True
 
     if request.path == '/image_proxy':
@@ -82,8 +85,8 @@ def is_accepted_request() -> bool:
         return True
 
     if request.path == '/search':
-        c_burst = incr_sliding_window(redis_client, 'IP limit, burst' + x_forwarded_for, 20)
-        c_10min = incr_sliding_window(redis_client, 'IP limit, 10 minutes' + x_forwarded_for, 600)
+        c_burst = incr_sliding_window(redis_client, 'IP limit, burst' + remote_addr, 20)
+        c_10min = incr_sliding_window(redis_client, 'IP limit, 10 minutes' + remote_addr, 600)
         if c_burst > 15 or c_10min > 150:
             logger.debug("to many request")  # pylint: disable=undefined-variable
             return False
@@ -110,7 +113,7 @@ def is_accepted_request() -> bool:
             return False
 
         if request.args.get('format', 'html') != 'html':
-            c = incr_sliding_window(redis_client, 'API limit' + x_forwarded_for, 3600)
+            c = incr_sliding_window(redis_client, 'API limit' + remote_addr, 3600)
             if c > 4:
                 logger.debug("API limit exceeded")  # pylint: disable=undefined-variable
                 return False
@@ -123,6 +126,20 @@ def pre_request():
     return None
 
 
+def init_whitelist(limiter_whitelist_ip: list[str], limiter_whitelist_subnet: list[str]):
+    global WHITELISTED_IPS, WHITELISTED_SUBNET  # pylint: disable=global-statement
+    if isinstance(limiter_whitelist_ip, str):
+        limiter_whitelist_ip = [limiter_whitelist_ip]
+    if isinstance(limiter_whitelist_subnet, str):
+        limiter_whitelist_subnet = [limiter_whitelist_subnet]
+    if not isinstance(limiter_whitelist_ip, list):
+        raise ValueError('server.limiter_whitelist_ip is not a list')
+    if not isinstance(limiter_whitelist_subnet, list):
+        raise ValueError('server.limiter_whitelist_subnet is not a list')
+    WHITELISTED_IPS = [ipaddress.ip_address(ip) for ip in limiter_whitelist_ip]
+    WHITELISTED_SUBNET = [ipaddress.ip_network(subnet, strict=False) for subnet in limiter_whitelist_subnet]
+
+
 def init(app, settings):
     if not settings['server']['limiter']:
         return False
@@ -131,5 +148,10 @@ def init(app, settings):
         logger.error("The limiter requires Redis")  # pylint: disable=undefined-variable
         return False
 
+    init_whitelist(
+        cast(list, get_setting('server.limiter_whitelist_ip', default=[])),
+        cast(list, get_setting('server.limiter_whitelist_subnet', default=[])),
+    )
+
     app.before_request(pre_request)
     return True
diff --git a/searx/settings_defaults.py b/searx/settings_defaults.py
index ae4a44156..46293da66 100644
--- a/searx/settings_defaults.py
+++ b/searx/settings_defaults.py
@@ -174,8 +174,8 @@ SCHEMA = {
         'port': SettingsValue((int, str), 8888, 'SEARXNG_PORT'),
         'bind_address': SettingsValue(str, '127.0.0.1', 'SEARXNG_BIND_ADDRESS'),
         'limiter': SettingsValue(bool, False),
-        'limiter_whitelist_ip': SettingsValue(list, []),
-        'limiter_whitelist_subnet': SettingsValue(list, []),
+        'limiter_whitelist_ip': SettingsValue((str, list), []),
+        'limiter_whitelist_subnet': SettingsValue((str, list), []),
         'secret_key': SettingsValue(str, environ_name='SEARXNG_SECRET'),
         'base_url': SettingsValue((False, str), False, 'SEARXNG_BASE_URL'),
         'image_proxy': SettingsValue(bool, False),
diff --git a/tests/unit/test_plugins.py b/tests/unit/test_plugins.py
index 1beab5c8c..fa0bada26 100644
--- a/tests/unit/test_plugins.py
+++ b/tests/unit/test_plugins.py
@@ -171,8 +171,7 @@ class LimiterPluginTest(SearxTestCase):
         self.assertTrue(len(store.plugins) == 1)
 
         def test_whitelist_case(case):
-            plugins.limiter.WHITELISTED_SUBNET = case[1]['whitelist_subnet']
-            plugins.limiter.WHITELISTED_IPS = case[1]['whitelist_ip']
+            plugins.limiter.init_whitelist(case[1]['whitelist_ip'], case[1]['whitelist_subnet'])
             ret = store.call(store.plugins, 'is_whitelist_ip', case[0])
             self.assertEqual(ret, case[2])
 
@@ -186,12 +185,6 @@ class LimiterPluginTest(SearxTestCase):
             )
         )
 
-        # not an ip
-        test_cases.append(('192.0.43.22', {'whitelist_ip': 'not an ip', 'whitelist_subnet': []}, False))
-
-        # not a subnet
-        test_cases.append(('192.0.43.22', {'whitelist_ip': [], 'whitelist_subnet': 'not a subnet'}, False))
-
         # test single ip
         test_cases.append(('192.0.43.22', {'whitelist_ip': '192.0.43.22', 'whitelist_subnet': []}, True))
 
@@ -211,3 +204,11 @@ class LimiterPluginTest(SearxTestCase):
 
         for case in test_cases:
             test_whitelist_case(case)
+
+        # not an ip
+        with self.assertRaises(ValueError):
+            test_whitelist_case(('192.0.43.22', {'whitelist_ip': ['not an ip'], 'whitelist_subnet': []}, False))
+
+        # not a subnet
+        with self.assertRaises(ValueError):
+            test_whitelist_case(('192.0.43.22', {'whitelist_ip': [], 'whitelist_subnet': ['not a subnet']}, False))
```

**Comment by blob42** [comment]
@dalf thanks for the review, much cleaner this way indeed. I will incorporate the patch.

**Comment by return42** [comment]
@blob42 to solve conflicts with current master, you need to rebase (not merge) your branch on current master  / BTW before commit run `make test` .. in py37 `list[..]` is not a valid type hint (import and use `List[..]`) --> https://github.com/searxng/searxng/actions/runs/4163033485/jobs/7202919317#step:7:76

**Comment by blob42** [comment]
@return42 Any chance this gets merged soon ? Should I resolve the conflicts ?

**Comment by return42** [comment]
> @return42 Any chance this gets merged soon ? 

Hi @blob42 I am very sorry for the delay, pardon me .. I have this PR on my ToDo list since a very long time, but its "on hold" .. until I have a final decision how to move on with the limiter / see my thoughts below.

> Should I resolve the conflicts ?

No need for at this time, I can do it when I'm back to this PR

-----

Here are some thoughts I have about future the limiter ..

When @dalf implemented the initial release of the limiter it was a plugin and the intention was to have a very simple bot blocker with zero configuration.

The limiter is now an indispensable part of SearXNG and the implementation is no longer a plugin but a fixed part of SearXNG.  In other words, a public instance is no longer conceivable without the limiter.

I would like to stick to the concept of "zero configuration", but realize more and more that this is not possible if we don't want to switch off the limiter completely ... and we don't want that :-)

Your PR here need an option in the settings.yml .. to whitelist .. tomorrow we need a block list .. and the PR

- https://github.com/searxng/searxng/pull/2357

will also need an option, at least to be enabled/disabled. And while we are there may be there comes the day a maintainer want to customize other filters like this one:

https://github.com/searxng/searxng/blob/master/searx/plugins/limiter.py#L29-L42

or want to add more filters .. whatever in the future will be conceivable.

I think what we need is a limter that runs with zero configuration and I think when we make options customizable this should no longer be done in the settings.yml .. I think we need a optional file like /etc/searxng/limiter.conf (or similar).

Before I have a concept for a limiter configuration I don't want to merge this PR (since it adds an option to settings.yml) and as soon as we give out this option to the maintainers this option is set in stone.

I want to get more experience with the PR https://github.com/searxng/searxng/pull/2357 first, when I have finished my work on this PR I have a future proof concept for a configuration of the limiter.

I'm very sorry, that you have to wait so long .. but I think it is not good to change how a component is configured .. first we need a future proof concept that scales.

**Comment by blob42** [comment]
@return42 no worries, thanks for the detailed explanation I totally understand. 

I can put some spare time to help so feel free to ping me if there is anything I can do including the UI side.

**Comment by blob42** [comment]
Last force push was just setting my git author email

**Comment by return42** [comment]
> I can put some spare time to help so feel free to ping me if there is anything I can do including the UI side.

Thank you for the offer :+1: .. TBH  I first had to think for myself "where the journey goes".  I tried to find an architecture that can be harmoniously embedded in the setups of the individual instances.

An architecture was built in the namespace [`searx.botdetection`](https://github.com/searxng/searxng/tree/master/searx/botdetection) / described [here](https://docs.searxng.org/src/searx.botdetection.html) .  

To customize the [Limiter](https://docs.searxng.org/src/searx.botdetection.html#limiter) there is a [`/etc/searxng/limiter.toml`](https://github.com/searxng/searxng/blob/master/searx/botdetection/limiter.toml) configuration file for this architecture. Without this configuration file the limiter runs as before ("vanilla limiter") - except for a few bugfixes.  

For block- and pass- lists you can use the [`ip_lists` method](https://docs.searxng.org/src/searx.botdetection.html#method-ip-lists) by adding a `[botdetection.ip_limit]` section to your local [toml](https://toml.io/en/) file.

Please note:

- There is a hard coded passlist [SEARXNG_ORG](https://docs.searxng.org/src/searx.botdetection.html#searx.botdetection.ip_lists.SEARXNG_ORG) to pass requests from `check.searx.space` / from [searx.space](https://searx.space/) 
- In the limiter, the ip_lists method has priority over all other methods -> if an IP is in the pass_ip list, it has unrestricted access and it is also not checked if e.g. the "user agent" suggests a bot (e.g. curl).

**Comment by blob42** [comment]
This looks perfect thanks for the update.

**Pull request closed without merging**
