### PR TITLE
Drop pytomlpp dependency for Python >= 3.11

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

Rely on tomllib for Python >= 3.11

## Related issues

- https://github.com/searxng/searxng/discussions/3267
- #2981

### CODE REVIEW

**Comment by return42** [comment]
Thanks for this PR / I will review!  .. ~but first I want to get #2981 reviewed and merged / if it is OK for you.~

**Comment by return42** [comment]
As long we do not see any drawbacks in using pytomlpp I'm not sure we should remove it .. its [4 times faster](https://github.com/hukkin/tomli?tab=readme-ov-file#performance) compared to the pure python implementation in py3.11.

However if we want less dependencies we should replace pytomlpp by tomli in py < 3.11 / tomli is the tomllib module that has been added to the standard library in Python 3.11 and the [compatibility layer](https://github.com/hukkin/tomli?tab=readme-ov-file#building-a-tomlitomllib-compatibility-layer) is simpler, compared the one we need for pytomlpp & standard library.

**Comment by dalf** [comment]
>  its 4 times faster compared to the pure python implementation in py3.11.

I don't think config loading is the SearXNG startup time bottleneck.

> if we want less dependencies we should replace pytomlpp by tomli in py < 3.11

I agree: tomli is a written in pure Python, so there is no additional build time for "uncommon" architectures.

**Comment by unixfox** [comment]
Real pleasure. Building pytomlpp for ARM on alpine Linux takes ages!

**Comment by unixfox** [comment]
Is this PR ready :)?

**Review by unixfox — APPROVED** [review]

**Review by Bnyro — APPROVED** [review]

**Pull request merged**
