### PR TITLE
[fix] brave.search - update result selectors to fit to new layout

### LINKED ISSUE #3167: Brave search results miss description, and title is prepended by site name and page url
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

559b8606189ff44eee6e8bcde2763daf3c2cbd7c

**How did you install SearXNG?**

**What happened?**

I've noticed most (if not all) search results coming from Brave are malformed: results titles include site name and result url (in breadcrumbs form), followed by the actual results page title.
Also, most of results descriptions are empty (This site did not provide any description).

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

brave_results

**Additional context**

### PR DESCRIPTION
**Pull request by return42**
Closes: https://github.com/searxng/searxng/issues/3167

### CODE REVIEW

**Comment by allixx** [comment]
Thanks! Works as intended in my tests.

**Comment by Bnyro** [comment]
Related: https://github.com/searxng/searxng/pull/3108

**Comment by return42** [comment]
> Related: #3108

@Bnyro I merged #3108 and rebased this PR / in d7029409482 of this PR the title tag is fixed.

If you have the opportunity, please check this PR again / thanks a lot :+1:

**Review by Bnyro — APPROVED** [review]
Works as expected, thanks!

**Pull request merged**
