### PR TITLE
[feat] engine: implementation of mwmbl

### LINKED ISSUE #1654: MWMBL
**Working URL to the engine**

https://mwmbl.org/
**Why do you want to add this engine?**

Open source, has a distributed crawler.
**Features of this engine**

it lets users contribute to the index by installing an extension.

Also, it crawls pages from hackernews.
**How can SearXNG fetch the information from this engine?**

doesn't look like it has an API and it requires JS, you can probably reverse engineer the scripts, I don't know enough JS to do it myself.
**Applicable category of this engine**

general
**Additional context**

### PR DESCRIPTION
**Pull request by Bnyro**
## What does this PR do?
* add a new engine, mwmbl, for general results

## Why is this change important?
* the results are pretty good for a foss non-meta search engine

## How to test this PR locally?
!mwm hello world

## Related issues
closes #1654

### CODE REVIEW

**Comment by Bnyro** [comment]
Oh, I forgot to put `disabled: true` on it, so that should be before merging. 
EDIT: fixed.

**Review by return42 — APPROVED** [review]
Seems to be an interesting project at first sight, it's just a pity that only little progress in the development can be observed.

Anyway, its worth to add a engine for / thanks a lot for your implementation :+1:

**Comment by Bnyro** [comment]
Yes, unfortunately it seems like the development stopped / paused some months ago.

Apart from that, it has a really nice UI actually, and the quality of the results is not that bad (in my personal opinion). With some more active development, this could have become a really great alternative for other proprietary search engines imo.

**Comment by EchedeyLR** [comment]
Development has not stopped.

There are some things that are being done on free time. Aside that, there is not much to do.

**Comment by EchedelleLR** [comment]
Development has not stopped.

There are some things that are being done on free time. Aside that, there is not much to do.

**Comment by EchedelleLR** [comment]
@Bnyro https://api.mwmbl.org/docs

This is the official API documentation.

**Comment by Bnyro** [comment]
Cool, thanks!

**Pull request merged**
