### PR TITLE
[simple theme] minor css fixes

### PR DESCRIPTION
**Pull request by mrpaulblack**
## What does this PR do?

Minor simple theme improvements, see commit message:
* remove hover effect from vim help modal
* remove bold font weight from active item in prefenreces tab bar
* remove margin from answer box to unify with rest of result page

## Why is this change important?

Polish simple theme.

## How to test this PR locally?

```make run```

## Related issues

### CODE REVIEW

**Comment by mrpaulblack** [comment]
(I am going to wait for #473 to get merged first...)

**Comment by dalf** [comment]
> add margin to left of border results to move them inline with search input form

The results from the general and social categories don't mix well.
For example, if I search for `!gpodder !qwant new york`, 
image

> remove margin from border results on tablet to center them correctly

I can't spot the difference. The margin seems to already be `margin: 1rem 0 !important;`

> remove margin from #answer on desktop

👍 

> remove hover effect from vim key modal

👍 

> unify first selected tab in pref.

👍

**Comment by dalf** [comment]
> add margin to left of border results to move them inline with search input form

My comment above is my view point. May be not an issue in someone's eyes.

> set search logo on result page as background image and remove complexity from html

it overlaps the changes in #473

**Comment by mrpaulblack** [comment]
@dalf Thank you for the review. I removed the margin on the result articles with a border as you suggested and also removed my changes to the watermark to not interfere with return42's watermark PR. I went ahead and merged since this PR shrunk down to 3 changed lines that you already approved...

**Pull request merged**
