### PR TITLE
[docker] multiarch build

### PR DESCRIPTION
**Pull request by dalf**
Add a new Makefile target `make docker.buildx` to build and push a multiarch docker image (it can't be only build).

use buildx with the --cache-from and --cache-to options to cache the layers
only the last built is cached

---

About buildx:
* https://docs.docker.com/buildx/working-with-buildx/
* https://github.com/docker/buildx/#binary-release

### CODE REVIEW

**Comment by return42** [comment]
Looks very interesting to me .. I hope I have the time to test it these days .. my docker skill is worse :-)

**Comment by dalf** [comment]
As suggested https://github.com/searx/searx-docker/issues/27 , most probably it requires:
* a base image with all the dependencies (and built). This image is built only when the dependencies change.
* an second image using the base image, with only the python code.

Or even a dedicated ARM host.

**Comment by dalf** [comment]
[EDIT] `--cache-from` and `--cache-to` options make it simple.

----

Since the job takes one hour:
* it is possible to create `searxng-base`  image with all the dependencies (distro & pip)
* the image is pulled : if it fails it is built and pushed.
* then `searxng` image uses this `searxng-base`.

So docker step takes one hour only when the dependencies change.

**Comment by dalf** [comment]
ping @unixfox

**Review by unixfox — APPROVED** [review]

**Comment by return42** [comment]
@unixfox thanks a lot for your review!.. @dalf I would like to test this PR also .. but ATM I do not have the time for .. it will take some days before I can start with.  Since @unifox already approved this PR .. feel free to merge (I can do my tests afterwards).

**Pull request merged**
