### PR TITLE
[enh] add instant answers from ddg

### PR DESCRIPTION
**Pull request by allendema**
## What does this PR do?

Get instant answers from ddg.

## Why is this change important?
Get instant answers for complex queries.

## How to test this PR locally?
`!ddg what's the 6th fibonacci number`

SearXNG_fibonacci

`!ddg 2 random latin paragraphs`

SearXNG_latin

`!ddg rot13 nathan fielder`
SearXNG_Nathan_Fielder

## Author's checklist

https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/t/
## Related issues

Related:
https://github.com/searx/searx/issues/1695
https://github.com/searx/searx/issues/60#issuecomment-307047773
https://github.com/searxng/searxng/issues/459

### CODE REVIEW

**Comment by Bnyro** [comment]
Just for my understanding: why do you want to make this optional? It seems like it just works out of the box without any additional configuration or API request needed looking at the code?

**Comment by allendema** [comment]
> Just for my understanding: why do you want to make this optional?

Just to have the option if anyone wants it disabled.

Note that it is enabled if:
- set to true
- instant_answers is not provided in settings

**Review by Bnyro — COMMENTED** [review]
> Just to have the option if anyone wants it disabled.
>
Well, we don't have options to disable answerers for other engines (Google, Brave, ...) either, so I'd not perfer to have that `instant_answers` option.

Apart from that lgtm.

**Review by Bnyro — APPROVED** [review]

**Review by return42 — APPROVED** [review]
HI @allendema, happy to see new contributions from your side :-) ..

Thanks for removing `instant_answers` option / BTW: excellent work :+1:

**Comment by allendema** [comment]
> happy to see new contributions from your side :-) ..

Its my pleasure :)

**Pull request merged**
