### PR TITLE
[doc] answer CAPTCHA from server's IP

### PR DESCRIPTION
**Pull request by return42**
Related: https://github.com/searxng/searxng/issues/2011#issuecomment-1553317619

### CODE REVIEW

**Comment by unixfox** [comment]
Can you print this documentation link in the error logs when searxng encounters an issue related to qwant?

**Comment by return42** [comment]
The described method to solve a CAPTCHA from server's IP is not only related to qwant .. you can use this method to solve IP blocking for whatever engine is blocked (rated as a bot by the origin search engine).

Our CAPTCHA detection is not precise enough to print this message when a CAPTCHA is detected; by example when qwants response a CAPTCHA we get a `qwant ( server API error )` / compare #2011.

**Comment by unixfox** [comment]
Hum no it won't work on most engines, most engines requires passing the cookie containing the captcha validation. That's actually impressive that qwant doesn't require that.

So I suggest to still print a message when an error is occurring in the qwant engine.

**Comment by return42** [comment]
> most engines requires passing the cookie containing the captcha validation.

I know google requires a cookie but AFIK ddg does not have a cookie .. and others?

> So I suggest to still print a message when an error is occurring in the qwant engine.

Lets wait what issue reports come in .. when I have a clear view on more than two or three engines we can print a message whenever it makes sense.

**Pull request merged**
