### PR TITLE
 [fix] normalize SearXNG color from #487cff to #3050ff 

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

 [fix] normalize SearXNG color from `#487cff` to `#3050ff`

## Why is this change important?

The blue color of the simple theme is [#3050ff](https://color-hex.org/color/3050ff) ...

https://github.com/searxng/searxng/blob/0311eba538df589bc11a4d76d3c94b104c5b764d/searx/static/themes/simple/src/less/definitions.less#L29

## How to test this PR locally?

**before:**

grafik

**after:**

grafik

grafik

### CODE REVIEW

**Comment by dalf** [comment]
For what it's worth, the lighter color is intentional: the combo high saturation and big size makes the logo too eye catchy in my opinion.

**Comment by return42** [comment]
> For what it's worth, the lighter color is intentional

AFAIK a good design is based on a color palette, in the CSS we define such a color palette:

- https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/src/less/definitions.less#L4 

ATM there is _one blue_: `#3050ff` for the light ~and dark~ theme.

I picked up this color and used it in the magnifier (logo) [see fill=](https://github.com/searxng/searxng/blame/master/src/brand/searxng-wordmark.svg#L54) .. My intention is to have "one blue" .. but you arguments count, I can confirm: `#3050ff` is to eye catchy.

IMO we have these options:

1. change color of "SearXNG" logo to `#3050ff` / what I have done in this PR: _to eye catchy_
2. define an additional _blue color_ `#487cff`
3. in definition.less change `#3050ff` to `#487cff`

I can implement a patch on top of this branch to demonstrate how 3. would look like.

@dalf @mrpaulblack what do you think about consistent a _color palette_?

Give me some hints for a discussion .. and I can implement it on top of this branch.

**Comment by mrpaulblack** [comment]
I actually thought @dalf made the logo a lighter blue so the contrast in the dark theme is higher with the dark background... But I am with @return42 on this one. The color theme should be consistent with a blue for links and result article headings and the rest is the consistent blue that return42 described in his comment above. We should either make the logo the same blue as the theme or the blue in the theme the same tone as the original logo that dalf made... Maybe the best option is to make 2 versions of the logo one that matches the blue from light theme and one that matches blue from dark theme.

**Comment by return42** [comment]
One think we should consider: how a logo looks like in the browser (links & history):

**dark**

grafik


**light**

grafik

>  Maybe the best option is to make 2 versions of the logo

If we can, we should avoid two versions of the logo .. at least in the favicon we need one logo that fits for dark & light themes, see above and compare the github logo with the SearXNG magnifier .. IMO the contrast of SearXNG favicon in the dark theme is much better, compared to the gh favicon.

**Comment by dalf** [comment]
I agree to keep a single blue color (logo, links, etc.), to keep consistency.

> 3. in definition.less change `#3050ff` to `#487cff`

I vote this, but I don't know how it looks (icons in the browser, the result page).

**Comment by return42** [comment]
> I vote this, but I don't know how it looks (icons in the browser, the result page).

I tried to harmonize the colors but I think it does not improve the look & feel.

Checkout branch and have a look / I don't have a clue, comments are welcome.

**Comment by dalf** [comment]
No solution, just some screenshots: 

* master branch:
image

* this branch:
image
  The blue color looks bland to me (in this branch)

**Comment by mrpaulblack** [comment]
the blue color for the links is independent from the blue color for the rest of the UI. So the blue color of the logo only needs to match with the blue color of the buttons and so on...

**Comment by dalf** [comment]
A screenshot
image

The light blue of the General category is surrounded by darker colors.

<details>
<summary>Patch for the light version (not the dark one)</summary>

```patch
diff --git a/searx/static/themes/simple/src/less/definitions.less b/searx/static/themes/simple/src/less/definitions.less
index 2bad9000..a9f9f184 100644
--- a/searx/static/themes/simple/src/less/definitions.less
+++ b/searx/static/themes/simple/src/less/definitions.less
@@ -56,10 +56,10 @@
   --color-result-border: #ddd;
   --color-result-url-font: #000;
   --color-result-vim-selected: #f7f7f7;
-  --color-result-vim-arrow: #487cff;
+  --color-result-vim-arrow: #000bbb;
   --color-result-description-highlight-font: #000;
-  --color-result-link-font: #4877ff;
-  --color-result-link-font-highlight: #487cff;
+  --color-result-link-font: #000bbb;
+  --color-result-link-font-highlight: #000bbb;
   --color-result-link-visited-font: #80b;
   --color-result-publishdate-font: #777;
   --color-result-engines-font: #777;
```

</details>

**Comment by return42** [comment]
After trying a few things and a time has passed, I come to the conclusion that we should not change the colors.

**Pull request closed without merging**
