### PR TITLE
[mod] Tools to install and maintain golang binaries & packages.

### LINKED ISSUE #507: Filtron install script always downloads AMD64 binaries even on AArch64 systems.
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
commit 646db5d4f942b4c4da4a62f38b159bd80b7f9db1
**How did you install SearXNG?**
followed the official wiki https://searxng.github.io/searxng/admin/installation.html
**What happened?**
When trying to install filtron, it downloads AMD64 version of Go, so exec format error happens

**How To Reproduce**
Grab an AArch64 server, install Oracle Linux 8.4, and try to follow the guide.

**Expected behavior**
It should've downloaded AArch64 binaries.

**Screenshots & Logs**
```
ERROR: ol-8.4: nginx not yet implemented
ERROR: ol-8.4: apache not yet implemented
ERROR: ol-8.4: uWSGI not yet implemented
ERROR: ol-8.4: pkg_install LXC_BASE_PACKAGES not yet implemented
ERROR: ol-8.4: nginx not yet implemented
ERROR: ol-8.4: apache not yet implemented
ERROR: ol-8.4: uWSGI not yet implemented
ERROR: ol-8.4: pkg_install LXC_BASE_PACKAGES not yet implemented
ERROR: ol-8.4: nginx not yet implemented
ERROR: ol-8.4: apache not yet implemented
ERROR: ol-8.4: uWSGI not yet implemented
ERROR: ol-8.4: pkg_install LXC_BASE_PACKAGES not yet implemented
ERROR: ol-8.4: nginx not yet implemented
ERROR: ol-8.4: apache not yet implemented
ERROR: ol-8.4: uWSGI not yet implemented
ERROR: ol-8.4: pkg_install LXC_BASE_PACKAGES not yet implemented
INFO:  using instance at: /usr/local/searx/searx-src
INFO:  switching to /usr/local/searx/searx-src/.config.sh

=======
filtron
=======

Install filtron (service)
=========================

user filtron
------------

useradd --shell /bin/bash --system  --home-dir "/usr/local/filtron"  --comment 'Reverse HTTP proxy to filter requests' filtron
mkdir "/usr/local/filtron"
chown -R "filtron:filtron" "/usr/local/filtron"
groups filtron
-->|filtron : filtron
export SERVICE_HOME=/usr/local/filtron
Environment /usr/local/filtron/.go_env has been setup.
grep -qFs -- 'source /usr/local/filtron/.go_env' ~/.profile || echo 'source /usr/local/filtron/.go_env' >> ~/.profile
** press any [KEY] to continue **

Install Go in user's HOME
-------------------------

download and install go binary ..
INFO:  caching: https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
INFO:    --> /home/mihatehiura/searx/cache/go1.17.2.linux-amd64.tar.gz
--2021-11-16 11:07:03--  https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
Resolving golang.org (golang.org)... 2404:6800:4004:826::2011, 172.217.175.81
Connecting to golang.org (golang.org)|2404:6800:4004:826::2011|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz [following]
--2021-11-16 11:07:03--  https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 2404:6800:4004:81d::200e, 172.217.175.46
Connecting to dl.google.com (dl.google.com)|2404:6800:4004:81d::200e|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 134803982 (129M) [application/x-gzip]
Saving to: '/home/mihatehiura/searx/cache/go1.17.2.linux-amd64.tar.gz'

/home/mihatehiura/s 100%[===================>] 128.56M  17.2MB/s    in 7.8s

2021-11-16 11:07:12 (16.4 MB/s) - '/home/mihatehiura/searx/cache/go1.17.2.linux-amd64.tar.gz' saved [134803982/134803982]

echo $PATH
  |filtron| /usr/local/filtron/local/go/bin:/usr/local/filtron/go-apps/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
echo $GOPATH
  |filtron| /usr/local/filtron/go-apps
mkdir -p $HOME/local
rm -rf $HOME/local/go
tar -C $HOME/local -xzf /home/mihatehiura/searx/cache/go1.17.2.linux-amd64.tar.gz
-bash: line 2: /usr/local/filtron/local/go/bin/go: cannot execute binary file: Exec format error
** press any [KEY] to continue **

Install filtron in user's ~/go-apps
-----------------------------------

go install -v github.com/asciimoo/filtron@latest
  |filtron| -bash: line 1: /usr/local/filtron/local/go/bin/go: cannot execute binary file: Exec format error

Install filtron rules
=====================

INFO:  install rules /home/mihatehiura/searx/utils/templates/etc/filtron/rules.json
INFO:    --> /etc/filtron/rules.json
** press any [KEY] to continue **

Install System-D Unit filtron
-----------------------------

INFO:  install (eval=1): /lib/systemd/system/filtron.service
INFO:  BUILD /home/mihatehiura/searx/cache/lib/systemd/system/filtron.service
INFO:  BUILD using template /home/mihatehiura/searx/utils/templates/lib/systemd/system/filtron.service
chown: invalid group: 'mihatehiura:mihatehiura'
INFO:  install: /home/mihatehiura/searx/cache/lib/systemd/system/filtron.service
-->|'/home/mihatehiura/searx/cache/lib/systemd/system/filtron.service' -> '/lib/systemd/system/filtron.service'
** press any [KEY] to continue **

Activate filtron (service)
--------------------------

systemctl enable  filtron.service
systemctl restart filtron.service
Created symlink /etc/systemd/system/multi-user.target.wants/filtron.service → /usr/lib/systemd/system/filtron.service.
systemctl status --no-pager filtron.service
● filtron.service - filtron
   Loaded: loaded (/usr/lib/systemd/system/filtron.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-11-16 11:07:37 KST; 17ms ago
 Main PID: 728751 ((filtron))
    Tasks: 1 (limit: 36875)
   Memory: 2.8M
   CGroup: /system.slice/filtron.service
           ‣ 728751 [(filtron)]

Nov 16 11:07:37 oracle-arm systemd[1]: Started filtron.
Nov 16 11:07:37 oracle-arm systemd[1]: filtron.service: Main process exited…EXEC
Nov 16 11:07:37 oracle-arm systemd[1]: filtron.service: Failed with result …de'.
Hint: Some lines were ellipsized, use -l to show in full.
** press any [KEY] to continue **

ERROR: Filtron is not listening on: http://127.0.0.1:4004
INFO:  Apache is installed on this host.

Do you want to install a reverse proxy (ProxyPass) [YES/no] n

Do you want to inspect the installation? [NO/yes] n
```
_Note: that username is not real name, just ~~google~~searx it and you will know where it's from._

**Additional context**
Don't be AMD64 centric and please test these scripts on AArch64 systems from now on.

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

[mod] Tools to install and maintain golang [1] binaries & packages.

[1] https://golang.org/doc/devel/release#policy

## How to test this PR locally?

```
./manage go.help
go.:
  ls        : list golang binary archives (stable)
  golang    : (re-) install golang binary in user's $HOME/local folder
  install   : install go package in user's $HOME/go-apps folder
  bash      : start bash interpreter with golang environment sourced
```

check the results for `os` and `arch`:

    ./manage go.os
    ./manage go.arch

A simple *helloworld* test with user 'my_user' :

    sudo -H adduser my_user
    ./manage go.golang go1.17.3 my_user
    ./manage go.install github.com/go-training/helloworld@latest my_user
    ./manage go.bash my_user
    $ helloword
    Hello World!!

Don't forget to remove 'my_user':  

    sudo -H deluser --remove-home my_user

If test above success try to [install](https://searxng.github.io/searxng/admin/installation.html) filtron and morty:

    sudo -H ./utils/filtron.sh install all
    sudo -H ./utils/morty.sh install all

## Author's checklist

I need some tester for the various `os` and `arch` (see above)

## Related issues

Closes: https://github.com/searxng/searxng/issues/507
Related: https://github.com/searxng/searxng/issues/53

### CODE REVIEW

**Comment by mrpaulblack** [comment]
The installation works on my amd64 workstation but fails on my raspberry pi 4 running raspbian lite:

```
pi@wlan:~/searxng $ ./manage go.golang
ERROR: raspbian-10: nginx not yet implemented
ERROR: raspbian-10: apache not yet implemented
ERROR: raspbian-10: uWSGI not yet implemented
ERROR: raspbian-10: pkg_install LXC_BASE_PACKAGES not yet implemented

Install Go in 's HOME
---------------------
INFO:  Download go binary go1.17.3.linux-armv6l.tar.gz (99MB)
INFO:  already cached: https://golang.org/dl/go1.17.3.linux-armv6l.tar.gz
INFO:    --> /home/pi/searxng/cache/go1.17.3.linux-armv6l.tar.gz
INFO:  go1.17.3.linux-armv6l.tar.gz checksum OK
INFO:  install golang
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value]
            [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
mkdir -p $HOME/local
INFO:  test golang installation
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value]
            [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
```

(The same command worked on my workstation)

[EDIT] `go.arch` returned: `armv6l`

[EDIT2] also this is just because I dont have those packages installed:

```
ERROR: raspbian-10: nginx not yet implemented
ERROR: raspbian-10: apache not yet implemented
ERROR: raspbian-10: uWSGI not yet implemented
```

**Comment by return42** [comment]
> The installation works on my amd64 workstation but fails on my raspberry pi 4 running raspbian lite:

Thanks for giving it a try .. some words about:

**First** 

raspbian, the [Raspberry Pi OS ](https://www.raspberrypi.com/software/operating-systems/) is special.  The installation scripts we have do not support this distribution. In the [installation instructions](https://searxng.github.io/searxng/admin/installation-searx.html#installation-basic) you can see what OS we support.

grafik

This is also the reason why you are seeing error messages like:

```
pi@wlan:~/searxng $ ./manage go.golang
ERROR: raspbian-10: nginx not yet implemented
ERROR: raspbian-10: apache not yet implemented
ERROR: raspbian-10: uWSGI not yet implemented
ERROR: raspbian-10: pkg_install LXC_BASE_PACKAGES not yet implemented
```

>  also this is just because I dont have those packages installed:

No, this is not the problem, usual these packages would be installed by our installation scripts when they are needed. 

The problem is, that our installation scripts do not have an implementation to install packages on such a OS, this is what the ERROR message says.

It is the same on my pi where I have an OS that is not supported by our scripts:

```bash
pi@pi:~ $ cat /etc/issue
Raspbian GNU/Linux 9 \n \l
```

**Second** 

is the architecture one of the OS shown in the screenshot above, is running on.

This patch does not extend the list of OS distributions we support, this PR only offers a wider range of architectures.

Assume you have a _normal_ debian distribution installed on you pi, then you can now install a SearXNG suite (including filtron & morty / both need a go installation) with our scripts.

> `go.arch` returned: `armv6l`

```bash
go.arch() {
    local ARCH
    case "$(command uname -m)" in
        "x86_64") ARCH=amd64 ;;
        "aarch64") ARCH=arm64 ;;
        "armv6" | "armv7l") ARCH=armv6l ;;
        "armv8") ARCH=arm64 ;;
        .*386.*) ARCH=386 ;;
        ppc64*) ARCH=ppc64le ;;
    *)  die 42 "ARCH is unknown: $(command uname -m)" ;;
    esac
    echo "${ARCH}"
}
```

It is the same on my pi where I have an `armv7l` (RISC):

```bash
pi@pi:~ $ uname -a
Linux pi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

To sum up .. don't try to install SearXNG by our scripts, this won't work.

One test you can do, to see if the right go binary is installed, please try ...

    $ ./manage go.golang go1.17.3

this should install golang in your `~/local/go` folder, just ignore the ..

    ERROR: raspbian-10: ???? not yet implemented

messages. Are there any other issues you see?  If succeeded you should see something like:

    INFO:  test golang installation
    /home/<user>/local/go/bin/go
    go version go1.17.3 linux/????
 
This means the golang installation is OK.

After you can try to install a go hello-world example ..

    $ ./manage go.install github.com/go-training/helloworld@latest

Any error messages? (except the ones I mentioned above)

If the installation of the helloworld example succeeded, try to run this small program. For this you need an environment (PATH) where all the golang infrastructure is included.  This is exactly the way, the filtron and morty installations are settled up.

For this environment just start a bash by ...

    $ ./manage go.bash

In the prompt you get type ...

    $ helloworld 
    Hello World!!

Does it work on your pi?

**Comment by mrpaulblack** [comment]
So installing SearXNG on raspbian not supported... got it. But is the `./manage go.golang` command supposed to work on raspbian. Because if so than the error log from my comment before still holds up (basically something with the sudo binary on raspbian not supporting the arguments you provided with the script maybe!?)

[EDIT] the golang hello world and env is working on my amd64 linux workstation perfectly tho :+1: 

```
pi@wlan:~/searxng $ ./manage go.golang go1.17.3
ERROR: raspbian-10: nginx not yet implemented
ERROR: raspbian-10: apache not yet implemented
ERROR: raspbian-10: uWSGI not yet implemented
ERROR: raspbian-10: pkg_install LXC_BASE_PACKAGES not yet implemented

Install Go in 's HOME
---------------------
INFO:  Download go binary go1.17.3.linux-armv6l.tar.gz (99MB)
INFO:  already cached: https://golang.org/dl/go1.17.3.linux-armv6l.tar.gz
INFO:    --> /home/pi/searxng/cache/go1.17.3.linux-armv6l.tar.gz
INFO:  go1.17.3.linux-armv6l.tar.gz checksum OK
INFO:  install golang
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value]
            [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
mkdir -p $HOME/local
INFO:  test golang installation
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value]
            [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...
```

**Comment by return42** [comment]
> [EDIT] the golang hello world and env is working on my amd64 linux workstation perfectly tho +1

Thanks!!! this is all I need to know :) .. all the other errors are related to sudo / the rasp-OS

For this patch to test we need only install once a golang binary .. if this works, all other will work on the OS distros we support (these routines are tested on amd64).

I'am goning to merge this PR ...

**Pull request merged**
