### PR TITLE
[simple theme] various improvements

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

various "simple theme" improvements

-----

[simple theme] CSS remove box-shadow effects / e.g.:

before ..

grafik

after ..

grafik

----

[simple theme] unification of .results table (`@phone` & `@small-phone`)

before ...

grafik

after ..

grafik

-----

[simple theme] simplify and justify #answers & #corrections

before ...

grafik

after ...

grafik

-----

[simple theme] add .rounded-corners to selectable_url

before ...

grafik

after ..

grafik

### CODE REVIEW

**Comment by mrpaulblack** [comment]
I am working on a review right now; pls do not merge yet; ty

**Comment by return42** [comment]
> pls do not merge yet; 

I will wait about feedback .. some layout changes are arguable ..  thanks for review & comments!

**Review by mrpaulblack — CHANGES_REQUESTED** [review]
First of all thank you for the PR. Everything LGTM, except the following:

* I would like to not close #458, because I still think this is valid and needs to be addressed to make the theme more uniform

* makes the contrast on the light theme checkbox toggle higher

* basically I like your idea with unifing the result theme, but I do not think its a good idea in practice tho: different content needs different kinds of how it is displayed; so as a compromise:  I would like to keep the layout from before this PR for the general, it and science categories. The videos, news, map, music, files and social media categorie use the same layout as phone on tablet and desktop.

* I also suggest making the select ui on phone with a 1px border and some other minor changes -> see comment below

**Comment by mrpaulblack** [comment]
[EDIT] @return42  I suggest the following changes (sry dont know how to format this better...):

```diff
--- a/searx/static/themes/simple/src/less/definitions.less
+++ b/searx/static/themes/simple/src/less/definitions.less
@@ -93,7 +93,7 @@
   --color-toolkit-select-border-hover: #bbb;
   --color-toolkit-checkbox-onoff-background: #ddd;
   --color-toolkit-checkbox-onoff-label-background: #3050ff;
-  --color-toolkit-checkbox-onoff-checked-background: #ddd;
+  --color-toolkit-checkbox-onoff-checked-background: #aaa;
   --color-toolkit-checkbox-label-background: #fff;
   --color-toolkit-checkbox-label-border: #ddd;
   --color-toolkit-checkbox-input-border: #3050ff;
   ```

```diff
--- a/searx/static/themes/simple/src/less/style.less
+++ b/searx/static/themes/simple/src/less/style.less
@@ -140,11 +140,20 @@ article.result-images[data-vim-selected] {
   }
 }
 
+article[data-vim-selected].category-videos,
+article[data-vim-selected].category-news,
+article[data-vim-selected].category-map,
+article[data-vim-selected].category-music,
+article[data-vim-selected].category-files,
+article[data-vim-selected].category-social {
+  border: 1px solid var(--color-result-vim-arrow);
+  .rounded-corners;
+}
+
 .result {
-  margin: 1rem @results-tablet-offset;
+  margin: @results-margin 0;
   padding: @result-padding;
-  border: 1px solid var(--color-result-border);
-  .rounded-corners;
+  border-left: 0.2rem solid transparent;
 
   h3 {
     font-size: 1.1em;
@@ -238,6 +247,17 @@ article.result-images[data-vim-selected] {
   }
 }
 
+.category-videos,
+.category-news,
+.category-map,
+.category-music,
+.category-files,
+.category-social {
+  border: 1px solid var(--color-result-border);
+  margin: 1rem 0;
+  .rounded-corners;
+}
+
 .category-social .image {
   width: auto !important;
   min-width: 48px;
@@ -274,7 +294,7 @@ article.result-images[data-vim-selected] {
   padding: 0;
   position: relative;
   max-height: 200px;
-  border: none;
+  border: none !important;
 
   img {
     float: inherit;
@@ -700,7 +720,7 @@ article.result-images[data-vim-selected] {
 @media screen and (max-width: @phone) {
   #main_results div#results {
     grid-template-columns: 100%;
-    margin: 2rem 0 0 0;
+    margin: 2rem @results-tablet-offset 0 @results-tablet-offset;
   }
 
   #linkto_preferences {
@@ -710,10 +730,6 @@ article.result-images[data-vim-selected] {
     right: 0;
   }
 
-  #sidebar {
-    margin: 0 5px 2px 5px;
-  }
-
   #results {
     margin: 0;
     padding: 0;
@@ -723,6 +739,17 @@ article.result-images[data-vim-selected] {
     margin: 2rem 1rem 0 1rem !important;
   }
 
+  article[data-vim-selected] {
+    border: 1px solid var(--color-result-vim-arrow);
+    border: 1px solid var(--color-result-vim-arrow);
+    .rounded-corners;
+  }
+
+  .result {
+    border: 1px solid var(--color-result-border);
+    margin: 1rem 0;
+    .rounded-corners;
+  }
+
   .result-images {
     margin: 0;
     padding: 0;
```

**Comment by return42** [comment]
> sry dont know how to format this better...

For easiness; If you have the changes local, you can create a commit and push it to a (new) branch on your `github.com:MrPaulBlack/searxng` from where I can pull it ..

**Comment by mrpaulblack** [comment]
Alright there you go: https://github.com/MrPaulBlack/searxng/commit/26806fcf0f88ce9c6dc3f1785f2d057de277b084 (also sry for the comment spam...)

**Comment by return42** [comment]
> I would like to not close #458, because I still think this is valid and needs to be addressed to make the theme more uniform

OK I understand .. "closes" has been removed.

> makes the contrast on the light theme checkbox toggle higher

good point, thanks for your patch

> but I do not think its a good idea in practice 

I tooked over your patch ..  and removed my `[simple theme] unification of .results table (@phone & @small-phone)` shown in the _before/after_ images above in https://github.com/searxng/searxng/pull/474#issue-1043917621. But one question I have: why do you think should have each result a box (border) on phone devices but not on desktop? 

> also sry for the comment spam...

I can't see any spam :) ... I appreciate your work very much / thanks a lot for your review & patch!  
I reordered and rebased the patches to have your e05bcd43 instead of mine 4e760c9 / I hope this is OK for you .. ?

**Comment by mrpaulblack** [comment]
Everything LGTM :+1:  and about the usage of border in the result article: I think the border on phone helps to distinguished better between the articles and to make the UI cleaner looking. This also helps on desktop and tablet as well tho I prefer the "classic" look without a border (Also the margin is smaller so more content in the same space I guess...).

**Pull request merged**
