### PR TITLE
[fix] search.less: settings icon invisible on mobile devices

### LINKED ISSUE #2836: [Bug] Search box not in center in mobile view.
**Version of SearXNG** 2023.9.22+71358e9c6

**How To Reproduce**

Just open it on your phone.

**Screenshots & Logs**

**Additional context**
1. Find out which PR cause this.
2. solve it.

### PR DESCRIPTION
**Pull request by BernieHuang2008**
## What does this PR do?
just a quick fix of #2836 .

i've changed the css selector: the new style in https://github.com/searxng/searxng/commit/a76c8e4101dceb68cf7d846868e5e50e54461b08 will only be activated when in result page.

## What's different with #2833
this PR is a sort of merge of #2742 and #2833. 

These changes are made by #2742 👇 but #2833 have just removed it. 
image

With this PR, the feature will be still exist but also solve the home-page problem like #2833 does.

ping @Bnyro, have a review please.

## Related issues
Closes #2836 
This is the reopen of PR #2838

### CODE REVIEW

**Comment by Bnyro** [comment]
I think we should also remove https://github.com/searxng/searxng/pull/2846/files#diff-4f244eec7a4a314e8d7e0f7d65ea91ba85afdf13035e202b8aaf9f27a1397dfbR236-R238 by that? Since that's no longer necessary then.

**Comment by BernieHuang2008** [comment]
> I think we should also remove https://github.com/searxng/searxng/pull/2846/files#diff-4f244eec7a4a314e8d7e0f7d65ea91ba85afdf13035e202b8aaf9f27a1397dfbR236-R238 by that? Since that's no longer necessary then.

Oh ye, tablet can also use the same styleshheet.

**Comment by BernieHuang2008** [comment]
i've deleted the code mentioned above, have a look now!

**Review by Bnyro — APPROVED** [review]
LGTM!

**Comment by Bnyro** [comment]
If you know how to, please rebase the PR instead of merging the master branch into it, to keep the commit history clean (i.e. remove the [Merge branch 'searxng:master' into fix-2836](https://github.com/searxng/searxng/pull/2846/commits/c897994a276903bd71720ee1ed3bd99d93cd348a) commit).

**Comment by Bnyro** [comment]
And please change the commit message for the first commit (which is currently `quick solve of ...`) and the title of this pull request to `[fix] search.less: settings icon invisible on mobile devices`

**Comment by BernieHuang2008** [comment]
@return42 I think it's ready.

**Comment by return42** [comment]
> @return42 I think it's ready.

I would say "its perfect" :)

----

 .. just fixed a typo in the commit message:

- ``[fix] settings icon invisiale on mobile devices``
- ``[fix] settings icon invisible on mobile devices``

**Pull request merged**
