### PR TITLE
Bump Alpine 3.18 (Python 3.11)

### PR DESCRIPTION
**Pull request by nberlee**
## What does this PR do?
Updates Alpine to 3.18

## Why is this change important?
The releasenotes of Alpine state it bumps Python 3.11

## How to test this PR locally?
crosscompiled it for arm64, uploaded it to dockerhub (nberlee/searxng:python311) and used it in my k8s cluster

### CODE REVIEW

**Comment by return42** [comment]
@dalf if you have time left, could have a look at this PR / thanks!

**Comment by dalf** [comment]
I use Python 3.11 since the first release without issue, so I think the PR is okay.

However, when I use `make docker.buildx`, for some reason I have an error with linux/arm/v7 and Alpine 3.17 or 3.18.
It seems related to https://github.com/pypa/pip/issues/11435

```
#0 32.81 subprocess.CalledProcessError: Command '('uname', '-rs')' returned non-zero exit status 1.
#0 32.83 Traceback (most recent call last):
#0 32.83   File "/usr/bin/pip3", line 33, in <module>
#0 32.83     sys.exit(load_entry_point('pip==22.3.1', 'console_scripts', 'pip3')())
#0 32.83   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 70, in main
#0 32.83     return command.main(cmd_args)
#0 32.83   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 101, in main
#0 32.83     return self._main(args)
#0 32.83   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
#0 32.84     self.handle_pip_version_check(options)
#0 32.84   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 179, in handle_pip_version_check
#0 32.84     session = self._build_session(
#0 32.84   File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
#0 32.84     session = PipSession(
#0 32.84   File "/usr/lib/python3.10/site-packages/pip/_internal/network/session.py", line 343, in __init__
#0 32.84     self.headers["User-Agent"] = user_agent()
#0 32.84   File "/usr/lib/python3.10/site-packages/pip/_internal/network/session.py", line 140, in user_agent
#0 32.84     linux_distribution = distro.name(), distro.version(), distro.codename()
#0 32.84   File "/usr/lib/python3.10/site-packages/pip/_vendor/distro/distro.py", line 345, in version
#0 32.84     return _distro.version(pretty, best)
#0 32.84   File "/usr/lib/python3.10/site-packages/pip/_vendor/distro/distro.py", line 874, in version
#0 32.85     self.uname_attr("release"),
#0 32.85   File "/usr/lib/python3.10/site-packages/pip/_vendor/distro/distro.py", line 1059, in uname_attr
#0 32.85     return self._uname_info.get(attribute, "")
#0 32.85   File "/usr/lib/python3.10/functools.py", line 981, in __get__
#0 32.85     val = self.func(instance)
#0 32.85   File "/usr/lib/python3.10/site-packages/pip/_vendor/distro/distro.py", line 1173, in _uname_info
#0 32.86     stdout = subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
#0 32.86   File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
#0 32.86     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#0 32.86   File "/usr/lib/python3.10/subprocess.py", line 526, in run
#0 32.86     raise CalledProcessError(retcode, process.args,
#0 32.86 subprocess.CalledProcessError: Command '('uname', '-rs')' returned non-zero exit status 1.
```

**Comment by nberlee** [comment]
@dalf I cannot replicate it.

`make docker.buildx` takes a very long time for arm/v7, but it finishes successfull: https://hub.docker.com/layers/nberlee/searxng/2023.5.10-fe0cce2a/images/sha256-ea4510d4fe5aa06aaed1fa76f6f07389f60525bbaa12d8d27c26d14ca4a4b609?context=repo

using:
github.com/docker/buildx 0.10.4 c513d34049e499c53468deac6c4267ee72948f02
QEMU emulator version 8.0.0

**Comment by dalf** [comment]
Ok, if the PR is merged, the worst case scenario is the docker image is not updated : we can roll back without issue.

So @return42 I think we can merge.

**Pull request merged**
