### PR TITLE
[simple theme] add icons to category and drop webfont

### PR DESCRIPTION
**Pull request by mrpaulblack**
## What does this PR do?

Add icons to the categories in the search form of the result template.

* add globe-outline as default
* add custom icons to the default categories
* change the padding and margin on the category label
* update from ionicons-npm to ionicons ver.5
* drop the webfont built by grunt for icons
* built icons.html template for inlining icons with jinja2 into html
* update icon to use mostly the outline version
* add icons to categories and do not display them on mobile to save space
* remove all legacy ion icon font files from simple theme
* icons.html is added in this commit since make statc.build.restore requires git to know the file already
* cleanup error-dialog

This PR removes the custom webfont that gets build with the defined icons. Instead of serving a webfont the selected icons are now built into the icons.html jinja2 template file and inlined into the html with macros. This way we do not need to serve a webfont and save requests for each icon by serving it through the html. It also only serves the needed icons in the html this way...

Also the license changes with the ionicon npm package for the package to MIT

## Why is this change important?

Polish for the simple theme and design parity with other search engines.

## How to test this PR locally?

```make themes.simple```
```make run```

(now also builds icons.html so change gruntfile.js for removing and adding icons and than `make static.build.commit`)

## Author's checklist

Desktop:
image

(Tablet pretty much looks like desktop)

Mobile:
image

## Related issues

I think this PR closes: #248

### CODE REVIEW

**Comment by dalf** [comment]
>  Is it feasible to switch 3 major versions to ion5?

* Upgrade the version https://github.com/searxng/searxng/blob/90acb342d32b1ce890402acbc24cc9a5793fddc6/searx/static/themes/simple/package.json#L15 ( the new package seems to be [ionicons](https://www.npmjs.com/package/ionicons) )
* `npm install`
* update `gruntfile.js` (the path seems to be `node_modules/ionicons-npm/src/svg/`) : https://github.com/searxng/searxng/blob/90acb342d32b1ce890402acbc24cc9a5793fddc6/searx/static/themes/simple/gruntfile.js#L102-L124
* install these two distro packages: `ttfautohint` and `fontforge`.
* `npm run webfont`,  /!\ it replaces the content of `fonts/ion.css`.

**Comment by return42** [comment]
LGTM, except some icons are broken, e.g. magnifier, music and others .. 

grafik

**Comment by mrpaulblack** [comment]
Yeah I am actually not sure why this is happening. Its probably when building the font from the svgs... but idk; need to try around a bit more first...

**Comment by dalf** [comment]
Without success, I've tried to upgrade the grunt-webfont dependencies in a fork: https://github.com/dalf/grunt-webfont/blob/master/package.json (in packages.json, instead of a version number it is possible to provide a GIT URL).

It's been a while, but may this problem already existed with some icons of ion version 2.

Possible workaround: rely only a background SVG
* keep ionicons as npm dependency
* remove grunt-webfont dependency
* create ion.less using a less:
  * a mixin to define common properties
  * use [data-uri()](https://lesscss.org/functions/#misc-functions-data-uri) to embed the SVG in ion.less

Already use case of data-uri:
https://github.com/searxng/searxng/blob/90acb342d32b1ce890402acbc24cc9a5793fddc6/searx/static/themes/simple/src/less/toolkit.less#L347

---

A more complex alternative: create a ion.html, a set of jinja2 macros with the content of the SVG (for example, icons of GitHub are inlined SVG).

**Comment by return42** [comment]
I don't know, but it might be related to the https://github.com/searxng/searxng/pull/488#issuecomment-963606592 ...

ATM we have an issue reported when `make node.clean node.env` is build:

    npm WARN deprecated svgo@0.6.6: This SVGO version is no longer supported. Upgrade to v2.x.x.

Hint: https://github.com/sapegin/grunt-webfont is not maintained since years, see archived repository at https://github.com/sapegin/grunt-webfont and we have other issues with, see  https://github.com/searxng/searxng/pull/248#issuecomment-894672328

Related: https://github.com/searxng/searxng/pull/473#discussion_r745424674

**Comment by dalf** [comment]
I've tried to upgrade the svgo version:
https://github.com/dalf/grunt-webfont/blob/4619280c92e1085110da8ee3fada1be84a48451e/package.json#L39

To use:
https://github.com/searxng/searxng/blob/90acb342d32b1ce890402acbc24cc9a5793fddc6/searx/static/themes/simple/package.json#L14
replace 
`^1.7.2` by `https://github.com/dalf/grunt-webfont`

It didn't helped: some icons are still broken (may be I have tested too quickly).

**Comment by return42** [comment]
@dalf: I haven't tested, but do you have seen https://github.com/lehni/grunt-webfont/commit/9afc00886fb608eebabd3dc995624160f6d6f1ba / it is branch master from fork https://github.com/lehni/grunt-webfont

**Comment by return42** [comment]
@MrPaulBlack I pushed two commits on top .. these are coming from my tests (drop them if you want).

I tested  https://github.com/lehni/grunt-webfont in 5db0832 .. but it does not helped ..

Here is a screenshot of the `ion.woff` font ..

grafik

and here is the `ion.ttf` font ..

grafik

What me wonders .. one has 19 glyphs , the other 21.

IMO this grunt-webfont tool produce crap .. why not just using the svg files we need or lets use a icon-font that is ready to use.  Do we really need to build our own font? Alternatively we can use https://github.com/ionic-team/ionicons/tree/main/docs/fonts

**Comment by mrpaulblack** [comment]
Yeah sorry that I did not answer faster. I was really busy... I am going to drop grunt-webfont and add the svg files inline into the html. I am not a big fan of inlining them into the css, since its going to load all icons with the searxng.css file. When inlining them with jinja2 into the html its only going to add only the needed icons... I think that is a better solution than trying to get a webfont working tbh... So yeah I agree with return42 webfont seems overkill here.... (and it seems hard to maintain because of all the build deps)

[EDIT] I am really busy at the moment, so the PR is going to take a bit longer sry...

**Comment by return42** [comment]
> I am really busy at the moment, so the PR is going to take a bit longer sry...

All is well ... don't be rushed :)

**Comment by dalf** [comment]
In this [gist](https://gist.github.com/dalf/504cc61047369df159d8e031dbcd652c), gruntfile.js creates `searx/templates/simple/icons.html` with this content:

```jinja
{%- set icons = {
        'error':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Alert Circle</title><path d="M256 48C141.31 48 48 141.31 48 256s93.31 208 208 208 208-93.31 208-208S370.69 48 256 48zm0 319.91a20 20 0 1120-20 20 20 0 01-20 20zm21.72-201.15l-5.74 122a16 16 0 01-32 0l-5.74-121.94v-.05a21.74 21.74 0 1143.44 0z"/></svg>',
        'warning':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Alert Circle</title><path d="M448 256c0-106-86-192-192-192S64 150 64 256s86 192 192 192 192-86 192-192z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><path d="M250.26 166.05L256 288l5.73-121.95a5.74 5.74 0 00-5.79-6h0a5.74 5.74 0 00-5.68 6z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/><path d="M256 367.91a20 20 0 1120-20 20 20 0 01-20 20z"/></svg>',
        'close-outline':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Close</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M368 368L144 144M368 144L144 368"/></svg>',
        'chevron-up':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Chevron Up</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M112 328l144-144 144 144"/></svg>',
        'menu':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Menu</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M80 160h352M80 256h352M80 352h352"/></svg>',
        'ellipsis-vertical':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Ellipsis Vertical</title><circle cx="256" cy="256" r="32" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><circle cx="256" cy="416" r="32" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><circle cx="256" cy="96" r="32" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/></svg>',
        'magnet':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Magnet</title><path d="M421.83 293.82A144 144 0 00218.18 90.17M353.94 225.94a48 48 0 00-67.88-67.88" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M192 464v-48M90.18 421.82l33.94-33.94M48 320h48"/><path d="M286.06 158.06L172.92 271.19a32 32 0 01-45.25 0L105 248.57a32 32 0 010-45.26L218.18 90.17M421.83 293.82L308.69 407a32 32 0 01-45.26 0l-22.62-22.63a32 32 0 010-45.26l113.13-113.17M139.6 169.98l67.88 67.89M275.36 305.75l67.89 67.88" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32"/></svg>',
        'globe':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Globe</title><path d="M256 48C141.13 48 48 141.13 48 256s93.13 208 208 208 208-93.13 208-208S370.87 48 256 48z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><path d="M256 48c-58.07 0-112.67 93.13-112.67 208S197.93 464 256 464s112.67-93.13 112.67-208S314.07 48 256 48z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><path d="M117.33 117.33c38.24 27.15 86.38 43.34 138.67 43.34s100.43-16.19 138.67-43.34M394.67 394.67c-38.24-27.15-86.38-43.34-138.67-43.34s-100.43 16.19-138.67 43.34" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/><path fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32" d="M256 48v416M464 256H48"/></svg>',
        'search-outline':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Search</title><path d="M221.09 64a157.09 157.09 0 10157.09 157.09A157.1 157.1 0 00221.09 64z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32" d="M338.29 338.29L448 448"/></svg>',
        'image':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Image</title><rect x="48" y="80" width="416" height="352" rx="48" ry="48" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32"/><circle cx="336" cy="176" r="32" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><path d="M304 335.79l-90.66-90.49a32 32 0 00-43.87-1.3L48 352M224 432l123.34-123.34a32 32 0 0143.11-2L464 368" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/></svg>',
        'play':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Play</title><path d="M112 111v290c0 17.44 17 28.52 31 20.16l247.9-148.37c12.12-7.25 12.12-26.33 0-33.58L143 90.84c-14-8.36-31 2.72-31 20.16z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/></svg>',
        'newspaper':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Newspaper</title><path d="M368 415.86V72a24.07 24.07 0 00-24-24H72a24.07 24.07 0 00-24 24v352a40.12 40.12 0 0040 40h328" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32"/><path d="M416 464h0a48 48 0 01-48-48V128h72a24 24 0 0124 24v264a48 48 0 01-48 48z" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32"/><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M240 128h64M240 192h64M112 256h192M112 320h192M112 384h192"/><path d="M176 208h-64a16 16 0 01-16-16v-64a16 16 0 0116-16h64a16 16 0 0116 16v64a16 16 0 01-16 16z"/></svg>',
        'location':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Location</title><path d="M256 48c-79.5 0-144 61.39-144 137 0 87 96 224.87 131.25 272.49a15.77 15.77 0 0025.5 0C304 409.89 400 272.07 400 185c0-75.61-64.5-137-144-137z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/><circle cx="256" cy="192" r="48" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/></svg>',
        'musical-notes':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Musical Notes</title><path d="M192 218v-6c0-14.84 10-27 24.24-30.59l174.59-46.68A20 20 0 01416 154v22" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/><path d="M416 295.94v80c0 13.91-8.93 25.59-22 30l-22 8c-25.9 8.72-52-10.42-52-38h0a33.37 33.37 0 0123-32l51-18.15c13.07-4.4 22-15.94 22-29.85V58a10 10 0 00-12.6-9.61L204 102a16.48 16.48 0 00-12 16v226c0 13.91-8.93 25.6-22 30l-52 18c-13.88 4.68-22 17.22-22 32h0c0 27.58 26.52 46.55 52 38l22-8c13.07-4.4 22-16.08 22-30v-80" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/></svg>',
        'layers':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>Layers</title><path d="M434.8 137.65l-149.36-68.1c-16.19-7.4-42.69-7.4-58.88 0L77.3 137.65c-17.6 8-17.6 21.09 0 29.09l148 67.5c16.89 7.7 44.69 7.7 61.58 0l148-67.5c17.52-8 17.52-21.1-.08-29.09zM160 308.52l-82.7 37.11c-17.6 8-17.6 21.1 0 29.1l148 67.5c16.89 7.69 44.69 7.69 61.58 0l148-67.5c17.6-8 17.6-21.1 0-29.1l-79.94-38.47" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/><path d="M160 204.48l-82.8 37.16c-17.6 8-17.6 21.1 0 29.1l148 67.49c16.89 7.7 44.69 7.7 61.58 0l148-67.49c17.7-8 17.7-21.1.1-29.1L352 204.48" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/></svg>',
        'school':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>School</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M32 192L256 64l224 128-224 128L32 192z"/><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M112 240v128l144 80 144-80V240M480 368V192M256 320v128"/></svg>',
        'file-tray-full':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>File Tray Full</title><path d="M384 80H128c-26 0-43 14-48 40L48 272v112a48.14 48.14 0 0048 48h320a48.14 48.14 0 0048-48V272l-32-152c-5-27-23-40-48-40z" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="32"/><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32" d="M48 272h144M320 272h144M192 272a64 64 0 00128 0M144 144h224M128 208h256"/></svg>',
        'people':'<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512"><title>People</title><path d="M402 168c-2.93 40.67-33.1 72-66 72s-63.12-31.32-66-72c-3-42.31 26.37-72 66-72s69 30.46 66 72z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/><path d="M336 304c-65.17 0-127.84 32.37-143.54 95.41-2.08 8.34 3.15 16.59 11.72 16.59h263.65c8.57 0 13.77-8.25 11.72-16.59C463.85 335.36 401.18 304 336 304z" fill="none" stroke="currentColor" stroke-miterlimit="10" stroke-width="32"/><path d="M200 185.94c-2.34 32.48-26.72 58.06-53 58.06s-50.7-25.57-53-58.06C91.61 152.15 115.34 128 147 128s55.39 24.77 53 57.94z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="32"/><path d="M206 306c-18.05-8.27-37.93-11.45-59-11.45-52 0-102.1 25.85-114.65 76.2-1.65 6.66 2.53 13.25 9.37 13.25H154" fill="none" stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="32"/></svg>',
      
      } 
      -%}
      
      {% macro icon(action, alt) -%}
          <span class="ion-icon-big ion-{{ action }}" title="{{ alt }}">{{ icons[action] | safe }}</span>
      {%- endmacro %}
      
      {% macro icon_small(action) -%}
          <span class="ion-icon ion-{{ action }}" title="{{ alt }}">{{ icons[action] | safe }}</span>
      {%- endmacro %}
```

Some SVG icons takes the whole HTML page (like the search icon), but that's another issue.

**Comment by dalf** [comment]
I've just updated gruntfile.js: the src keys were not the right one.

**Comment by dalf** [comment]
The full change in this commit: https://github.com/dalf/searxng/commit/c0b25d9201224ffb634a1e54e64f539eb7ea4381 (it requires some clean up, the icon on the categories are not implemented, ...).

In this implementation, each icon is a svg inside a span: I think we can remove the span element.

Feel free to cherry-pick / copy / paste.

On Friday, I will have more time.

**Comment by mrpaulblack** [comment]
Welp that is everything being gone! I accidentally forced pushed from another branch on this one! -_- Going to rewrite (with cherry picking dalfs commit) in the next few days

**Comment by dalf** [comment]
https://stackoverflow.com/questions/12568628/how-to-recover-from-a-git-push-force

Does something like that can help ? (caution,.... not tested...)
```
# reset to the previous state of origin/master, as recorded by reflog
git reset --hard origin/master@{1}
```
(for your local branch obviously).

**Comment by return42** [comment]
AFAIK you can get the branch back by looking in the reflog, may be this link can help  https://riptutorial.com/git/example/2446/recover-a-deleted-branch

**Comment by mrpaulblack** [comment]
Thanks for the quick help! I was literally feeling this emotion right after I force pushed and the files in the other PR did not change and I saw the branch I force pushed in: https://www.youtube.com/watch?v=X6NJkWbM1xk . I can def. restore the files with git reset and git reflog! :D so yeah Thanks!

[EDIT] so yeah to recover for future desasters:
```git reflog``` -> select commit of the PR
```git reset --hard commit_hash```
```git push origin -f```

**Comment by return42** [comment]
> I can def. restore the files with git reset and git reflog! :D so yeah Thanks!

Good to know .. anyway I pushed my local clone of your branch to https://github.com/return42/searxng/tree/category-icons

I remember Linus Torvalds joked: _If you want to backup something without having a storage, place it in a repository and push it on a public host, even if the host dies there will always exist a clone somewhere._ :-)

**Comment by return42** [comment]
BTW: there exists always a link to the commit here in the PR log (see above) ... 

grafik

**Comment by dalf** [comment]
See https://github.com/dalf/searxng/commit/24ce2f92998db92f6db4a3b8390b94645243d030 
To cherry-pick / copy / paste / whatever

image

image

icons.html is not included since it is built by the theme. The content:
```jinja
{# this file was generated by searx/static/themes/simple/gruntfile.js #}
{%- set icons = {
  'error':'<svg class="ionicon" viewBox="0 0 512 512" aria-hidden="true"><path d="M256 48C141.31 48 48 141.31 48 256s93.31 208 208 208 208-93.31 208-208S370.69 48 256 48zm0 319.91a20 20 0 1120-20 20 20 0 01-20 20zm21.72-201.15l-5.74 122a16 16 0 01-32 0l-5.74-121.94v-.05a21.74 21.74 0 1143.44 0z"/></svg>',
...
} 
-%}
      
{% macro icon(action, alt) -%}
  {{ icons[action] | replace("ionicon", "ion-icon-big") | safe }}
{%- endmacro %}
      
{% macro icon_small(action) -%}
  {{ icons[action] | replace("ionicon", "ion-icon") | safe }}
{%- endmacro %}
```

**Comment by mrpaulblack** [comment]
Alright I cleaned up the commit from dalf and added some small fixes. Thanks you @dalf and @return42 for the suggestions,fixes and especially with the grunt and jinja2 changes!

**Review by dalf — APPROVED** [review]
Excellent

**Comment by return42** [comment]
Pretty cool work .. sorry for my temporary absent .. now I had some time to test, see https://github.com/searxng/searxng/issues/498

**Pull request merged**
