### PR TITLE
Preferences Icon Update

### PR DESCRIPTION
**Pull request by MontyQI**
## What does this PR do?

Changes preferences icon to 
settings
## Why is this change important?

This icon will be better associated with settings that previous one.

## How to test this PR locally?

`make run`
change theme to simple

### CODE REVIEW

**Review by return42 — APPROVED** [review]
Thanks for your PR! Other search engines use the hamburger menu, but I also like the gear icon you suggest and like you, I think the association of a gear with a setting is more obvious.

I approve this PR but I won't judge what is better, lets hear what other say ...

**Comment by tiekoetter** [comment]
I personally think the gear icon looks better.

**Review by mrpaulblack — CHANGES_REQUESTED** [review]
Thanks for the PR. I also like the gear icon more. But please change your commits:

* one commit with the correct icon set from `node_modules/ionicons/dist/svg` in gruntfile (you can replace the current one): https://github.com/searxng/searxng/blob/f3d4b25e739164ea6af087379536b3ef3538d63c/searx/static/themes/simple/gruntfile.js#L180
* one commit with the build theme; for that just run `make static.build.commit` which will auto create the commit :+1: 

[EDIT] you can do this by using `git reset --hard` than making your changes and force pushing those changes on this branch to override this already existing commit with `git push origin -f`

**Comment by return42** [comment]
@mrpaulblack thanks for your hint about `svg2jinja`!

Its OT here but while we are talking about I want to ask you and @dalf if we really need this grunt task:
 
https://github.com/searxng/searxng/blob/f3d4b25e739164ea6af087379536b3ef3538d63c/searx/static/themes/simple/gruntfile.js#L200

Isn't it simpler to copy the svg icons once into the html / AFAIK the ionicons will never modified(?)

**Comment by dalf** [comment]
About the icon, I prefer the hamburger menu.

> Isn't it simpler to copy the svg icons once into the html 

I don't understand when do you want to make this copy.
Once the theme is compiled, ionicons is not available (it is in node_modules)
`svg2jinja` minifies the content of the selected icons, and inline the results in the HTML file

**Comment by return42** [comment]
> I don't understand when do you want to make this copy.

@dalf I haven't thought to its end but I am asking for because of configurable icons in the categories 

- [Stop hardcoding icons in the Simple theme (searx/templates/simple/categories.html), define them in categories_as_tabs in settings.yml instead](https://github.com/searxng/searxng/issues/690) from @not-my-profile and
- https://github.com/searxng/searxng/pull/603#issuecomment-994929745 from mine

> Once the theme is compiled, ionicons is not available (it is in node_modules)

May be we copy the SVG files from ionicons once, like we can do it from any other source.

What I mean: when those icons are configurable any other SVG file should be good enough. (I ignore request/response cycles for now / if, then they need to optimized on the server code).

**Pull request closed without merging**
