### PR TITLE
[simple theme] center results on tablet

### PR DESCRIPTION
**Pull request by mrpaulblack**
## What does this PR do?
This PR centers every result, except images, on tablets when using the simple theme.

## Why is this change important?

Make the simple theme more user friendly on tablets.

## How to test this PR locally?

```make run```

## Author's checklist

Light mode on tablet with this PR applied:
image

### CODE REVIEW

**Review by return42 — APPROVED** [review]
Thanks a lot!  .. I just fixed a typo "cemter" --> "center" in the commit message.

**Comment by return42** [comment]
> center results on tablet

@MrPaulBlack what do you think about media-screen selectors and the word "tablet" .. this patch applies to `max-width: 80em` ... does it make sense to give the media-screen selectors (`max-width: ...`) some names?

```
./themes/simple/src/less/style.less\0572:@media screen and (max-width: 80em) {
./themes/simple/src/less/style.less\0713:@media screen and (max-width: 50em) {
./themes/simple/src/less/style.less\0770:@media screen and (max-width: 35em) {
./themes/simple/src/less/preferences.less\0119:@media screen and (max-width: 80em) {
./themes/simple/src/less/toolkit.less\0436:@media screen and (max-width: 50em) {
./themes/simple/src/less/index.less\038:@media screen and (max-width: 80em) {
./themes/simple/src/less/index.less\050:@media screen and (max-width: 50em) {
./themes/simple/src/less/search.less\0106:@media screen and (max-width: 80em) {
./themes/simple/src/less/search.less\0148:@media screen and (max-width: 50em) {
./themes/simple/src/less/autocomplete.less\063:@media screen and (max-width: @results-width) {
./themes/oscar/src/less/logicodev/results.less\0263:@media screen and (max-width: 75em) {
```

**Comment by mrpaulblack** [comment]
@return42 I am not really sure I know what you mean with giving them name tbh... Could you give me an example.... Like how would you change this line?
```less
@media screen and (max-width: 80em) {...}
```

**Comment by mrpaulblack** [comment]
Oh I get it now. Giving them names with CSS or LESS vars. Yeah I think that is a great idea actually!
Everything > 80em is desktop; < 80em is tablet; < 50em is phone and < 35em is a small phone... You could add the vars to `definitions.less`....

So something like this:
```less
//definitions.less
@tablet = 80em;
@phone = 50em;
@small-phone = 35em;

//in the respective less files
@media screen and (max-width: @tablet) {...}
@media screen and (max-width: @phone) {...}
@media screen and (max-width: @small-phone) {...}
```

**Pull request merged**
