### PR TITLE
Upgrade installation scripts and documentation

### LINKED ISSUE #1112: Install scripts: remove filtron.sh and morty.sh
* The [limiter plugin](https://github.com/searxng/searxng/blob/master/searx/plugins/limiter.py) can replace filtron. It is reliabled on a public instance.
* The embedded image proxy can replace morty.

```yaml
server:
  limiter: true  # can be disabled for a private instance
  image_proxy: true
redis:
  url: redis://....
```

---

searxng-docker is about to do the same: https://github.com/searxng/searxng-docker/pull/12

### PR DESCRIPTION
**Pull request by return42**
A preview of the documentation about the upgrade is available from here:

https://return42.github.io/searxng/admin/update-searxng.html#migrate-and-stay-tuned

**HINT:  last patch on top needs to be removed before this PR is merged!** 

    [brand] branch: searxng-install https://github.com/return42/searxng

This brand is needed to test the installation procedures as long this PR is not merged into master.

----

## What does this PR do?

```
- [utils/searxng.sh] implement new script to install SearXNG
- [doc] update documentation of the installation procedures
- [clean up] drop obsolete searx, filtron and morty install scripts
- [docs] add section "Migrate and stay tuned!"
```

## Why is this change important?

The infrastructure of SearXNG has changed dramatically over the past year. The installation scripts and documentation have not been adapted so far.

## How to test this PR locally?

----

First read the admin documentation, to see what have been changed ..

    make docs.live

----

Test new `./utils/searxng.sh` script ..

in LXCs, first build containers and install SearXNG by `install all`:

    sudo -H ./utils/lxc.sh build
    sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install all
    
Choose to `install nginx`:

    sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx

or `install apache` HTTP server:

    sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install apache
     
Run `instance check`:

    sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh instance check

Now you can test the SearXNG instances from the conatiners, to get the URLs of the containers use:

    sudo -H ./utils/lxc.sh show suite | grep SEARXNG_URL
    ...
    [searxng-ubu2004]    SEARXNG_URL          : http://10.146.148.203/searxng
    [searxng-ubu2110]    SEARXNG_URL          : http://10.146.148.219/searxng
    [searxng-fedora35]    SEARXNG_URL          : http://10.146.148.64/searxng
    [searxng-archlinux]    SEARXNG_URL          : http://10.146.148.135/searxng

----

Settings see https://github.com/return42/searxng/blob/searxng-install/utils/templates/etc/searxng/settings.yml#L3-L22

Features:

- the limiter should work (except on fedora35, see "Pitfalls of the Tyrant mode" in the uWSGI admn-doc)
- image_proxy should work on all instances
- cache busting (aka `static_use_hash`) should work

----

closes: https://github.com/searxng/searxng/issues/1112

### CODE REVIEW

**Comment by return42** [comment]
FYI: rebased branch and append  

- b5ecade02 [docs] corrections from @tiekoetter's review

Thank you, @tiekoetter :+1:

**Comment by dalf** [comment]
Running:
`sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install all`

There are warning about the virtualenv:
```
sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install all


[searxng-ubu2004] Create virtualenv (python)
[searxng-ubu2004] --------------------------
[searxng-ubu2004] 
[searxng-ubu2004] ERROR: ./utils/searxng.sh: line 474: To create pyenv for SearXNG, first install searxng-src.
WARN:  [searxng-ubu2004] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all
INFO:  [searxng-ubu2110] FORCE_TIMEOUT=0 ./utils/searxng.sh install all


[searxng-ubu2110] Create virtualenv (python)
[searxng-ubu2110] --------------------------
[searxng-ubu2110] 
[searxng-ubu2110] ERROR: ./utils/searxng.sh: line 474: To create pyenv for SearXNG, first install searxng-src.
WARN:  [searxng-ubu2110] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all
INFO:  [searxng-fedora35] FORCE_TIMEOUT=0 ./utils/searxng.sh install all


[searxng-fedora35] Create virtualenv (python)
[searxng-fedora35] --------------------------
[searxng-fedora35] 
[searxng-fedora35] ERROR: ./utils/searxng.sh: line 474: To create pyenv for SearXNG, first install searxng-src.
WARN:  [searxng-fedora35] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all
INFO:  [searxng-archlinux] FORCE_TIMEOUT=0 ./utils/searxng.sh install all


[searxng-archlinux] Clone SearXNG sources
[searxng-archlinux] ---------------------
[searxng-archlinux] 
[searxng-archlinux] WARN:  missing local branch searxng-install
[searxng-archlinux] INFO:  create local branch searxng-install from start point: origin/searxng-install
[searxng-archlinux] fatal: not a valid object name: 'origin/searxng-install'
[searxng-archlinux] WARN:  take into account, installing branch searxng-install while current branch is return42-searxng-install
[searxng-archlinux] INFO:  clone into: /usr/local/searxng/searxng-src
[searxng-archlinux] mkdir -p "/usr/local/searxng"
[searxng-archlinux] cd "/usr/local/searxng"
[searxng-archlinux] git clone --branch "searxng-install" --origin "origin" "/share/searxng" "searxng-src"
[searxng-archlinux]   |searxng| Cloning into 'searxng-src'...
[searxng-archlinux]   |searxng| fatal: Remote branch searxng-install not found in upstream origin
[searxng-archlinux] ./utils/searxng.sh: line 459: pushd: /usr/local/searxng/searxng-src: No such file or directory
[searxng-archlinux] cd "/usr/local/searxng/searxng-src"
[searxng-archlinux]   |searxng| -bash: line 1: cd: /usr/local/searxng/searxng-src: No such file or directory
[searxng-archlinux] git remote set-url origin https://github.com/return42/searxng
[searxng-archlinux]   |searxng| fatal: not a git repository (or any of the parent directories): .git
[searxng-archlinux] git config user.email "root@searxng-archlinux"
[searxng-archlinux]   |searxng| fatal: not in a git directory
[searxng-archlinux] git config user.name "root"
[searxng-archlinux]   |searxng| fatal: not in a git directory
[searxng-archlinux] git config --list
[searxng-archlinux]   |searxng| safe.directory=/usr/local/searxng/searxng-src
[searxng-archlinux] ./utils/searxng.sh: line 467: popd: directory stack empty
[searxng-archlinux] ** press any [KEY] to continue **
[searxng-archlinux] 
[searxng-archlinux] Create virtualenv (python)
[searxng-archlinux] --------------------------
[searxng-archlinux] 
[searxng-archlinux] ERROR: ./utils/searxng.sh: line 474: To create pyenv for SearXNG, first install searxng-src.
WARN:  [searxng-archlinux] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all
```

The command ends with the line above and the exit code 42. Is it normal ?

---

https://github.com/dalf/searxng-install : the scripts runs in a GitHub Action. "Of course" there is a [network issue](https://github.com/dalf/searxng-install/runs/7052522540?check_suite_focus=true): the gateway is reachable but not further. I wish to fix this issue so we can run these tests automatically.

**Comment by return42** [comment]
> the scripts runs in a GitHub Action. 

Would be cool to have an automated test :+1:

> "Of course" there is a [network issue](https://github.com/dalf/searxng-install/runs/7052522540?check_suite_focus=true): 

Without a network no packages can be installed and the SearXNG brand (repo) can't be cloned. 

> The command ends with the line above and the exit code 42. Is it normal ?

Yes, the function `searxng.install.pyenv` check if a clone exists, if not, it ends with exit code 42 .. 

https://github.com/return42/searxng/blob/searxng-install/utils/searxng.sh#L470-L474

You will see the same exit code, if you do not install `all` but calling `./utils/searxng.sh install pyenv` without having cloned before (`./utils/searxng.sh install searxng-src`).

https://github.com/return42/searxng/blob/searxng-install/utils/searxng.sh#L133

**Comment by dalf** [comment]
> Yes, the function searxng.install.pyenv check if a clone exists, if not, it ends with exit code 42 ..

I've tried the next step: `sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx`.

The full log:
```
INFO:  [searxng-ubu2004] FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx
[searxng-ubu2004] 
[searxng-ubu2004] Install nginx site searxng.conf
[searxng-ubu2004] ===============================
[searxng-ubu2004] 
[searxng-ubu2004] This installs SearXNG's uWSGI app as Nginx site.  The Nginx site is
[searxng-ubu2004] located at: /etc/nginx/default.apps-available/searxng.conf and requires
[searxng-ubu2004] a uWSGI.
[searxng-ubu2004] 
[searxng-ubu2004] To install uWSGI use::
[searxng-ubu2004] 
[searxng-ubu2004]     searxng.sh install uwsgi
[searxng-ubu2004] 
[searxng-ubu2004] ERROR: ./utils/searxng.sh: line 684: SearXNG's uWSGI app not available
WARN:  [searxng-ubu2004] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx
INFO:  [searxng-ubu2110] FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx
[searxng-ubu2110] 
[searxng-ubu2110] Install nginx site searxng.conf
[searxng-ubu2110] ===============================
[searxng-ubu2110] 
[searxng-ubu2110] This installs SearXNG's uWSGI app as Nginx site.  The Nginx site is
[searxng-ubu2110] located at: /etc/nginx/default.apps-available/searxng.conf and requires
[searxng-ubu2110] a uWSGI.
[searxng-ubu2110] 
[searxng-ubu2110] To install uWSGI use::
[searxng-ubu2110] 
[searxng-ubu2110]     searxng.sh install uwsgi
[searxng-ubu2110] 
[searxng-ubu2110] ERROR: ./utils/searxng.sh: line 684: SearXNG's uWSGI app not available
WARN:  [searxng-ubu2110] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx
INFO:  [searxng-fedora35] FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx
[searxng-fedora35] 
[searxng-fedora35] Install nginx site searxng.conf
[searxng-fedora35] ===============================
[searxng-fedora35] 
[searxng-fedora35] This installs SearXNG's uWSGI app as Nginx site.  The Nginx site is
[searxng-fedora35] located at: /etc/nginx/default.apps-available/searxng.conf and requires
[searxng-fedora35] a uWSGI.
[searxng-fedora35] 
[searxng-fedora35] To install uWSGI use::
[searxng-fedora35] 
[searxng-fedora35]     searxng.sh install uwsgi
[searxng-fedora35] 
[searxng-fedora35] ERROR: ./utils/searxng.sh: line 684: SearXNG's uWSGI app not available
WARN:  [searxng-fedora35] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx
INFO:  [searxng-archlinux] FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx
[searxng-archlinux] 
[searxng-archlinux] Install nginx site searxng.conf
[searxng-archlinux] ===============================
[searxng-archlinux] 
[searxng-archlinux] This installs SearXNG's uWSGI app as Nginx site.  The Nginx site is
[searxng-archlinux] located at: /etc/nginx/default.apps-available/searxng.conf and requires
[searxng-archlinux] a uWSGI.
[searxng-archlinux] 
[searxng-archlinux] To install uWSGI use::
[searxng-archlinux] 
[searxng-archlinux]     searxng.sh install uwsgi
[searxng-archlinux] 
[searxng-archlinux] ERROR: ./utils/searxng.sh: line 684: SearXNG's uWSGI app not available
WARN:  [searxng-archlinux] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx
```

**Comment by return42** [comment]
> I've tried the next step: `sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx`.

Sorry, I do not understand the intention of your question.

Isn't it clear, that `all` is just a command that calls other commands in the needed order:

https://github.com/return42/searxng/blob/searxng-install/utils/searxng.sh#L256-L287

If one command fails it does not make sense to continue with the next; When there is no clone, you can't install a pyenv, when there is no uwsgi service installed, you can't install a HTTP service for this uWSGI service .. and when there is a  [network issue](https://github.com/dalf/searxng-install/runs/7052522540?check_suite_focus=true) it makes no sense to try an installation, since nothin can be loaded and installed from package manager repositories.

**Comment by dalf** [comment]
> and when there is a [network issue](https://github.com/dalf/searxng-install/runs/7052522540?check_suite_focus=true) it makes no sense to try an installation

The network issue is from this [GitHub workflow](https://github.com/dalf/searxng-install/blob/main/tests.yml) (disabled for now)

---

The log above comes from my try on my laptop: there is no network issue.
To make sure, I've tried again, so I've stopped all the containers, remove them and run the script again.

* `sudo -H ./utils/lxc.sh build` went well
* `sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install all` stops with some errors:

```
[searxng-ubu2004] Finalize installation
[searxng-ubu2004] =====================
[searxng-ubu2004] 
[searxng-ubu2004] Do you want to run some checks? [YES/no] Yes
[searxng-ubu2004] INFO:  wrapper:  utils/searxng.sh instance _call searxng.check
[searxng-ubu2004] -bash: /usr/local/searxng/searxng-src/utils/searxng.sh: No such file or directory
WARN:  [searxng-ubu2004] exit code (127) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all


[searxng-ubu2110] Finalize installation
[searxng-ubu2110] =====================
[searxng-ubu2110] 
[searxng-ubu2110] Do you want to run some checks? [YES/no] Yes
[searxng-ubu2110] INFO:  wrapper:  utils/searxng.sh instance _call searxng.check
[searxng-ubu2110] -bash: line 1: /usr/local/searxng/searxng-src/utils/searxng.sh: No such file or directory
WARN:  [searxng-ubu2110] exit code (127) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all


[searxng-fedora35] Finalize installation
[searxng-fedora35] =====================
[searxng-fedora35] 
[searxng-fedora35] Do you want to run some checks? [YES/no] Yes
[searxng-fedora35] INFO:  wrapper:  utils/searxng.sh instance _call searxng.check
[searxng-fedora35] -bash: line 1: /usr/local/searxng/searxng-src/utils/searxng.sh: No such file or directory
WARN:  [searxng-fedora35] exit code (127) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all
INFO:  [searxng-archlinux] FORCE_TIMEOUT=0 ./utils/searxng.sh install all
[searxng-archlinux] ERROR: missing command wget
WARN:  [searxng-archlinux] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all
```

---

In addition to the test above I have updated https://github.com/dalf/searxng-install : 
* see [/blob/main/.github/workflows/test2.yml](https://github.com/dalf/searxng-install/blob/main/.github/workflows/test2.yml)
* the result: https://github.com/dalf/searxng-install/runs/7062375666?check_suite_focus=true

It is not surprising reading the doc, however I'm not sure how to solve that.

**Comment by return42** [comment]
> The network issue is from this [GitHub workflow](https://github.com/dalf/searxng-install/blob/main/tests.yml) (disabled for now)
> The log above comes from my try on my laptop: there is no network issue.
> To make sure, I've tried again, so I've stopped all the containers, remove them and run the script again.

Ah, OK .. thats good .. if you have problems building all containers, I recommend to run your first test in a single container, e.g. I often use archlinux for a first test;  bevore remove all containers and all images (I have seen some issues building all containers due to the limited size of the lxc storage where all the containers and images are stored)

```
sudo -H ./utils/lxc.sh remove containers
sudo -H ./utils/lxc.sh remove images
sudo -H ./utils/lxc.sh cmd searxng-archlinux FORCE_TIMEOUT=0 ./utils/searxng.sh install all
```

Does this work on your laptop ..

If yes, install ngingx:

     sudo -H ./utils/lxc.sh cmd searxng-archlinux FORCE_TIMEOUT=0 ./utils/searxng.sh install nginx

I not,  please read the log thoroughly, are there any ERROR messages .. please post it here to see where it might fail.

The message you posted above:

      [searxng-ubu2004] -bash: /usr/local/searxng/searxng-src/utils/searxng.sh: No such file or directory
      [searxng-ubu2110] -bash: line 1: /usr/local/searxng/searxng-src/utils/searxng.sh: No such file or directory

shows me that the clone was not built .. and  the nessage

     [searxng-archlinux] ERROR: missing command wget

shows me, that the wget command from the archlinix package manager was not installed for some reason, I assume you have no more space left on your lxc storage.  And this is the reason why the installation in the containers fails at different points (do you see a "no space left" message anywhere in the log?).

----

About CI & LXC ..

> It is not surprising reading the doc, however I'm not sure how to solve that.

:-)  .. after the clone ..

https://github.com/dalf/searxng-install/blob/main/.github/workflows/test2.yml#L17

and before the `install all` add a `chmod ugo+rwx -R searxng` .. does it help?

**Comment by dalf** [comment]
Ok I figured out the issue: I created a new branch from master and then merge the changes from this branch. 
Once I checked out return42/searxng-install it works as intended.

<details>

<summary>the log about "Clone SearXNG sources" with the previous configuration (new branch from master and then merge searxng-install)</summary>

```
Clone SearXNG sources
---------------------

WARN:  missing local branch searxng-install
INFO:  create local branch searxng-install from start point: origin/searxng-install
fatal: not a valid object name: 'origin/searxng-install'
WARN:  take into account, installing branch searxng-install while current branch is return42-searxng-install
INFO:  clone into: /usr/local/searxng/searxng-src
mkdir -p "/usr/local/searxng"
cd "/usr/local/searxng"
git clone --branch "searxng-install" --origin "origin" "/share/searxng" "searxng-src"
  |searxng| Cloning into 'searxng-src'...
  |searxng| fatal: Remote branch searxng-install not found in upstream origin
./utils/searxng.sh: line 459: pushd: /usr/local/searxng/searxng-src: No such file or directory
cd "/usr/local/searxng/searxng-src"
  |searxng| -bash: line 1: cd: /usr/local/searxng/searxng-src: No such file or directory
git remote set-url origin https://github.com/return42/searxng
  |searxng| fatal: not a git repository (or any of the parent directories): .git
git config user.email "root@searxng-archlinux"
  |searxng| fatal: not in a git directory
git config user.name "root"
  |searxng| fatal: not in a git directory
git config --list
  |searxng| safe.directory=/usr/local/searxng/searxng-src
./utils/searxng.sh: line 467: popd: directory stack empty
** press any [KEY] to continue **

Create virtualenv (python)
--------------------------

ERROR: ./utils/searxng.sh: line 474: To create pyenv for SearXNG, first install searxng-src.
WARN:  [searxng-archlinux] exit code (42) from FORCE_TIMEOUT=0 ./utils/searxng.sh install all
```

</details>

----

> and before the install all add a chmod ugo+rwx -R searxng .. does it help?

It seems to be a chicken / egg problem: after then git clone, the searxng user does not exist.

why doesn't the script do the chown?

See the log: https://github.com/dalf/searxng-install/runs/7062375666?check_suite_focus=true#step:2:180

**Comment by return42** [comment]
> why doesn't the script do the chown?

The script should not change permissions of objects that are not a part of the installation itself .. the git clone in this folder is a "tool" to install, but it is not a part of the installation itself. I hope it was understandable what I wanted to express.

**Review by dalf — APPROVED** [review]

**Comment by return42** [comment]
FYI: in preparation to merge this PR, the branch has been rebased on master and the *brand-commit* has been removed (see [HINT](https://github.com/searxng/searxng/pull/1332#issue-1273853164))

A preview of the documentation about the upgrade is available from here:

https://return42.github.io/searxng/admin/update-searxng.html#migrate-and-stay-tuned

**Pull request merged**
