### PR TITLE
Simple theme: the cookie table is always displayed left-to-right

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

In the preferences, the cookie table is always displayed LTR: 

image

## Why is this change important?

Fix UI issue.

## Related issues

Related to #827 
@GreenLunar  : this PR fixes the Simple theme, not the Oscar theme.

### CODE REVIEW

**Comment by GreenLunar** [comment]
Since it's in English and will always be reported here, in English, the table should be LTR in any theme.
Screenshot looks good.

**Review by return42 — APPROVED** [review]
This PR works, but the theme (the property page) still have RTL issues

**Comment by return42** [comment]
@GreenLunar FYI we will drop oscar theme in the near future.

**Comment by GreenLunar** [comment]
> This PR works, but the theme (the property page) still have RTL issues

Please refer me to any page you think has issue.

**Comment by return42** [comment]
Choose "Persian, Iran" language and go to preferences .. 

grafik

have an attention on the scrollbar in the bottom .. the page is extremely width.

**Pull request merged**
