### PR TITLE
[fix] Brave - Update xpath

### PR DESCRIPTION
**Pull request by allendema**
No results were returned.

## What does this PR do?
Fixes engine.

Update xpath exp.

## Why is this change important?

Fix engine.

## How to test this PR locally?

```!brave User-in-the-Loop```
## Author's checklist

N/A
## Related issues
N/A

### CODE REVIEW

**Comment by dalf** [comment]
Thank you. It works.

Can you merge the commits?

If is `a[@class="result-header"]/@href` enough ? (compare to `*[@class="result-header"]/@href`)

**Comment by dsh2dsh** [comment]
I tried it in my local searx-settings.yaml
```
engines:
  - name: brave
    url_xpath: //a[@class="result-header"]/@href
```
It works fine. I see brave results again. Thanks!

**Comment by julianfairfax** [comment]
Works perfectly. Should be merged.

**Comment by allendema** [comment]
Closing this merge request and opening a new one because of a mistake.

> If is a[@class="result-header"]/@href enough?

It is enough but they could change theHTML anytime, maybe just use the asterix to select any tag.

**Pull request closed without merging**
