### PR TITLE
Fix port scrolling up and down in image results

### LINKED ISSUE #3017: [BUG] Images are moving if I click on navigaton button
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

https://searx.kutay.dev/
2023.11.14+b3d29cb86

**How To Reproduce**

brave_2HbEXi8zVV
brave_Nnjv2L54OB
brave_rZ7oKNYmPG

### PR DESCRIPTION
**Pull request by ahmad-alkadri**
## What does this PR do?

Possibly fixes #3017. Preventing the displayed detail from moving/jumping up and down when the next/previous buttons clicked by simply preventing default browser action(s) when the click event occurred. 

Some screen records:

| Before the fix |
| --- |
| 0-before-fix |

| After the fix |
| --- |
| 1-after-fix |

## Why is this change important?

Improving user experience in images search results.

## How to test this PR locally?

Simply using `make run`or, if you want to test it while doing modifications on the frontend files, `LIVE_THEME=simple make run`

## Author's checklist

+ Build files compiled and committed
+ Styles checked

## Related issues

(Potentially) Closes #3017

### CODE REVIEW

**Review by return42 — APPROVED** [review]
> (Potentially) Closes https://github.com/searxng/searxng/issues/3017

I can confirm, this patch fixes #3017 .. thanks a lot for taking the time :+1: 

FYI I pushed the `make static.build.commit` on your branch / If it is not clear what I mean by, see our [Development Quickstart](https://docs.searxng.org/dev/quickstart.html).

**Comment by ahmad-alkadri** [comment]
> > (Potentially) Closes #3017
> 
> I can confirm, this patch fixes #3017 .. thanks a lot for taking the time 👍
>

No problem. It kinda surprised me that the problem's apparently been existing in the _simple_ theme for a while, across (probably) all instances using it, including mine. How I've never noticed it before is beyond me. I guess I rarely used the Image search. 
 
> FYI I pushed the `make static.build.commit` on your branch / If it is not clear what I mean by, see our [Development Quickstart](https://docs.searxng.org/dev/quickstart.html).

Yes, thank you. I haven't pushed the compiled build statics because it was still draft (hence why it was still in my **Author's Checklist**). Apologies for bothering you with this.

Fully open for discussions/reviews.

**Review by Bnyro — APPROVED** [review]
Can confirm this does the job :+1:

**Comment by return42** [comment]
> Apologies for bothering you with this.

No need to apologies .. perfect work!  .. I only mentioned it because I wasn't sure if you were aware of the `make static.build.commit` .. thanks a lot for taking the time :+1:

**Pull request merged**
