### PR TITLE
[fix] follow up of PR-1856

### PR DESCRIPTION
**Pull request by return42**
- `` url: false`` breaks with existing installations   https://github.com/searxng/searxng/commit/e92755d358df5b34b0181f48f8ba02c7f2939e8f#r89577339

- PR-1856: https://github.com/searxng/searxng/pull/1856

- Comments from review: https://github.com/searxng/searxng/pull/1856#pullrequestreview-1176402810

### CODE REVIEW

**Comment by dalf** [comment]
> url: false breaks with existing installations

Do the installation scripts use this following file  ?
https://github.com/searxng/searxng/blob/3a765113eefc7ac0b1ee94e9a0ac0db8069ec336/utils/templates/etc/searxng/settings.yml#L18-L19

If yes, the existing installation should be fine.

> it breaks all developer scenarios.

It doesn't work for developer having a Redis instance on the default TCP port.

There is `SEARXNG_DEBUG` for `general.debug`.
It is easy to add `SEARXNG_REDIS_URL` for `redis.url`:
* it avoids to push development settings to all installations
* and most importantly, if `redis.url` is defined, the code can be the URL should work, there is no "here an exception, but actually ignore that or may be not".

**Comment by return42** [comment]
> If yes, the existing installation should be fine.

Yes, sorry .. I didn't have used this template in my instance so I had the issue.

> It is easy to add `SEARXNG_REDIS_URL` for `redis.url`:

OK .. when I have time I will have a look and update this PR / thanks!

**Comment by return42** [comment]
> * and most importantly, if `redis.url` is defined, the code can be the URL should work, there is no "here an exception, but actually ignore that or may be not".

What if redis server is not up and running?

**Comment by dalf** [comment]
> What if redis server is not up and running?

If the user has configured an URL and it doesn't work, then this is an error.
In this scenario, SearXNG can exit.

However if the value is `unix:///usr/local/searxng-redis/run/redis.sock?db=0`, SearXNG can not decide.

> OK .. when I have time I will have a look and update this PR / thanks!

<details>

<summary>Here a patch based on the master branch</summary>

```patch
diff --git a/manage b/manage
index c887826e2..3879087b2 100755
--- a/manage
+++ b/manage
@@ -31,6 +31,8 @@ export NODE_MINIMUM_VERSION="16.13.0"
 # SPHINXOPTS=
 BLACK_OPTIONS=("--target-version" "py37" "--line-length" "120" "--skip-string-normalization")
 BLACK_TARGETS=("--exclude" "searx/static,searx/languages.py" "--include" 'searxng.msg|\.pyi?$' "searx" "searxng_extra" "tests")
+DEFAULT_DEV_REDIS_SOCKET="/usr/local/searxng-redis/run/redis.sock"
+
 
 pylint.FILES() {
 
@@ -144,6 +146,11 @@ webapp.run() {
         sleep 3
         xdg-open http://127.0.0.1:8888/
     )&
+    # set SEARXNG_REDIS_URL if it is not defined and "{DEFAULT_DEV_REDIS_URL}" exists.
+    if [ -S "${DEFAULT_DEV_REDIS_SOCKET}" ] && [ -z "${SEARXNG_REDIS_URL}" ]; then
+        export SEARXNG_REDIS_URL="unix://${DEFAULT_DEV_REDIS_SOCKET}?db=0"
+        build_msg RUN "Use Redis URL ${SEARXNG_REDIS_URL}"
+    fi
     SEARXNG_DEBUG=1 pyenv.cmd python -m searx.webapp
 }
 
diff --git a/searx/settings_defaults.py b/searx/settings_defaults.py
index 470290f92..cfa1bb47c 100644
--- a/searx/settings_defaults.py
+++ b/searx/settings_defaults.py
@@ -174,7 +174,7 @@ SCHEMA = {
         'default_http_headers': SettingsValue(dict, {}),
     },
     'redis': {
-        'url': SettingsValue((None, False, str), False),
+        'url': SettingsValue((None, False, str), False, 'SEARXNG_REDIS_URL'),
     },
     'ui': {
         'static_path': SettingsDirectoryValue(str, os.path.join(searx_dir, 'static')),
```

</details>

* `SEARXNG_REDIS_URL=redis://localhost?db=0 make run` works.
* if `/usr/local/searxng-redis/run/redis.sock` is a socket, `make run` connect automatically to it EXCEPT if SEARXNG_REDIS_URL is already defined.

(`make test.shell` doesn't show any error, but the script might need some adjustment)

**Comment by return42** [comment]
closed in favorite of https://github.com/searxng/searxng/pull/1954

**Pull request closed without merging**
