### PR TITLE
README.rst: add a link to the screenshots

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

Add a link to the screenshots.
Feel free to suggest better wording.

## Why is this change important?

Some images are better than just text.

## How to test this PR locally?

N/A

## Author's checklist

May be we should keep https://github.com/searxng/searxng-browser-tests as a dev tool, and reference only few screenshots in README.md

### CODE REVIEW

**Comment by unixfox** [comment]
Some values set by default would be great I think.

Like firefox 1280 for browser and index for test case.

**Comment by mrpaulblack** [comment]
I really like when projects have screenshots and with the help of the tool we actually have up to date screenshots; I think what we can do is link to the site itself (also we should maybe put this on a another host like `dev.searxng.org` instead of the path IMO...)

And maybe we can also insert a few screenshots as URL directly into the readme to always have up to date screenshots in the readme. This also helps people coming from SearX to immediately see the SearXNG frontend changes...

**Comment by dalf** [comment]
> we should maybe put this on a another host like dev.searxng.org instead of the path IMO.

Ok. Tell me when dev.searxng.org exists.

---

See https://searxng.org/searxng-browser-tests/screenshots.html

By default it shows some results in general category using FF.
The URL is updated when the user selects another browser and/or test case (= the URL can be copied / pasted).

> And maybe we can also insert a few screenshots as URL directly into the readme

Some symbolic links can be helpful here, so we can have https://dev.searxng.org/images/firefox_1920_search_general.png for example.

**Comment by mrpaulblack** [comment]
`dev.searng.org` has a CNAME now that points to searxng.github.io :+1:

**Comment by dalf** [comment]
PR updated with the new links:
https://dev.searxng.org/
https://dev.searxng.org/screenshots.html

**Review by mrpaulblack — APPROVED** [review]
LGTM :+1: 

Thanks :D

**Comment by return42** [comment]
I got a 404 on https://dev.searxng.org/screenshots.html

**Comment by dalf** [comment]
> I got a 404 on https://dev.searxng.org/screenshots.html

For some reason, new run of the workflow revert the location to https://searxng.org/searxng-browser-tests/

There are persistent URL to the screenshots (perhaps the links need to be updated if the dev.searxng.org is not fixed):
```md
![image](https://dev.searxng.org/screenshots/firefox_1920/search_general/search_general.png)
![image](https://dev.searxng.org/screenshots/firefox_1920/search_images/search_images_detail.png)
![image](https://dev.searxng.org/screenshots/firefox_1920_-_dark_mode/search_videos/search_videos_player.png)
```

image
image
image

**Comment by unixfox** [comment]
Still 404 for me too.

**Comment by dalf** [comment]
> Still 404 for me too.

Fixed in commit https://github.com/searxng/searxng-browser-tests/commit/3e556c78c990f798526468990487ed5e1213644c (the GH workflow makes  sure there is a file named `CNAME`).

**Pull request merged**
