### PR TITLE
[fix] interface language zh_CN and zh_TW don't work

### LINKED ISSUE #339: locales zh_CN and zh_TW don't work
On the master branch, `zh_CN` and `zh_TW` fallback to English.

The fix seems to rename the directories `zh_Hans_CN` and `zh_Hant_TW` respectively.

I'm not sure about the consequences.

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

before this commit, when the user picks "Chinese, China" or "Chinese, Taiwan",
the locale fallbacks to English.

This commit fixes this issue (the translations branch must be updated)

## Why is this change important?

Bug fix

## Related issues

close #339

### CODE REVIEW

**Comment by dalf** [comment]
https://github.com/searxng/searxng/blob/cebc0e395b293ddf9f6a4485bb4bfa3a4ee9df4f/tests/unit/test_webapp.py#L214

The fix to unit tests is `b'<option value="zh_Hant_TW" selected="selected">',`
but the returned value is `b'<option value="zh_Hans_CN" selected="selected">',`

**Comment by return42** [comment]
May by the header from ... 

https://github.com/searxng/searxng/blob/cebc0e395b293ddf9f6a4485bb4bfa3a4ee9df4f/tests/unit/test_webapp.py#L211

is not evaluated correctly to `zh_Hant_TW`?

**Comment by return42** [comment]
With .. `'Accept-Language': 'zh-tw;q=0.8'` ...

https://github.com/searxng/searxng/blob/cebc0e395b293ddf9f6a4485bb4bfa3a4ee9df4f/tests/unit/test_webapp.py#L211

The `language` is `zh-TW` ..

https://github.com/searxng/searxng/blob/cebc0e395b293ddf9f6a4485bb4bfa3a4ee9df4f/searx/webapp.py#L528

**Comment by return42** [comment]
With .. `'Accept-Language': 'zh-tw;q=0.8'` ... the `locale` is  `zh_Hans_CN` ..

https://github.com/searxng/searxng/blob/cebc0e395b293ddf9f6a4485bb4bfa3a4ee9df4f/searx/webapp.py#L534

UI_LOCALE_CODES is 

    ['oc', 'nl-BE', 'ar', 'bg', 'bo', 'ca', 'cs', 'cy', 'da', 'de', 'el-GR', 'en', 'eo', 'es', \
    'et', 'eu', 'fa-IR', 'fi', 'fil', 'fr', 'gl', 'he', 'hr', 'hu', 'ia', 'it', 'ja', 'lt', 'nb-NO', 'nl', \
    'pl', 'pt', 'pt-BR', 'ro', 'ru', 'sk', 'sl', 'sr', 'sv', 'ta', 'te', \  
    'tr', 'uk', 'vi', 'zh-Hans-CN', 'zh-Hant-TW']

While LANGUAGE_CODES is ...

    ['af-ZA', 'ar-EG', 'be-BY', 'bg-BG', 'ca-ES', 'cs-CZ', 'da-DK', 'de', 'de-AT', 'de-CH', 'de-DE', 'el-GR', 'en', \
    'en-AU', 'en-CA', 'en-GB', 'en-IE', 'en-NZ', 'en-US', 'es', 'es-AR', 'es-CL', 'es-ES', 'es-MX', 'et-EE', 'fa-IR', \
    'fi-FI', 'fr', 'fr-BE', 'fr-CA', 'fr-CH', 'fr-FR', 'he-IL', 'hr-HR', 'hu-HU', 'id-ID', 'is-IS', 'it-IT', 'ja-JP', 'ko-KR', 'lt-LT',\
     'lv-LV', 'nb-NO', 'nl', 'nl-BE', 'nl-NL', 'pl-PL', 'pt-PT', 'ro-RO', 'ru-RU', 'sk-SK', 'sl-SI', 'sr-RS', 'sv-SE', 'sw-TZ',\
     'th-TH', 'tr-TR', 'uk-UA', 'vi-VN', 'zh', 'zh-CN', 'zh-HK', 'zh-TW', 'all']



https://github.com/searxng/searxng/blob/cebc0e395b293ddf9f6a4485bb4bfa3a4ee9df4f/searx/webapp.py#L249-L256

I guess one of this the functions ..

https://github.com/searxng/searxng/blob/cebc0e395b293ddf9f6a4485bb4bfa3a4ee9df4f/searx/utils.py#L396

https://github.com/searxng/searxng/blob/cebc0e395b293ddf9f6a4485bb4bfa3a4ee9df4f/searx/utils.py#L373

does not match from `zh-TW` to `'zh-Hant-TW'` locale when argument `lang_list=UI_LOCALE_CODES` is used ..

@MarcAbonce do you have an idea how we can fix it?

**Comment by MarcAbonce** [comment]
I think I figured it out in #382.
I opened a separate PR just to see how the CI reacted to my changes, but I don't know if it would make more sense for you to cherry pick my commit into this PR or if they can be merged separately.

**Comment by return42** [comment]
>  but I don't know if it would make more sense for you to cherry pick my commit into this PR 

@MarcAbonce / thanks a lot!  ... I picked your commits on top if this PR, an added 89cdb23d

I don't know if 6ad6c26 fixes the issue right / I'm bit confused that we have `-` and `_` as separators / IMO `-` (minus) is correct::

```html
...
<html lang="zh_Hant_TW" ...>
...
<option value="all" >
...
<option value="ca-ES" >
...
<option value="en" >English - en</option>
<option value="en-AU" >English (Australia) - en-AU</option>
<option value="en-CA" >English (Canada) - en-CA</option><
option value="en-GB" >English (United Kingdom) - en-GB</option>
<option value="en-IE" >English (Ireland) - en-IE</option>
<option value="en-NZ" >English (New Zealand) - en-NZ</option>
<option value="en-US" >English (United States) - en-US</option>
...
<option value="zh_Hans_CN" > ...
<option value="zh_Hant_TW" selected="selected"> ...
```

**Comment by dalf** [comment]
I've pushed a new commit ( eef9ba1132bd401ec25d2b290aad9841e4a3f819 ) to fix the output : `<html lang="zh-TW" ...>` (instead of `<html lang="zh_Hant_TW" ...>`).

**Comment by return42** [comment]
> I've pushed a new commit ( eef9ba1132bd401ec25d2b290aad9841e4a3f819 ) to fix the output : `<html lang="zh-TW" ...>` (instead of `<html lang="zh_Hant_TW" ...>`).

Yes, this patch fix the output in the templates, but is this not only a symptom?  What me confused is, that  `match_language(..)` returns values with a  `-` and a `_` separator. .. or I am wrong?

**Comment by MarcAbonce** [comment]
> Yes, this patch fix the output in the templates, but is this not only a symptom? What me confused is, that match_language(..) returns values with a - and a _ separator. .. or I am wrong?

Yeah, this is kind of confusing.
The Babel library internally uses underscores to separate their locales.
Ideally, everything else should use hyphens.

The function match_languages in only meant to handle locales with hyphens/minus signs.
The only part where the locales are converted to underscores is when consuming Babel's get_global data structure, which internally is using underscores. *

I think the translation directories also use underscores because of Babel.

\* Edit: I don't know if it would be more readable to refactor 6ad6c26b7f7b7c47c44e47d0afb778eee15f9158 to extract all the calls to Babel's get_global so all that converting back and forth is encapsulated away from the rest of match_languages.

\* Edit 2: Something like this: https://github.com/MarcAbonce/searxng/commit/dffb16cafaef02564c61ac41631a5f57f2aed7c0?

**Comment by dalf** [comment]
@MarcAbonce  I have included your commit and another one to use hyphen everywhere except when Babel needs it:
* `searx.webapp.get_locale` (`UI_LOCALE_CODES` is not required anymore).
* `searx.utils.match_language` with your commits

Note: `searx.webapp._get_locale_rfc5646` is required (because Chrom* browser don't detect language code with subtag, see [comment](https://github.com/searxng/searxng/blob/4d2d350074e67d530e2fe03b640ecf4d96aaab26/searx/webapp.py#L268-L275))

**Pull request merged**
