### PR TITLE
Add user documentation "How to search"

### PR DESCRIPTION
**Pull request by not-my-profile**
## What does this PR do?

Replaces the previous [search syntax](https://docs.searxng.org/user/search_syntax.html) documentation with a [more thorough How to search](https://share.push-f.com/searxng/how-to-search/user/how-to-search.html) documentation.

### CODE REVIEW

**Comment by return42** [comment]
@dalf @mrpaulblack  I don't know what is better ..

My very personal opinion: 

commits e401a384 and 73382661 are worth to merge. About 

- 6559a017 [doc] create "How to search" user documentation

I have a doubt. IMO it is to text-heavy and users might prefer the more simple description we currently have .. but as I said; I don't know.

**Comment by not-my-profile** [comment]
>I don't know what is better ..

We can have both!

>IMO it is to text-heavy and users might prefer the more simple description we currently have

The current documentation fails to explain many important details that aren't obvious.

But you're right that we should also have a short syntax reference somewhere.
I think ideally it should be shown as a popup in the UI when clicking a link like `Syntax?` next to the search box.
When clicked it would show a brief syntax overview in a popup, like what we currently have:

image

and then there would be a `Learn more` link that links to the more extensive user documentation I introduce in this PR.

**Comment by not-my-profile** [comment]
Ok, I'm closing this for now. I think we should address #722 first.

**Comment by dalf** [comment]
A feature without documentation: https://github.com/searx/searx/pull/1640

**Pull request closed without merging**
