### PR TITLE
[README] add doc-links: disable metrics & hostname replace

### PR DESCRIPTION
**Pull request by return42**

### CODE REVIEW

**Review by mrpaulblack — APPROVED** [review]
LGTM

**Comment by unixfox** [comment]
Better wording:
```
- thanks to the anonymous metrics, it is easier to report a bug of an engine and thus engines get fixed more quickly
  - if you don't want any metrics to be recorded, you can `disable them on the server
  <https://docs.searxng.org/admin/engines/settings.html#general>`_
- administrator can `block and/or replace the URLs in the search results
  <https://github.com/searxng/searxng/blob/5c1c0817c3996c5670a545d05831d234d21e6217/searx/settings.yml#L191-L199>`_
```
I've added space for the 2nd point in order to make some context with the previous message.

**Comment by return42** [comment]
> Better wording:

much better .. thanks!

done: https://github.com/return42/searxng/tree/mod-README#differences-to-searx

**Comment by unixfox** [comment]
> > Better wording:
> 
> much better .. thanks!
> 
> done: [https://github.com/return42/searxng/tree/mod-README#differences-to-searx](https://github.com/return42/searxng/tree/mod-README?rgh-link-date=2022-07-05T12%3A15%3A02Z#differences-to-searx)

you forgot to remove the line `- it is easier to report a bug of an engine`

**Comment by return42** [comment]
> you forgot to remove 

:facepalm: .. sorry .. done: https://github.com/searxng/searxng/compare/ce7836bfe6f507384ff480c476eeace18de55d09..3722d078587dfac4311caa1f05beaf971054640d

**Review by unixfox — APPROVED** [review]

**Pull request merged**
