### PR TITLE
ucbcb bypass method to CONSENT yes for google

### LINKED ISSUE #1432: Bug: google images engine
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.07.02-4ef62637

**How did you install SearXNG?**
I installed SearXNG using docker.

**What happened?**
As soon as i search something the results show as normal but i can't open the Images tab and there are no images shown on the right side.

**How To Reproduce**
I'm not pretty sure since i just installed it. I changed the language and changed the default categories to "General, Images and Map"

**Expected behavior**
I expected to search for something and have images pop up on the right side instead of `Error! Engines cannot retrieve results:
google images`

**Screenshots & Logs**
(https://gyazo.com/287fc3763f54fe48e90e0332d8f139a0)

**Technical report**

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 100
  * Parameters: `('200', 'OK', 'consent.google.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 100
  * Parameters: `('//script[contains(., "AF_initDataCallback({key: ")]', 'index 1 not found')`
  * File name: `searx/engines/google_images.py:107`
  * Function: `parse_urls_img_from_js`
  * Code: `img_src_script = eval_xpath_getindex(dom, '//script[contains(., "AF_initDataCallback({key: ")]', 1).text`

### PR DESCRIPTION
**Pull request by unixfox**
## What does this PR do?

This change the previous bypass method for Google consent using ucbcb=1 to accept the consent using `CONSENT=YES+`.

It seems like the bypass method with `ucbcb=1` doesn't work consistently. I'll have to investigate further later, but currently I prefer to fix the issue with google images.

## Why is this change important?

Fixes #1432

## Related issues

Closes #1432

### CODE REVIEW

**Comment by return42** [comment]
@unixfox try a `make format.python` to fix the [issue reported by the CI](https://github.com/searxng/searxng/runs/7498482427?check_suite_focus=true#step:7:47).

**Comment by unixfox** [comment]
> @unixfox try a `make format.python` to fix the [issue reported by the CI](https://github.com/searxng/searxng/runs/7498482427?check_suite_focus=true#step:7:47).

I know I always forgot.

Done

**Comment by return42** [comment]
Seems youtube_noapi is also affected (I read https://github.com/iv-org/invidious/pull/2207).

Very interesting to see youtube_noapi and google have a similar API (at least for the consent).

Is it OK when I reword your commit message to include additional information about?

**Comment by unixfox** [comment]
> Seems youtube_noapi is also affected (I read [iv-org/invidious#2207](https://github.com/iv-org/invidious/pull/2207)).

It's also included in this commit.

> Very interesting to see youtube_noapi and google have a similar API (at least for the consent).

Well it's google behind in both cases after all :).

> Is it OK when I reword your commit message to include additional information about?

Sure

**Review by return42 — APPROVED** [review]
Thanks for this patch .. I didn't know that we can prevent redirects by setting the CONSENT cookie .. it was very interesting to me, to read what you guys do on invidious :+1:

**Pull request merged**
