### PR TITLE
[mod] switch default theme from oscar to simple

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

switch default theme from oscar to simple

## Why is this change important?

Thanks to the fabulous work from @dalf and @mrpaulblack the simple theme is now ready to become the default.  I tested the simple theme over 3 weeks in my daily usage and I can't find a reason why oscar should be longer the default.

## Open issues

- [ ] [Simple theme as the default theme](https://github.com/searxng/searxng/projects/1)
- [x] #463
- [x] #542
- [x] #368
- [x] #351

### CODE REVIEW

**Review by mrpaulblack — APPROVED** [review]
There is still ARIA, RTL layout missing and stuff like settings page is not mobile friendly... But I think we should make it default to get more user feedback for the simple theme and to make it more straight forward for new instance maintainer what the big changes of SearXNG in comparison to SearX are... LGTM :+1: 

[EDIT] Ping @dalf are u ok with changing to the simple by default?

**Comment by return42** [comment]
I forgot to fix the unit tests :facepalm: .. coming soon ..

**Comment by tiekoetter** [comment]
I think search autocomplete suggestions should be fixed in Chrome (and Safari) first, before making simple the default theme of SearXNG.

https://github.com/searxng/searxng/issues/542

**Comment by not-my-profile** [comment]
>There is still ARIA [..] missing

I'd consider that a blocker. Accessibility by default is important.

**Comment by return42** [comment]
>> There is still ARIA [..] missing

> I'd consider that a blocker. Accessibility by default is important. 

What quality would be sufficient, is it enough to sprinkle a few attributes here and there?

If ARIA is a blocker then we might as well close this PR right now. I don't have ARIA knowledge, I don't know anyone who has practical experience with or anyone who can test and grade ARIA additions .. do you?

[No ARIA is better than Bad ARIA](https://www.w3.org/TR/wai-aria-practices/#no_aria_better_bad_aria)

**Comment by not-my-profile** [comment]
Yes I have some experience. The fundamental basics of ARIA are actually very simple ... there is no excuse not to implement them.

E.g. the settings icon image has no alternative text for a screen reader (which can be fixed by simply adding an `aria-label`).

It's worth noting that `aria-label`s should also be translated so e.g. adding  `aria-label="{{_("Preferences")}}"` to the link would do the job.

Nowadays both Firefox and Chromium have accessibility issue reporting built into their developer tools, which can help spot accessibility problems. E.g. they report that the simple theme has contrast problems. We could also set up automatic accessibility testing in our CI with [lighthouse](https://github.com/GoogleChrome/lighthouse) (or [axe-core](https://github.com/dequelabs/axe-core) for more control). But it's worth noting that many accessibility problems cannot be detected automatically.

>What quality would be sufficient?

From the top of my head (this is accessibility in general not just ARIA):

* Every interactive UI element should have a label.
* Every visible UI element should be usable with only the keyboard (e.g. focusable via `Tab`).
* Text should have at least a contrast ratio of 4.5 (can be easily inspected with the developer tools).
* Always try to use the semantically appropriate HTML tags.
* The document should have a proper semantic hierarchy (e.g. with `h1` and `h2`).
* The behavior of interactive UI elements should always match the semantics implied by their markup (e.g. #498 violates that since the checkbox behavior is overridden via JavaScript without adding an appropriate ARIA tag ... which is a good example why it's generally a bad idea to just change behavior of semantic tags via JavaScript)

**Comment by return42** [comment]
> It's worth noting that `aria-label`s should also be translated so e.g. adding  `aria-label="{{_("Preferences")}}"` to the link would do the job.

I don't know .. should it be such easy? ... is `role='button'` sufficient enough? ...  W3C says [All interactive ARIA controls must be usable with the keyboard.](https://www.w3.org/TR/aria-in-html/#3rdrule)

EDIT: I wrote this comment while you edited your comment :smile:

**Comment by not-my-profile** [comment]
> All interactive ARIA controls must be usable with the keyboard.

`<a href="somewhere">some text</a>`

is 100% keyboard accessible. You can focus it and press `Enter` to open it.

>is `role='button'` sufficient enough?

`role=button` should generally **not** be added to proper links (with a working `href`). If the preferences link instead was `<a href=# onclick=openPreferences()>preferences</a>` then `role=button` would be appropriate ... since it's not an actual working link. (for such cases it's generally easier to simply use `<button>` instead though).

**Comment by return42** [comment]
May be I have to describe what my intention is ... I think the requirements to SearXNG are different:

1. There are use cases where a API is needed / this is covered by the JSON interface (my wet dream is a SearXNG network hosted by the [SearXNG community](https://searx.space/)  where every query is dispatched to a different endpoint-server).
2. The majority will use a smooth WEB interface with dynamic elements (JS) / this is the place where I see the simple theme.
3. There are use cases where a pure HTML & CSS interface is needed / for what we have to implement a different theme.
4. And we have uses cases where assistive technologies are used / for what we have to implement a different theme.

> The fundamental basics of ARIA are actually very simple ... there is no excuse not to implement them.

Overlaps exist at 2., 3. and 4. but I think there is more closeness between 3. and 4. than between 2. and 4.

**Comment by not-my-profile** [comment]
Your implication that being accessible requires a separate user interface is wrong (both for `noscript` as well as for people with disabilities), see [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement) and WCAG. I strongly oppose the idea of implementing separate "accessible" themes for the simple reason that maintaining two themes is more work than maintaining one theme (which unless I am mistaken is the very reason we want to consolidate our two themes into one in the long run).

>I think the requirements to SearXNG are different

If you'd like me to keep contributing, accessibility by default will have to be part of our requirements.

**Comment by dalf** [comment]
IMO, it is too soon:
* the RTL languages are not supported (we just had some translations). There is already a searxng-rtl.css file. A solution is some less macros. For example: `.ltr-left(5rem)` becomes `left: 5rem` in RTL languages and  `right: 5rem` in LTR language).
* at least fix some ARIA issues (for example, the preference icon doesn't have a label).

**Comment by mrpaulblack** [comment]
@return42 when you have time can you please rebase this PR?

**Comment by unixfox** [comment]
There is no infinite scrolling in the simple theme though, something I really like.

**Comment by mrpaulblack** [comment]
Yes that is true; Tho there is a PR for this: https://github.com/searxng/searxng/pull/812

But eventually we just need to make the move, since there is always going to be something that is not finished with the theme. We can fix this after making simple the default IMO. I mean its RN still possible to switch back to oscar for people that really want to use it still...

**Comment by return42** [comment]
> @return42 when you have time can you please rebase this PR?

OK, done ..

**Comment by mrpaulblack** [comment]
ok thanks; I am ok with merge... @dalf @unixfox @tiekoetter are u also ok with this merge? (thumbs up or down on this comment is enough)

**Comment by unixfox** [comment]
I half agree, ok for having by default in searxng but I'm going to keep oscar by default on my instance until infinite loading is available on simple theme.

**Pull request merged**
