### PR TITLE
draft: yandex engine (web, images, videos)

### PR DESCRIPTION
**Pull request by Austin-Olacsi**
## What does this PR do?

this draft shows my current progress on a yandex engine. it does not use xpath selectors yet and yes i am aware it needs some cleanup.

## Why is this change important?

once it is ready it will be a valuable addition

## How to test this PR locally?
make run

## Related issues

https://github.com/searxng/searxng/issues/961
https://github.com/searxng/searxng/issues/2181

web
images
videos

### CODE REVIEW

**Comment by unixfox** [comment]
won't be usable due to their anti bot protection like explained in

https://github.com/searxng/searxng/issues/961#issuecomment-1066559405

**Comment by Austin-Olacsi** [comment]
it's possible, 4get.ca does it, and we can do it too.

**Comment by return42** [comment]
> won't be usable due to their anti bot protection like explained in https://github.com/searxng/searxng/issues/961#issuecomment-1066559405

the old implementation we removed was very simple

--> https://github.com/searx/searx/pull/2566/files

> it's possible, 4get.ca does it, and we can do it too.

--> https://git.lolcat.ca/lolcat/4get/src/branch/master/scraper/yandex.php#L210

I think it's definitely worth trying out this PR (in a DRAFT)

**Comment by return42** [comment]
Further it might be help full to recall the comment from @thunder-coding

- https://github.com/searxng/searxng/issues/961#issuecomment-1793728114

**Comment by unixfox** [comment]
> it's possible, 4get.ca does it, and we can do it too

Did you see that they force you to use CAPTCHA in order to use the instance? This to reduce by a lot the bad traffic that may get the instance blocked.

@Austin-Olacsi @return42 I can guarantee you that once this will be merged into searxng then discovered by many more people. Yandex will become unusable on searxng because they will easily detect us as a "botnet".

That's what happened the previous time that yandex was in searxng.

@return42 Maybe a good middle ground is to have yandex as **inactive** engine by default. This way people has to enable it by themselves and this will probably reduce the likelyness of getting yandex blocked altogether on searxng.

**Comment by rohitrsm83** [comment]
Hello people, just a lay user here.

I notice now that the captchas are gone when I do a Yandex search. Perhaps it will be easier to integrate it into Searx now?

Thx

**Comment by return42** [comment]
Just for info: Yandex is now a propaganda machine --> [The Kremlin-engineered deal would see Russia's largest technology player fall entirely under Russian ownership, including a fund ultimately owned by oil major Lukoil (LKOH.MM) .. leading some within the Kremlin to push to nationalise Yandex ..](https://www.reuters.com/technology/yandex-nv-agrees-52-bln-sale-russian-assets-investor-consortium-2024-02-05/)

**Comment by rohitrsm83** [comment]
> Just for info: Yandex is now a propaganda machine --> [The Kremlin-engineered deal would see Russia's largest technology player fall entirely under Russian ownership, including a fund ultimately owned by oil major Lukoil (LKOH.MM) .. leading some within the Kremlin to push to nationalise Yandex ..](https://www.reuters.com/technology/yandex-nv-agrees-52-bln-sale-russian-assets-investor-consortium-2024-02-05/)

Thanks for the reply.

I was earlier given to understand that the reason for not including Yandex had nothing to do with politics and was instead because of the captcha issue. 

Anyway, as a lay user I can only request. 

Regards

**Comment by return42** [comment]
> I was earlier given to understand that the reason for not including Yandex had nothing to do with politics and was instead because of the captcha issue.

My comment was just for info .. I think we should not have any special political preferences in the SearXNG project :)

**Comment by rohitrsm83** [comment]
> > I was earlier given to understand that the reason for not including Yandex had nothing to do with politics and was instead because of the captcha issue.
> 
> My comment was just for info .. I think we should not have any special political preferences in the SearXNG project :)

Ok. no probs.

**Comment by Austin-Olacsi** [comment]
I've stopped working on this in favor of: https://github.com/searxng/searxng/pull/3401

**Comment by MorsMortium** [comment]
@Austin-Olacsi Since the other PR is closed, and the engine request of yandex is reopened, since they seem to not use captchas that aggressively anymore, could you please continue your work here?

**Comment by Austin-Olacsi** [comment]
@MorsMortium i have plans to work on this during my free time.

i've already found working xpath selectors for the web results, but for images and videos we will need to parse js. it is going to be a little bit tricky for me.

**Comment by return42** [comment]
We have a yandex_music engine (IDK the state), added in 

- 3c42252c https://github.com/searxng/searxng/pull/3234

this engine parses a JSON response / BTW take note of https://github.com/searxng/searxng/issues/961#issuecomment-2143710643

**Comment by Austin-Olacsi** [comment]
This PR is pretty low on my list of priorities right now so it may be a while before i can show anything great.

**Pull request closed without merging**
