### PR TITLE
Simple theme uppercase buttons

### PR DESCRIPTION
**Pull request by MontyQI**
## What does this PR do?
~~Changes simple theme. For now, changed search bar and colors.~~
Changes buttons text in simple theme to uppercase.

## Why is this change important?
It makes simple theme look more modern.

## How to test this PR locally?
``make node.env``
``make themes.simple``
``make run``
change to simple theme
## Additional resources
Search bar and some colors are from [https://github.com/paulgoio/searxng](url)

**Screenshots**
Screenshot_2022-01-26-12-14-20_2560x1440
Screenshot_2022-01-26-12-30-47_2560x1440

### CODE REVIEW

**Comment by mrpaulblack** [comment]
Well this PR is basically changes from my fork. In my fork I am using the colors from google... I dont think its a good idea to use those colors in this project upstream tbh (google probably has the rights to those colors or something). Also the impl. of the search bar in my fork is also pretty hacky tbh and I think this would need to be reworked to be usable in SearXNG upstream.

What I like is in https://github.com/searxng/searxng/pull/825/commits/4715e2f8046f3fcc288255f7b88b8de91738c943 changing the label to uppercase

But yeah all in all I am meh about this PR. I dont think its a good idea to use googles colors in a big project like SearXNG and I agree that the search bar needs to be reworked, but we should not use the hacky impl. of my fork. I already started refactoring the search bar here a while ago: https://github.com/mrpaulblack/searxng/commits/simple-theme-search-form

Also using material design buttons dont really fit in with the simple theme. There are hover effects, shadows and so on with those elements and with the simple theme we try to avoid those effects (Tho I think a shadow around search bar and autocomplete would be nice tbh)

**Comment by MontyQI** [comment]
I didn't know it was your fork. I think at least the changes of preferences colors are good idea. Now they look a bit yellow.

**Comment by return42** [comment]
> Now they look a bit yellow.

yellow? .. could you give an example?

FYI in https://github.com/searxng/searxng/pull/564 I (we) came to the conclusion that we leaf the colors unchanged.  If there comes the day we change the colors we should harmonize them with the SVGs.

Personally I would not apply this PR (sorry).

**Comment by mrpaulblack** [comment]
> yellow? .. could you give an example?

There is more blue in the google colors. For example the main background is blue-ish tinted with google when using the dark theme, while upstream in SearXNG the dark colors dont have the blue tint and appear more yellow-ish when comparing IMO.

How about this.. Can you change this PR to only include the changes to make the label uppercase, because I really like that change.

This evening I will make a draft PR for the search bar and we can discuss redesign there @MontyQI ?



Also just FYI: We dont need to touch the current blue accent colors. What we could do is just make all the dark colors slightly more blue upstream...
If you want to you can propose a PR with where you change those colors, but without using google colors @MontyQI

**Comment by MontyQI** [comment]
Ok I'll change it.

**Review by mrpaulblack — APPROVED** [review]
LGTM

**Comment by dalf** [comment]
Note: it breaks the existing translations in weblate.

I think weblate can make some magic to figure out that may be the translation for "Save" should be the one "save" with a minor change, but nothing of this is configure.

I don't know if we should uppercase the labels using CSS?

**Comment by return42** [comment]
> I don't know if we should uppercase the labels using CSS?

No, please not .. do not apply any magic on strings within the rendering layer.

> I think weblate can make some magic to figure out that may be the translation for "Save" should be the one "save" with a minor change, but nothing of this is configure.

IMO we should get a try and merge.  If all goes wrong, we have a really good and active translator community.

**Comment by mrpaulblack** [comment]
> I don't know if we should uppercase the labels using CSS?

I did not think about this; Hmm we would be more flexible in the future if we want to CAPS LOCK the whole button label for example, but is the CSS Uppercase going to work properly for every language LTR as well as RTL?

**Comment by return42** [comment]
>  but is the CSS Uppercase going to work properly for every language LTR as well as RTL?

No .. any magic on strings in the rendering will raise a lot of new questions and quirks .. please lets avoid such complications.

**Comment by return42** [comment]
> I think weblate can make some magic to figure out that may be the translation for "Save" should be the one "save" with a minor change, but nothing of this is configure.

@dalf: there is a "automatic suggestion" function ..

grafik

**Comment by dalf** [comment]
For information, there are the two versions "Save" and "save" : 
* https://github.com/searxng/searxng/blob/master/searx/templates/oscar/preferences.html#L492
* --> https://weblate.bubu1.eu/translate/searxng/searxng/en/?q=%22Save%22&sort_by=-priority%2Cposition&offset=2

**Pull request merged**
