### PR TITLE
Add PyCharm configuration files to .gitignore

### PR DESCRIPTION
**Pull request by ngosang**
## What does this PR do?

Add PyCharm configuration files to .gitignore

## Why is this change important?

PyCharm creates a folder called `.idea` in the project. This PR excludes those files from Git so they are not commited by mistake.

## How to test this PR locally?

Tested by me.

### CODE REVIEW

**Comment by return42** [comment]
Does it make sense to add a PyCharm configuration which might help others to get up a running PyCharm environment? 

By example for emacs users I added https://github.com/searxng/searxng/blob/master/.dir-locals.el and  there is also a PR for a `.editorconfig` https://github.com/searxng/searxng/pull/1736

**Comment by ngosang** [comment]
I never commit the IDE configuration into the repositories for these reasons:
* In the `.idea` folder the user-configuration and project-configuration are mixed. My configuration might not work for other users (for example, the Python version, Python path...). If I change something in my IDE, Git detects the change and I could commit by mistake.
* Pycharm and other IDEs are able to create all the configuration from scratch when you open a new project.
* There are too many IDEs / text editors to commit the configuration for all of them.

Said that, I'm open to any solution.

**Comment by return42** [comment]
> In the `.idea` folder the user-configuration and project-configuration are mixed. 

Thanks for clarify .. than we should not add the PyCharm config .. the `.dir-locals.el` and the `.editorconfig` I mentioned above include only settings related to the local SearXNG project and do not contain any user specific settings or absolute pathnames.

**Comment by dalf** [comment]
Related to https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000154070-How-to-gitignore-idea-files

**Pull request merged**
