### PR TITLE
[fix] remove twine from requirements-dev

### PR DESCRIPTION
**Pull request by return42**
SearXNG is a rolling release / we do not deploy packages on PyPi

### CODE REVIEW

**Comment by dalf** [comment]
These should be removed too:

* https://github.com/searxng/searxng/blob/08e524fc35d382e51725c2778fc97615851b8bc2/manage#L337-L348
* https://github.com/searxng/searxng/blob/08e524fc35d382e51725c2778fc97615851b8bc2/manage#L112-L113
* https://github.com/searxng/searxng/blob/08e524fc35d382e51725c2778fc97615851b8bc2/Makefile#L85
* https://github.com/searxng/searxng/blob/08e524fc35d382e51725c2778fc97615851b8bc2/docs/conf.py#L102

**Comment by return42** [comment]
Thanks for having attention --> [removed](https://github.com/searxng/searxng/compare/36c658638a354f00f7ce85392709569823654b5c..845f6acc32fa6ecb709885c4210dff921e44e79a)

https://github.com/searxng/searxng/blob/08e524fc35d382e51725c2778fc97615851b8bc2/docs/conf.py#L102

the last one is needed for the [documentation](https://docs.searxng.org/dev/engines/offline/sql-engines.html#engine-mysql-server): 

https://github.com/searxng/searxng/blob/08e524fc35d382e51725c2778fc97615851b8bc2/docs/dev/engines/offline/sql-engines.rst?plain=1#L116

**Review by dalf — APPROVED** [review]

**Review by Bnyro — APPROVED** [review]

**Comment by dalf** [comment]
Some leftover:
https://github.com/searxng/searxng/blob/c197c0e35e6eaa823d6ba8606df4e5a5c598a07b/manage#L282-L287
https://github.com/searxng/searxng/blob/master/Makefile#L83

**Comment by return42** [comment]
I can remove the build / but is not related to twine & pypi I think.

**Comment by dalf** [comment]
In the context of SearXNG, why build a Python package if this is not to upload it?
(real question, actually I use sdist/bdist_wheel only to upload the built packages)

**Pull request merged**
