### PR TITLE
Improve the layout of the search page on mobile

### PR DESCRIPTION
**Pull request by ormai**
## What does this PR do?

Now when a result is selected the content of the card doesn't shift. The preferences button is now visible on the left of the search bar. I've also tweaked margins and paddings so that the content mantains some space against the edges of the viewport.

changes

## Why is this change important?

Improves user experience and the page looks nicer.

## How to test this PR locally?

I've tested with the browser responsive mode.

### CODE REVIEW

**Comment by Bnyro** [comment]
Nice job, thank you for your PR!

Could you please split the changes in this PR into two commits, one where you do the code changes to the `search.less` and `style.less`, as well as an other commit which is auto-generated by `make static.build.commit`.

**Comment by ormai** [comment]
Ok. Done.

**Comment by return42** [comment]
@ormai thanks for your PR .. personally I think it is an improvement of the UI :+1: / but I will wait about the review from the other reviewers 

---

Some nits I have

- for your next PR don't use your master branch / create a feature branches for PRs
- I think the margin in the `@media screen and (max-width: @phone) {` should also be changed / see left screenshot below: the margin over the "Trefferanzahl 1.400.000". / on the right side we see the layout before this patch

```diff
diff --git a/searx/static/themes/simple/src/less/style.less b/searx/static/themes/simple/src/less/style.less
index 389b5798f..8bb10bb06 100644
--- a/searx/static/themes/simple/src/less/style.less
+++ b/searx/static/themes/simple/src/less/style.less
@@ -1015,7 +1015,7 @@ summary.title {
 
   #main_results div#results {
     grid-template-columns: 100%;
-    margin: 1rem 0 0 0;
+    margin: 0 auto;
   }
 
   #links_on_top {
```

image

**Comment by ormai** [comment]
@return42 thanks for the tip. I'll start doing that.

As for the margin, it looks better. I thought I'd removed a similar kind of margin but I totally overlooked that one.

**Review by Bnyro — APPROVED** [review]
Works as expected from my testing, well done :+1:

**Comment by Bnyro** [comment]
> @Bnyro thanks for the tip. I'll start doing that.
> 
> As for the margin, it looks better. I thought I'd removed a similar kind of margin but I totally overlooked that one.
>

PS: you probably wanted to respond to @return42, and not to me :wink:

**Comment by return42** [comment]
> PS: you probably wanted to respond to @return42, and not to me 😉

yes, he wanted :) .. and the implementation of my [request](https://github.com/searxng/searxng/pull/2742#issuecomment-1719915052) is in progress:

> thanks for the tip. I'll start doing that.

**Review by mrpaulblack — APPROVED** [review]
LGTM (can you please rebase and merge markus?)

**Pull request merged**
