### PR TITLE
add subdomain replacement to hostname_replace.py

### PR DESCRIPTION
**Pull request by Austin-Olacsi**
## What does this PR do?
you can now rewrite turtle.example.com to newsite.com/turtle
we can now move the subdomain.

## Why is this change important?

i use this and maybe other people would like to use it also.

## How to test this PR locally?

configure hostname replace like this:
`'(.*\.)?(?P<subdomain>[^.]+)\.fandom\.com$': 'breezewiki.com/\g<subdomain>'`

enable the hostname replace plugin, and search "patrick star"

and you can see, https://spongebob.fandom.com/wiki/Patrick_Star becomes https://breezewiki.com/spongebob/wiki/Patrick_Star

## Related issues

related to #1646
I didn't intend to close this in #2947

### CODE REVIEW

**Comment by return42** [comment]
I don't think we should drill the hostname_replace plugin any further, as the name suggests it was once intended to replace the hostname.   Later the blocking function was added ... we should not put more into it.

I would prefer it if we had a URL rewriter that can apply regular expressions to URLs and that offers other functions such as 

- Import of filter lists like
  - https://github.com/stroobants-dev/ublock-origin-shitty-copies-filter
  - https://github.com/quenhus/uBlock-Origin-dev-filter/tree/main
  - ...  
- Reading out the original URL for tracker links that are intended for forwarding / https://github.com/gorhill/uBlock/wiki/Strict-blocking#ability-to-parse-the-strict-blocked-url

**Comment by Austin-Olacsi** [comment]
So you are asking for a URL rewriter like this:

1. not part of the hostname_relplace plugin
2. can apply regular expressions to URLs
3. can import filter lists from an external source
4. can read tracker links and rewrite them to the intended destination URLs

**Comment by return42** [comment]
> So you are asking for a URL rewriter like this:  ...

yes, that would be cool stuff, we can implement it as a core component or as plugin.

Just brainstorming: 

May we can combine it with stuff from brave's goggle / goggle's syntax https://github.com/brave/goggles-quickstart/blob/main/goggles/quickstart.goggle 

- CopyCats removal: https://github.com/brave/goggles-quickstart/blob/main/goggles/copycats_removal.goggle
- https://github.com/search?q=brave+goggles&type=repositories

Limitation: SearXNG does not have an index --> we can only "profile & rate" URLs on a result page.

**Comment by NanashiTheNameless** [comment]
this does not appear to work anymore, it breaks hostname replace entirely when `  '(.*\.)?(?p&lt;subdomain&gt;[^.]+)\.fandom\.com$': 'antifandom.com/\g&lt;subdomain&gt;'` is included

**Comment by NanashiTheNameless** [comment]
> this does not appear to work anymore, it breaks hostname replace entirely when ` '(.*\.)?(?p&lt;subdomain&gt;[^.]+)\.fandom\.com$': 'antifandom.com/\g&lt;subdomain&gt;'` is included

nevermind, its just github copy being shit

**Comment by CIPH3RD** [comment]
for those stumbling across this thread looking to get AnonymousOverflow to work with SearXNG (properly), I tested the following regex in combination with adding this pull request to my instance (not sure why it hasn't been merged into main yet, it's great) and it works with both "/exchange/" subdomains as well as the regular ones (needed to prevent AnonOverflow from random misdirects and 404s).

 `` '(.*\.)?((?P<subdomain>[^.]+))?\.stackexchange\.com$' : 'anonymousoverflow.example.com/exchange/\g<subdomain>'``
   
 This Regular Expression needs to be used in combination with the regular one to work as a catch-all with AnonymousOverflow.
 
 keep up the great work!

**Comment by return42** [comment]
> with adding this pull request to my instance

Which PR do you refer?

**Comment by Austin-Olacsi** [comment]
@return42 Are you really really sure that you don't want to merge this PR? People are manually adding these changes to their own instances...

I don't foresee anyone else working on another solution...

**Comment by return42** [comment]
> I don't foresee anyone else working on another solution...

I don't know which is the better decision here.   Drilling the plugin will reduce the need for a better, [alternative solution](https://github.com/searxng/searxng/pull/3051#issuecomment-1868309357).  If we don't notice PRs like this, users may never get new features. It's a dilemma ... no matter what you decide, you can only make the wrong decision.

For those coming across here: can you please review the PR and leave your comment .. if we have more votes we should merge this PR :+1:

**Comment by Sommerwiesel** [comment]
I would really like this PR to get reworked for the new version and then merged...
Would also help improve what has been discussed here: https://github.com/searxng/searxng/issues/2619

**Comment by return42** [comment]
I close this PR since the plugin its based on is outed .. lets discuss further in https://github.com/searxng/searxng/issues/3682

**Pull request closed without merging**
