### PR TITLE
Theme: add a preference to center the results (Oscar) (2nd edition)

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

Same as description as #1281

TODO:
* [x] fix the mobile layout

## Related issues

related to
* #1169
* #1281
* #1286

### CODE REVIEW

**Comment by dalf** [comment]
The mobile layout should be fixed:
* The tablet layout is defined in a mixin in style.less
* The tablet layout is enabled with:
```less
@media screen and (min-width: @phone) and (max-width: @tablet) {lly.
  .center-aligment-no {
    .results-tablet();
  }
}
```
* The phone layout includes the tablet layout:
```less
@media screen and (max-width: @phone) {
  .results-tablet();
  ...
}
```

---

In style-center.less, `grid-template-columns: 60% 1fr;` has been replaced by `grid-template-columns: 60% calc(40% - @results-gap);` because it did worked as expected in Chrome.

---

Remaining minor issue: from 1275px to 1277px, the layout change three times. It seems the media queries do not work as expected at 1276px ( = `@tablet: 79.75em`).

**Comment by dalf** [comment]
> Remaining minor issue: from 1275px to 1277px, the layout change three times. It seems the media queries do not work as expected at 1276px ( = @tablet: 79.75em).

The issue is fixed, not in a nice way but it works.

Details:
```css
@media screen and (min-width: @phone) and (max-width: @tablet) {
   #example {
      margin-left: 1rem
   }
}

@media screen and (min-width: @tablet) {
   #example {
      margin-right: 1rem
   }
}
```

In this example, when the screen width is @tablet ( 1276px ), margins left and right are defined. To fix that, the rules for `(min-width: @tablet)` reset the values to one define in `style.less`.

If this is okay, then the PR is ready.

**Comment by return42** [comment]
> The issue is fixed, not in a nice way but it works.

I see the font size of the category names is changed three times (1275px, 1276px, 1277px) . but this is only a nit ..

In this PR I also tested RTL (persian) and I see the layout is broken when I **disable** the centered format (`center_aligment: false`) .. the result list is no longer placed on the right side (like it is in current master).

**Comment by dalf** [comment]
I haven't change anything about the source code:
image

Can you post a screenshot?

**Comment by return42** [comment]
> I haven't change anything about the source code:

Side effect?

With this PR:

image

In branch master:

image

**Comment by dalf** [comment]
From what I understand, the result are always centered.

On my laptop, with:
image

the result are on right side of the screen (after saving the preferences).

@mrpaulblack : can you give a try ? (or @tiekoetter or @unixfox or anyone interested in this feature)

**Review by return42 — APPROVED** [review]
> From what I understand, the result are always centered.

@dalf big sorry from mine: it was my issue .. I changed `center_aligment:` to `false` in the settings.yml but I did not realized, that I had saved centered results in the cookies :facepalm:

**Comment by dalf** [comment]
No problem :-) 
Thank you for checking again.

**Pull request merged**
