### PR TITLE
[feat] implement mariadb engine

### PR DESCRIPTION
**Pull request by glanham-jr**
## What does this PR do?

Implements the MariaDB engine

## Why is this change important?

 We currently support MySQL, this simply adds support for the community driven fork MariaDB

## How to test this PR locally?

You'll need to have a local instance of MariaDB. I was able to accomplish this by using docker as follows:

```bash
# Install pre-requisuites based on the following docs
# https://mariadb.com/docs/server/connect/programming-languages/c/install/
pip install mariadb 1.1.09 # I had issues with 1.1.10. You can also add this to requirements.txt if that is easier for testing
docker pull mariadb
docker run --name mariadbtest -e MYSQL_ROOT_PASSWORD=mypass -p 3306:3306 -d docker.io/library/mariadb:10.3
docker exec -it mariadbtest /bin/bash
mariadb -p
# enter 'mypass' to login
create database Foo;
create table Bar(Id int not null);
insert into Bar values (1), (2), (3);
exit # exit docker container
```

Then you can update the settings to the following:

```yml
  # Required dependency: mariadb
  - name: mariadb
    engine: mariadb_server
    database: Foo
    username: root
    password: mypass
    limit: 10
    query_str: 'SELECT Id from Bar WHERE Id=%(query)s'
    shortcut: mdb
```

Lastly, run searxng and search for one of the ids

```bash
make install
```

```
!mdb 1
```

## Author's checklist

 - [x] Review documentation of the engine if it is sufficient / done in a0f3b4fb07e5

## Related issues

#3859 

## Screenshots

image

### CODE REVIEW

**Comment by glanham-jr** [comment]
@unclemus

**Comment by unclemusclez** [comment]
Trying the following:
```
  - name: rss
    engine: mariadb_server
    database: ***
    username: ***
    password: ***
    limit: 10
    query_str: 'SELECT Id from Bar WHERE Id=%(query)s'
    categories: news
    search_type: news
    shortcut: rss
    disabled: false
```

image

error:
```
Traceback (most recent call last):
  File "/usr/local/searxng/src/searx/search/processors/offline.py", line 19, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/src/searx/search/processors/offline.py", line 15, in _search_basic
    return self.engine.search(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/src/searx/engines/mariadb_server.py", line 69, in search
    cur.execute(query_to_run, query_params)
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mariadb/cursors.py", line 310, in execute
    self._execute_text(self._transformed_statement)
mariadb.InterfaceError: Server has gone away
Mon Sep 30 09:44:43 2024 - uwsgi_response_write_headers_do(): Broken pipe [core/writer.c line 248] during GET /favicon.ico (192.168.2.69)
OSError: write error
Mon Sep 30 09:44:43 2024 - uwsgi_response_write_headers_do(): Broken pipe [core/writer.c line 248] during GET /static/themes/simple/img/favicon.png (192.168.2.69)
Mon Sep 30 09:44:43 2024 - uwsgi_response_write_headers_do(): Broken pipe [core/writer.c line 248] during GET /static/themes/simple/img/favicon.svg (192.168.2.69)
2024-09-30 09:44:50,372 WARNING:searx.engines.rss: ErrorContext('searx/engines/mariadb_server.py', 69, 'cur.execute(query_to_run, query_params)', 'mariadb.InterfaceError', None, ()) False
2024-09-30 09:44:50,372 ERROR:searx.engines.rss: engine rss : exception : Server has gone away
Traceback (most recent call last):
  File "/usr/local/searxng/src/searx/search/processors/offline.py", line 19, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/src/searx/search/processors/offline.py", line 15, in _search_basic
    return self.engine.search(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/src/searx/engines/mariadb_server.py", line 69, in search
    cur.execute(query_to_run, query_params)
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mariadb/cursors.py", line 310, in execute
    self._execute_text(self._transformed_statement)
mariadb.InterfaceError: Server has gone away
```

image
image


this seems safe enough to run on my normal instance so i will check stuff if there are any updates more rapidly.

update:
i dont know what i am doing but i think it works fine. i dont really know much aobut querying sql but i came up with the below for FreshRSS. It didnt work yet, but i'll get there.
FreshRSS is another open source project in case people want to delve into that as well.

image
```sql
SELECT freshrss_unclemusclez_entry.title, freshrss_unclemusclez_entry.author, freshrss_unclemusclez_entry.tags, freshrss_unclemusclez_entry.content_bin FROM freshrss_unclemusclez_entry WHERE freshrss_unclemusclez_entry.title LIKE %(query)s AND freshrss_unclemusclez_entry.author LIKE %(query)s AND freshrss_unclemusclez_entry.tags LIKE %(query)s AND freshrss_unclemusclez_entry.content_bin LIKE %(query)s
```
```sql
SELECT * FROM rss_kamala_.freshrss_unclemusclez_entry WHERE (CONVERT(title USING utf8) LIKE %(query)s OR CONVERT(author USING utf8) LIKE %(query)s OR CONVERT(content_bin USING utf8) LIKE %(query)s OR CONVERT(tags USING utf8) LIKE %(query)s OR CONVERT(attributes USING utf8) LIKE %(query)s)
```
image
it works but i still dont get any results

**Comment by glanham-jr** [comment]
I think your ANDs are cancelling each other out. Did you try OR in your query?

**Comment by unclemusclez** [comment]
`mariadb.ProgrammingError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LIMIT 10 OFFSET 0' at line 1`

i keep getting combinations of this which makes me think my syntax is correct and there is something else not working

**Comment by glanham-jr** [comment]
@unclemusclez Thanks for your continued testing. I added a `debug` log that emits the query so you can better diagnose the issue. If you enable verbose logging, you should be able to see the exact SQL Query causing issues.

**Comment by glanham-jr** [comment]
I'll format the code later.

**Comment by glanham-jr** [comment]
Added unit tests. Also renamed the tineye unit tests to match a naming convention.

**Review by return42 — APPROVED** [review]
I did not had luck on installing `pip mariadb` .. anyway, you already tested the SQL query .. I just added a commit to improve the documentation / thanks a lot for this PR :+1:

**Comment by unclemusclez** [comment]
cool so much love yas 
image

**Pull request merged**
