### PR TITLE
[mod] simple-theme: on small devices show category icon, not name

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

[mod] simple-theme: on small devices show category icon, not name

**before**

grafik

**after**

grafik

## How to test this PR locally?

To test I patched settings.yml

1. add a new category "TV" to see how *new* categories will be rendered (the icon)
2. activate autocomplete, to see autocompletion is positioned well
3. add `Content-Security-Policy` to check CSP

```diff
diff --git a/searx/settings.yml b/searx/settings.yml
index 305b254c..0ec979cd 100644
--- a/searx/settings.yml
+++ b/searx/settings.yml
@@ -16,7 +16,7 @@ search:
   # Existing autocomplete backends: "dbpedia", "duckduckgo", "google",
   # "startpage", "swisscows", "qwant", "wikipedia" - leave blank to turn it off
   # by default.
-  autocomplete: ""
+  autocomplete: "google"
   # Default search language - leave blank to detect from browser information or
   # use codes from 'languages.py'
   default_lang: ""
@@ -48,7 +48,7 @@ server:
 
   secret_key: "ultrasecretkey"  # change this!
   # Proxying image results through searx
-  image_proxy: false
+  image_proxy: true
   # 1.0 and 1.1 are supported
   http_protocol_version: "1.0"
   # POST queries are more secure as they don't show up in history but may cause
@@ -60,6 +60,7 @@ server:
     X-Download-Options: noopen
     X-Robots-Tag: noindex, nofollow
     Referrer-Policy: no-referrer
+    Content-Security-Policy: "default-src 'self'; img-src 'self' data: ;"
 
 ui:
   # Custom static path - leave it blank if you didn't change
@@ -70,7 +71,7 @@ ui:
   # it decreases the privacy, since the browser can records the page titles.
   query_in_title: false
   # ui theme
-  default_theme: oscar
+  default_theme: simple
   # Default interface locale - leave blank to detect from browser information or
   # use codes from the 'locales' config section
   default_locale: ""
@@ -1604,6 +1605,7 @@ engines:
   - name: mediathekviewweb
     engine: mediathekviewweb
     shortcut: mvw
+    categories: TV
 
   # - name: yacy
   #   engine: yacy
```

### CODE REVIEW

**Comment by mrpaulblack** [comment]
I like this the only problem I see with this PR: When a instance has multiple custom categories its just going to be the globe icon multiple times as a fallback. Can be confusing for new users since they wont know how to differentiate between the categories...

**Comment by return42** [comment]
> When a instance has multiple custom categories 

Right, this was also my first thought :smile: ..

I am working on a solution for customizable icons .. but this will be in another PR.

**Comment by mrpaulblack** [comment]
After checking this PR out again; I am not a big fan of this anymore. I think (especially for custom categories) the name is way more descriptive then an icon. With the name we also make sure that the category is big enough to press by design and different instances can have different categories for the same icon. Because of that I would like to close the PR in favor of keeping the current impl. on mobile.

**Comment by return42** [comment]
> I would like to close the PR in favor of keeping the current impl. on mobile.

May be there comes the time I will give it another try .. I changed PR from OPEN to DRAFT

**Pull request closed without merging**
