### PR TITLE
Simple theme: mobile layout: allow access to the preferences

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

Use [:placeholder-shown](https://caniuse.com/css-placeholder-shown) CSS selector which is supported since ~ 2017. If the browser doesn't support this selector, the preferences button remains hidden.

Front page:
image

With a query:
image

Without a query:
image

## Why is this change important?

Fix a UX bug

## Related issues

related #176 and #463

### CODE REVIEW

**Review by mrpaulblack — APPROVED** [review]
LGTM :+1: 

Just FYI: This makes the issue with scaling worse on mobile since the `#q` element of the search form does have some sort of min width (and the margin-right makes it worse):

image

**Comment by dalf** [comment]
It seems I miss something, I can't reproduce the issue :

image

---

With Chrome, I see a slight change of the width which change the whole page a little.

**Comment by mrpaulblack** [comment]
Try to make the width of the page smaller than 360px; The problem is that the `#q` input has some sort of min width. Meaning  when you make the width of the entire page smaller at some point the text input field does not get smaller. There are two things that can happen now:

* when touch input is disabled the page is going to have a horizontal scroll bar
* when touch input is enabled: the entire view-port gets smaller since there is now horizontal scroll bar allowed (I guess?)

The solution: Find a way to make the `#q` element of the search input smaller when the width of the entire page decreases (This issue already existed before this PR, but since the margin-right got added it got worse, since the effect starts earlier now); but tbh this can also be done in another PR, since the issue is also in the master branch and the phone also needs to be really small for this to happen...

[EDIT] maybe this only happens with firefox and not with cromium based browsers?

**Comment by dalf** [comment]
With Chrome, iPhone 5, DPI 2.0 :
image

**Pull request merged**
