### PR TITLE
Fix #2836

### LINKED ISSUE #2836: [Bug] Search box not in center in mobile view.
**Version of SearXNG** 2023.9.22+71358e9c6

**How To Reproduce**

Just open it on your phone.

**Screenshots & Logs**

**Additional context**
1. Find out which PR cause this.
2. solve it.

### PR DESCRIPTION
**Pull request by BernieHuang2008**
## What does this PR do?
just a quick fix of #2836 .

i've changed the css selector: the new style in https://github.com/searxng/searxng/commit/a76c8e4101dceb68cf7d846868e5e50e54461b08 will only be activated when in result page.

## Why is this change important?

UX

## Related issues
Closes #2836

### CODE REVIEW

**Comment by BernieHuang2008** [comment]
Ping @return42

**Comment by return42** [comment]
@BernieHuang2008 thanks a lot for your patch .. but @Bnyro has already posted https://github.com/searxng/searxng/pull/2833 .. I close this PR since #2833 is already merged.

**Comment by return42** [comment]
I reopen this PR .. may we pick up this PR to replace the #2833

@Bnyro will have a look at this PR .. could take a while / he just has other tasks :)

**Comment by BernieHuang2008** [comment]
sure. i will rebuild it and wait.

btw, can you reopen this PR? i still have some modifies (which can't sync with the PR when closed.)

**Comment by BernieHuang2008** [comment]
@return42 please reopen it thanks

**Comment by return42** [comment]
Sorry I'm no longer able to open this PR since you have deleted the branch :o .. the issue is discussed [here](https://gist.github.com/Farhan-Haseeb/fd4cbb476de4e2931c322d7bacb75e5f).

Just open another PR and leaf a link here / thanks.

**Pull request closed without merging**
